### PR TITLE
Open Sea - High Quality Images

### PR DESCRIPTION
**Pull request by skylarbarrera**
We were using the preview image, now we're using the original

before:  http://cloud.skylarbarrera.com/Screen-Shot-2021-02-02-00-10-59.14.png

after: http://cloud.skylarbarrera.com/Screen-Shot-2021-02-02-00-08-53.09.png

### CODE REVIEW

**Comment by mikedemarais** [comment]
this can cause problems when the original image is diff file formats like svg

**Comment by mikedemarais** [comment]
we need to either detect file format and only use original when it’s compatible 

or we should wait on this functionality until we ship the imgix images

**Comment by skylarbarrera** [comment]
Open sea now caches svg's as PNG's on their end (https://docs.opensea.io/docs/metadata-standards#section-metadata-structure)

I've added an svg check to fallback to preview_image for svg images

**Review by brunobar79 — APPROVED** [review]
I think this is safe enough to merge.

**Pull request merged**
