### PR TITLE
[TEAM2-328] Use Unique Id Pattern to Grab No Mainnet Addy Prices

### PR DESCRIPTION
**Pull request by derHowie**
## What changed (plus any additional context for devs)
OP+GMX do not have mainnet addresses. When updating L2 balances we now create a unique id to check account assets or generic assets for pricing information when adding the updated balance. I verified with @brunobar79 that this is, unfortunately for now, a common pattern within the app.

## Screen recordings / screenshots
Swapping for OP with an existing OP balance: https://recordit.co/NtihedGx0a
Swapping for OP without an OP balance: https://recordit.co/EPF3Cm3Yuf

## What to test
Test that OP/GMX do not disappear from the assets list when:
* Swapping OP on optimism (input and output)
* Swapping GMX on arbitrum (input and output)
* I included a video of swapping for OP without an existing OP balance to show that this logic doesn't mess with asset discovery, but we should probably check that too.

I opened this in favor of the previous PR: https://github.com/rainbow-me/rainbow/pull/3889 because I wanted to preserve the discussion there in case anyone wanted to reference it.

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels? (`team1/team2`, `critical path`, `release`, `dev QA`)
- [x] Did you test both iOS and Android?
- [x] If your changes are visual, did you check both the light and dark themes?
- [x] Added e2e tests? If not, please specify why
- [x] If you added new critical path files, did you update the CODEOWNERS file?
- [x] If no `dev QA` label, did you add the PR to the QA Queue?

### CODE REVIEW

**Comment by estebanmino** [comment]
nice videos!

**Review by estebanmino — CHANGES_REQUESTED** [review]
i swapped usdc to gmx on arbitrum and seems like we have an issue there https://www.loom.com/share/0834c703179d492f9c635f80cca47b24
sending a dm with some data

**Comment by derHowie** [comment]
@estebanmino commit: 9baa266d1c76cc5a5e36ab093af66cc066e5c8c8

case you caught when app is unaware of any L2 output token related data: https://recordit.co/tKiAdNDV57
original case of disappearing l2 tokens w/o mainnet addresses: https://recordit.co/P7zlNJ7Vnh

**Review by skylarbarrera — APPROVED** [review]
code looks good, behavior is working good for me while swapping on L2s

**Review by estebanmino — APPROVED** [review]
:cheff-kiss:
https://www.loom.com/share/ca62b18b1ddd4795bec96b144b460741

**Pull request merged**
