### PR TITLE
profiles: intro screen smog screen sizing

### PR DESCRIPTION
**Pull request by skylarbarrera**
Fixes TEAM2-404
Figma link (if any):

## What changed (plus any additional context for devs)

supports small devices up to ~666 height

## Screen recordings / screenshots

666 height - 
Screen Shot 2022-08-09 at 12 33 12 PM

pixel 4 - 
Screen Shot 2022-08-09 at 12 33 32 PM

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels? (`team1/team2`, `critical path`, `release`, `dev QA`)
- [x] Did you test both iOS and Android?
- [x] If your changes are visual, did you check both the light and dark themes?
- [x] Added e2e tests? If not, please specify why
- [x] If you added new critical path files, did you update the CODEOWNERS file?
- [x] If no `dev QA` label, did you add the PR to the QA Queue?

### CODE REVIEW

**Review by benisgold — COMMENTED** [review]
Screenshot_20220809_101515
hmmm the additional bottom padding makes this "find your name" button look questionably close to the bottom of the screen on pixel 2

**Comment by benisgold** [comment]
pixel 3 and galaxy a52 look good

**Review by benisgold — APPROVED** [review]

**Review by estebanmino — APPROVED** [review]
working on iphone se, iphone 8, iphone 11, pixel 4 and samsung s9 https://www.loom.com/share/5740a103775d4ff3962a0eba3aae0115

**Comment by jinchung** [comment]
The tests were successful on CI but the status update was hanging FYI

**Pull request merged**
