### PR TITLE
Redirect automatically to dapp for WC requests

### PR DESCRIPTION
**Pull request by brunobar79**
PoW connect via uniswap: https://recordit.co/YVKeJwM2ze
PoW swap via uniswap: http://recordit.co/KTBIfKzxjo
PoW full test via example.walletconnect.org: http://recordit.co/55tqoZCUzj

QA:  Test redirects from dapps using safari iOS, chrome iOS, chrome android and in app browsers like Twitter webview

Shoutout @mikedemarais  for the discovery

### CODE REVIEW

**Comment by christianbaroni** [comment]
🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🔥

one edge case we should handle, no redirect happens if you close rainbow or navigate to a diff app before connecting/confirming. could fall back to the old sheet if there’s no redirect

also when signing, it redirects you before the face id animation finishes, seems too abrupt. could use a slight delay when signing

later can add a success animation in the app before the redirect

**Review by estebanmino — DISMISSED** [review]
code lgtm!

**Comment by rorhug** [comment]
I love this work. However, could this make the common "connect then sign" flow a little more cumbersome?for example on https://foundation.app/

Apps that sign directly after you connect mean that you currently switch to rainbow, connect, sign (triggered automatically by the frontend in safari in the background), then return manually.

If this automatically inserts a switch post connect, I need switch back again to complete the sign. Put another way, many apps trigger sign without pressing the button like in the video linked above with demo.walletconnect.

I would love if signing (or any tx) directly post connect, could be hinted in the walletconnect api by the frontend.

**Comment by brunobar79** [comment]
> later can add a success animation in the app before the redirect

replied via twitter

**Comment by brunobar79** [comment]
> I love this work. However, could this make the common "connect then sign" flow a little more cumbersome? for example on https://foundation.app/
> 

Replied via twitter

**Review by estebanmino — APPROVED** [review]
lgtm

**Review by ibrahimtaveras00 — APPROVED** [review]
Looks good on both OS's, QA Passed 👍🏽

**Pull request merged**
