### PR TITLE
feat: add `walletconnect` debug context, swap in logger

### PR DESCRIPTION
**Pull request by estrattonbailey**
## What changed (plus any additional context for devs)
Adds `walletconnect` debug context and swaps in the new logger in our wallet connect related files. We could def do more logging, but in this PR I've only migrated what was there.

## Screen recordings / screenshots
None

## What to test
If it builds and runs it should be fine.

### CODE REVIEW

**Review by skylarbarrera — APPROVED** [review]
:shipit:

**Comment by jkadamczyk** [comment]
@estrattonbailey It looks like there are some more changes. Perhaps this is because the base branch was automatically changed due to the other one being merged to develop?

**Comment by estrattonbailey** [comment]
@jkadamczyk good call, did something silly. I squashed and rebased locally to reset 👍

**Review by jkadamczyk — APPROVED** [review]
Looks good to me! Thanks for rebasing Eric!

**Pull request merged**
