### PR TITLE
Remove unused RoundButtonSizeToggler component with Reanimated 1 usage

### PR DESCRIPTION
**Pull request by jkadamczyk**
Fixes RNBW-3384

## What changed (plus any additional context for devs)
* Removed unused RoundButtonSizeToggler component with Reanimated 1 usage

## Dev checklist for QA: what to test

* check preview, the app should work fine without it (no usages were found)

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels?
- [x] Added e2e tests? if not please specify why – just removed a component
- [x] If you added new files, did you update the CODEOWNERS file?

### CODE REVIEW

**Review by tchayen — APPROVED** [review]
🚀

**Review by brunobar79 — APPROVED** [review]
🚀

**Review by terrysahaidak — APPROVED** [review]

**Comment by jkadamczyk** [comment]
Seems like linter still complains gotta check it out it was clean _"on my machine"_

**Comment by jkadamczyk** [comment]
should be good now

**Pull request merged**
