### PR TITLE
Add rc-push script

### PR DESCRIPTION
**Pull request by brunobar79**
Fixes APP-####

## What changed (plus any additional context for devs)
Added a script that automates the following tasks:
- Creating a github tag for the active rc branch
- Pushing the tag to github
- Force pushing the RC branch into master
- Notifying swarmia about the release.

Requires https://github.com/rainbow-me/rainbow-env/pull/71

## Screen recordings / screenshots
Screenshot 2024-09-07 at 12 28 04 AM

Screenshot 2024-09-07 at 12 34 17 AM

## What to test
No need to test it. Confirmed locally working on the last release.

### CODE REVIEW

**Review by ibrahimtaveras00 — APPROVED** [review]
🐐

**Comment by brunobar79** [comment]
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@bruno/add-rc-push-script/47fa0275cbc27b250ac9e07e69c98eb656490870.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/@bruno/add-rc-push-script/47fa0275cbc27b250ac9e07e69c98eb656490870.ipa) for 47fa0275cbc27b250ac9e07e69c98eb656490870

**Comment by brunobar79** [comment]
\rebase

**Review by jinchung — APPROVED** [review]
🌮

**Pull request merged**
