### PR TITLE
Profiles: Make cover NFTs open NFT expanded state

### PR DESCRIPTION
**Pull request by jxom**
Fixes RNBW-4191
Fixes RNBW-4190

## What changed (plus any additional context for devs)

This PR opens the NFT expanded state for NFT cover photos.

## Screen recordings / screenshots

Android:
https://www.loom.com/share/0334e8e55ebf44ba9b26cabebaf69bd4

iOS:
https://www.loom.com/share/785ce1fa7d3c46959b80f88f109cfafa

## What to test

- Ensure that NFT cover photos open up the NFT expanded state of the cover NFT.
- Ensure that normal cover images are still zoomable.

### CODE REVIEW

**Review by skylarbarrera — APPROVED** [review]
looking good

**Review by estebanmino — CHANGES_REQUESTED** [review]
works everywhere but the profiles on the intro screen where it crashes https://www.loom.com/share/6840711be53c41f7bdee018416893348

**Comment by skylarbarrera** [comment]
we gucci: https://cloud.skylarbarrera.com/Screen-Recording-2022-08-05-13-50-08.mp4

**Review by estebanmino — APPROVED** [review]
i'm merging if tests pass https://www.loom.com/share/a8ba496cc87b40ab994b89ca15047bde

**Pull request merged**
