### PR TITLE
walletconnect: sanitize 712 signs

### PR DESCRIPTION
**Pull request by skylarbarrera**
Fixes APP-810

## What changed (plus any additional context for devs)

added sanitation for EIP 712 signs to match the BX

### CODE REVIEW

**Comment by jinchung** [comment]
Testing against https://se-sdk-dapp.vercel.app/
Screenshot 2023-10-27 at 10 38 24 AM

**Review by jinchung — CHANGES_REQUESTED** [review]
Left a comment with wc test dapp test

**Review by ibrahimtaveras00 — APPROVED** [review]
Looked good on both OS's 👍🏽 
- https://se-sdk-dapp.vercel.app/ 
- https://react-auth-dapp.walletconnect.com/ 
- opensea.io (connect & sign)

**Review by jinchung — APPROVED** [review]
🌮

**Pull request merged**
