### PR TITLE
Bump `react-native-safe-area-context`

### PR DESCRIPTION
**Pull request by perunt**
Fixes RNBW-TEAM1-76, RNBW-4047
Figma link (if any):

## What changed (plus any additional context for devs)
Updated `react-native-safe-area-context` to the latest version
Added top padding on the discover and settings screen for android
I checked places where used `react-native-extra-dimensions-android`, and also it's looks ok

https://linear.app/rainbow/issue/TEAM1-76/update-react-native-safe-area-context

## Screen recordings / screenshots
|Before|After|
|--|--|
|photo_2022-08-04 12 57 33|photo_2022-08-04 13 06 22|
|photo_2022-08-04 12 57 44|photo_2022-08-04 12 57 46|

## What to test
This affects all parts of the app since it's wrapped by `SafeAreaProvider`, but pay attention to the modal screens and the indents

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels? (`team1/team2`, `critical path`, `release`, `dev QA`)
- [x] Did you test both iOS and Android?
- [x] If your changes are visual, did you check both the light and dark themes?
- [ ] Added e2e tests? If not, please specify why
- [ ] If you added new critical path files, did you update the CODEOWNERS file?
- [ ] If no `dev QA` label, did you add the PR to the QA Queue?

### CODE REVIEW

**Review by terrysahaidak — APPROVED** [review]
LGTM

**Comment by skylarbarrera** [comment]
worth having real QA on this imo

**Review by tchayen — APPROVED** [review]
Works nicely on my device but def would benefit from proper QA.

**Comment by tchayen** [comment]
@perunt conflict appeared

**Review by estebanmino — COMMENTED** [review]
I agree that this one needs some QA, for example this is looking off on my s9
image

**Review by osdnk — APPROVED** [review]
code is ok

**Review by brunobar79 — APPROVED** [review]

**Comment by nickbytes** [comment]
> I agree that this one needs some QA, for example this is looking off on my s9, it was never perfect but now i can't see the gas section when the keyboard is open image

@perunt were you able to address this?

**Comment by perunt** [comment]
@nickbytes, a compromise was found in PR #4049, and the keyboard height for Android works better there, but only on the swap screen. Therefore, I suggest fixing[ the error ](https://github.com/rainbow-me/rainbow/pull/3917#pullrequestreview-1069848756)which showed by Esteban with a separate pull request after merging Terry's PR. Since this problem is not caused by `react-native-safe-area-context`, I guess it would be a good approach

**Review by BrodyHughes — APPROVED** [review]
No problems of note found on iPhone 13, Pixel 6 or S10+

**Pull request merged**
