### PR TITLE
Fix L2; Render ReactCoinIcon pngs in FastCoinIcon on Android too

### PR DESCRIPTION
**Pull request by terrysahaidak**
Fixes RNBW-3885

## What changed (plus any additional context for devs)

Now Android also uses ReactCoinIcon pngs just like iOS does after #3460 was merged. Android was using its own "FastCoinIcon" component, while on iOS we were still using old CoinIcon component. Now we use FastCoinIcon on both iOS and Android.

Also it will make FastBalanceCoinRow even a bit faster since we now render local assets for many of the icons instead of reaching to CDN for them.

## Dev checklist for QA: what to test

- Go to wallet screen
- Press on "all" to show all assets
- All the icons we display should be there
- You can verify if it works as expected by clicking on the asset to see its expanded state (with chart) - it still uses the old CoinIcon for that sheet in the left top corner
- It's best to use some profiles with like a huge amount of different assets to make sure all the assets are displayed correctly.
- THIS IS NOT ANDROID ONLY, iOS can be affected too

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels?
- [x] Added e2e tests? if not please specify why
- [x] If you added new files, did you update the CODEOWNERS file?

### CODE REVIEW

**Comment by tchayen** [comment]
@terrysahaidak there are some conflicts with develop (I guess the changes made by Christian?).

**Review by tchayen — APPROVED** [review]

**Comment by terrysahaidak** [comment]
I tried a few approaches to make it better and easier to understand, but this is the best so far.

But some icons can be broken due to  https://github.com/rainbow-me/rainbow/commit/ddb9cbf7c4f56390a38b8a441314ab34ba48d5c0

**Comment by BrodyHughes** [comment]
Looks mostly good. A few assets are not appearing correctly though. Specifically UNI on mainnet and L2 don't have an icon on Android. 

On iOS, UNI doesn't have an icon either and neither does OP. Additionally a weird bug is happening where the UNI assets are using the icon for my personal ENS as their icon. I also don't recognize the Rainbowwallet.eth wallet icon. 

Image from iOS (11)

**Comment by BrodyHughes** [comment]
Looks like maybe something was weird with my cache. A fresh install of the app + redownloading the fedora preview worked fine.

**Comment by terrysahaidak** [comment]
Seems like the UNI icon delay was not related to the PR and can be due to some JS/UI thread freeze, I cannot reproduce it.

**Pull request merged**
