### PR TITLE
Keep decimals as numbers consistent from fallback provider

### PR DESCRIPTION
**Pull request by jinchung**

### CODE REVIEW

**Review by brunobar79 — APPROVED** [review]

**Review by skylarbarrera — APPROVED** [review]
scenario is fixed 👍

**Comment by brunobar79** [comment]
That flag was added after I reviewed the PR. What are you guys trying to do with it?

**Comment by skylarbarrera** [comment]
> That flag was added after I reviewed the PR. What are you guys trying to do with it?

@brunobar79 the flag is to force the use of the fallback provider

**Comment by jinchung** [comment]
Just for future reference, it's a debug flag to help us test the scenario of "pretend zerion didn't work, let's let the fallback run" and subsequently test situations for those users

**Comment by brunobar79** [comment]
I'd add name that variable as `forceFallbackProvider` add it inside explorer:150

```
if (assets.length > 0) {
    return  forceFallbackProvider ? false : true;
}
````

That way you don't have to way 10 seconds every time you launch the app for the fallback to kick in

**Pull request merged**
