### PR TITLE
Optimize open savings and open small balances in AssetsList

### PR DESCRIPTION
**Pull request by osdnk**
Before:
 https://streamable.com/tuef97

After:
https://streamable.com/6wumtn

I know it looks slow after fixes anyway, but it's faster than before. Also, it's not a good phone, the list is very long and it's not a release mode.

### CODE REVIEW

**Comment by christianbaroni** [comment]
@osdnk one thing I noticed in the video, these buttons (all/less and edit) aren't aligned anymore:

Screen Shot 2020-12-11 at 2 20 14 PM

**Comment by osdnk** [comment]
You're right. I'll take a look

**Comment by osdnk** [comment]
@christianbaroni take a look

**Comment by skylarbarrera** [comment]
1 issue on android, looks good otherwise: http://cloud.skylarbarrera.com/Screen_Recording_20201214-100420.mp4

**Comment by skylarbarrera** [comment]
@osdnk seems the issue above is preexisting, the performance is just so much better now that its visible

**Review by mikedemarais — APPROVED** [review]
LGTM AMIGO

**Pull request merged**
