### PR TITLE
disable inlineRequires

### PR DESCRIPTION
**Pull request by brunobar79**
and also optional dependencies

### CODE REVIEW

**Review by osdnk — APPROVED** [review]
Correct but CI is failing

**Comment by osdnk** [comment]
@brunobar79

**Comment by osdnk** [comment]
I have rerun this.

**Comment by osdnk** [comment]
maybe now

**Comment by brunobar79** [comment]
Gonna close it because there are some parts of our app that depend on inline requires. Starting by the shim.js

**Pull request closed without merging**
