### PR TITLE
Upgrade reanimated to 2.4.1

### PR DESCRIPTION
**Pull request by terrysahaidak**
Fixes RNBW-2471

## What changed (plus any additional context for devs)

In the recent 2.4.0 release of Reanimated, there was one very specific fix we really need to improve the app's performance - Hermes Profiler now won't crash the app because of this fix
https://github.com/software-mansion/react-native-reanimated/pull/2842
Also, there was a number of performance improvements, you can learn more about them here:
https://github.com/software-mansion/react-native-reanimated/releases/tag/2.4.0

The 2.4.1 version only has a few small bugfixes.

## PoW (screenshots / screen recordings)

https://user-images.githubusercontent.com/7809008/152974517-54cae432-fe8f-4aac-b3e1-82d9a0f63bbb.mp4

## Dev checklist for QA: what to test

Each Reanimated 2 release can have some random crashes so it means that we need to test all the animations in the app

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels?

### CODE REVIEW

**Review by osdnk — APPROVED** [review]
I run this on iOs and seems to be ok! However, I opt for full regression for this

**Review by tchayen — APPROVED** [review]
Worked for me.

**Comment by ibrahimtaveras00** [comment]
No crashes, however, the only thing I did spot was some red when searching an ENS name on Android (works fine on iOS) 

seen here = https://recordit.co/oxKJ6c2otK

Screen Shot 2022-03-02 at 2 44 07 PM

not sure if we would consider this a blocker to merge this ticket or not

**Review by ibrahimtaveras00 — APPROVED** [review]
👍🏽

**Review by skylarbarrera — APPROVED** [review]
👌

**Pull request merged**
