### PR TITLE
filter pools from swap and asset list

### PR DESCRIPTION
**Pull request by skylarbarrera**
Fixes RNBW-2227 & RNBW-2228

## What changed (plus any additional context for devs)
regression from asset list changes

we may want to do this filtering upstream but for now i'm handling the same as hidden tokens.

## PoW (screenshots / screen recordings)
before asset list: https://cloud.skylarbarrera.com/Screen-Recording-2022-01-16-02-49-26.mp4
after asset list: https://cloud.skylarbarrera.com/Screen-Recording-2022-01-16-02-48-46.mp4

before swap: https://cloud.skylarbarrera.com/Screen-Recording-2022-01-16-01-50-00.mp4
after swap: https://cloud.skylarbarrera.com/Screen-Recording-2022-01-16-01-49-35.mp4

## Dev checklist for QA: what to test
should filter out pool tokens from swap & assets

## Final checklist
[x] Assigned individual reviewers?
[x] Added labels?

### CODE REVIEW

**Review by jinchung — DISMISSED** [review]
I believe this has been broken for a bit outside of the asset list changes (it's in prior releases)

If you search for `uniswapV2` you'll find an assetType that should be filtered out here: https://github.com/rainbow-me/rainbow/blob/develop/src/redux/data.js#L559

Can we first check what's going on here? This should automatically remove it from swap or asset list

**Comment by skylarbarrera** [comment]
closing in favor of: https://github.com/rainbow-me/rainbow/pull/2840

**Review by osdnk — CHANGES_REQUESTED** [review]
OK for removing from the swap list, is there a reason for removing from the token list?

I 100% disagree with the location of those changes? `useMemoBriefSectionData.ts` is supposed to contain only things related to the local layout/interactions. Things like this should be located in other places where we sort and filter tokens - ie., in selectors.

**Review by osdnk — CHANGES_REQUESTED** [review]
The code looks good. 100% for removing from the swap list, is there a reason for removing from the token list?

I 100% disagree with the location of those changes? `useMemoBriefSectionData.ts` is supposed to contain only things related to the local layout/interactions. Things like this should be located in other places where we sort and filter tokens - ie., in selectors.

**Pull request closed without merging**
