### PR TITLE
Fix secret phrase display

### PR DESCRIPTION
**Pull request by pugson**
Fixes RNBW-4265
Fixes TEAM2-470
Fixes TEAM1-133

## What changed (plus any additional context for devs)
- Fixed button shadow clipping on Android
- Fixed secret phrase display container on Android
- Fixed secret phrase display container dark mode on iOS
- Fixed secret phrase button having the wrong color with dark mode
- Fixed biometrics explainer position and padding
- Discovered and reported RNBW-4339

## Screen recordings / screenshots
| Android Button Before | Android Button After |
|-----------------------|----------------------|
| Screenshot_20220819-224223 | Screenshot_20220819-231618 |

| Android Secret Before | Android Secret After (Light) | Android Secret After (Dark) |
|-----------------------|------------------------------|-----------------------------|
| Screenshot_20220819-224233 | Screenshot_20220819-230852 | Screenshot_20220819-230912 |

| iOS Secret (Light) | iOS Secret (Dark) |
|---|---|
| CleanShot 2022-08-19 at 11 43 00 PM@2x | CleanShot 2022-08-19 at 11 43 34 PM@2x |

| View Secret Button (Light) | View Secret Button (Dark) |
|---|---|
| CleanShot 2022-08-27 at 01 27 29 AM@2x | CleanShot 2022-08-27 at 01 27 37 AM@2x |

## What to test
Looking at your secret phrase & copying it on iOS and Android.

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels? (`team1/team2`, `critical path`, `release`, `dev QA`)
- [x] Did you test both iOS and Android?
- [x] If your changes are visual, did you check both the light and dark themes?
- [x] Added e2e tests? If not, please specify why (only visual changes)
- [x] If you added new critical path files, did you update the CODEOWNERS file?
- [x] If no `dev QA` label, did you add the PR to the QA Queue?

### CODE REVIEW

**Review by skylarbarrera — APPROVED** [review]
🤌

**Review by tchayen — APPROVED** [review]
Works great, checked on both Android and iOS 🙇

**Review by estebanmino — APPROVED** [review]
code lgtm
android and ios lgtm
💅

**Review by terrysahaidak — APPROVED** [review]

**Comment by tchayen** [comment]
@pugson the TF [failed](https://app.bitrise.io/build/3bf6d37a-f78f-4e9d-a168-c2f423df11ad) because of app version number. I had similar issue and Esteban helped me and bumped the number. You can merge current develop, re-run and it should be fine.

**Review by BrodyHughes — APPROVED** [review]
🚀

**Pull request merged**
