### PR TITLE
Add i18n tags for alerts.

### PR DESCRIPTION
**Pull request by marco**
## What changed (plus any additional context for devs)

Updates language files to use i18n for remaining in-app alerts. Also, alphabetizes tags in language files. There should be no functionality changes here.

## PoW (screenshots / screen recordings)

App compiles and runs successfully:

Screen Shot 2022-06-22 at 8 44 48 AM

i18n checker:

```
Checking file "../rainbow-me/src/languages/_english.json":
    ✅ No errors found for "../rainbow-me/src/languages/_english.json".

Checking file "../rainbow-me/src/languages/_french.json":
    ✅ No errors found for "../rainbow-me/src/languages/_french.json".

Note, this script currently **does not** support interpolated translations such as `lang.t(`my.${variable}.based.${path}`).
    🔶 Manual check required for "lang.t(`time.${unit}.${length}.${plurality}`)".
```

## Dev checklist for QA: what to test

- Ensure that app compiles/runs successfully.
- Ensure all alerts work as expected

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels?
- [x] Added e2e tests? if not please specify why (N/A, no new functionality)
- [x] If you added new files, did you update the CODEOWNERS file? (No new files)

### CODE REVIEW

**Review by estebanmino — APPROVED** [review]
went one by one checking the code, and went through the app checking alerts where it made sense. LGTM!

**Review by terrysahaidak — APPROVED** [review]
Looks good. But in my opinion, when we add translation for buttons, the key should not be direct translation, like `alert.yes` and `alert.no` but instead `alert.confirm` and `alert.decline` since "yes" and "now" words directly might now work for a specific language that might confuse the translators.

**Comment by marco** [comment]
@terrysahaidak Thanks! That's a fair point. Initially, we did use more generic tags. We switched to matching the text to make the tags more searchable; there is a bit more discussion in Slack [here](https://rainbowhaus.slack.com/archives/C02K1GQKRKR/p1643202360006900).

**Review by skylarbarrera — APPROVED** [review]
👑

**Review by BrodyHughes — APPROVED** [review]
I'm unsure how to trigger all of the alerts, but I checked most of them and they looked good / worked & triggered when they were supposed to. I couldn't get the "Looks like you already imported this wallet!" to trigger here or in prod, so I'll create a ticket for that.

**Pull request merged**
