### PR TITLE
Remove axios

### PR DESCRIPTION
**Pull request by bcomnes**
This replaces axios with a small wrapper that does roughly the same thing, relying on fetch internally.

### CODE REVIEW

**Comment by bcomnes** [comment]
Places where I hand tested each one of these API calls:

- gasPrices.js: tested in the swap screen
- opensea-api.js: tested in the wallet NFT view screen
- wyre.js ???
- preferences.js: when loading the app
- additionalAssetData.js when you click on a token in the discover list

**Comment by bcomnes** [comment]
Going to QA this with @skylarbarrera tomorrow morning, but other than wyre, everything seems to work.

**Review by skylarbarrera — APPROVED** [review]
very nice 💯

**Comment by bcomnes** [comment]
Bye bye axios!

**Pull request merged**
