### PR TITLE
Remove bignumber.js

### PR DESCRIPTION
**Pull request by brunobar79**
Fixes RNBW-1803

## What changed (plus any additional context for devs)
- removed `bignumber.js` dep
- Added `react-native-bignumber`
- Patched ethers to use `react-native-bignumber` ( also made sure `elliptical` still uses the js implementation for now)
- rewrote all the utilities functions to use JS when possible
- Operations that require floating point big numbers are now being done by `FixedNumber` from ethers, which supports decimals.

Based on what Terry measured on this branch, it improves performance of  `sortAssetsByNativeAmount` by 30 - 40%.

## PoW (screenshots / screen recordings)

This Branch vs Develop
Screen Shot 2022-04-14 at 12 30 39 AM           Screen Shot 2022-04-14 at 12 30 39 AM

## Dev checklist for QA: what to test
Unfortunately this require full regression to make sure all the numbers are displayed in the same exact way as prod.

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels?
- [ ] Added e2e tests? if not please specify why - Already handled
- [ ] If you added new files, did you update the CODEOWNERS file? - Not needed

### CODE REVIEW

**Review by ibrahimtaveras00 — APPROVED** [review]
Values appear correct in app and txn data matches etherscan/arbiscan/polygonscan/optimistic.etherscan 
QA Passed 👍🏽

**Review by osdnk — COMMENTED** [review]
The general problem I observe is the fact we're using JS numbers for arithmetical operations. 
This is IMO wrong because that's the advantage of BigNumbers that we're NOT relying on JS number's precision and our motivation for using this library is that we need it.

If you claim that those (floating-point JS numbers) precisions are sufficient and we are okay with small mistakes (in 65th bit and following), then we no longer need big numbers (the motivation for using this lib disappears) and this is enough to just call `parseFloat` as soon as we get those data and then convert them back if we'll need this for anything (like contract interactions) and in-app use regular JS arithmetical operations.

However, I believe this is not what you want. So e.g., comparisons should be done more "manually" (see example in this lib I just found https://github.com/MikeMcl/bignumber.js/blob/master/bignumber.js#L2789).

**Comment by osdnk** [comment]
image

That's what I see. I'll fix this on my branch

**Comment by brunobar79** [comment]
Closed in favor of #3289

**Pull request closed without merging**
