### PR TITLE
Fix animated numbers on savings in Android

### PR DESCRIPTION
**Pull request by osdnk**
`tabular-numms` does not work for some reason, but we can skip it I guess for now.

### CODE REVIEW

**Comment by osdnk** [comment]
https://streamable.com/m2glyz

**Comment by brunobar79** [comment]
@osdnk Should we split the number and the symbol to two different components and set the wrapper for the number to have a min / fixed width, that way the symbol (DAI, WBTC, BAT) it's not jumping around while the number changes?

**Review by brunobar79 — APPROVED** [review]
💯

**Comment by osdnk** [comment]
I think we can just make `tabular-nums` workbale

**Pull request merged**
