### PR TITLE
Initial conversion of `src/handlers` to TypeScript.

### PR DESCRIPTION
**Pull request by marco**
## What changed (plus any additional context for devs)

This PR rebases @brunobar79's addition of the ts-migrate tool and sets up initial types for `src/handlers` as well as fixes some linter issues. This mostly is filled with `any` types for now, and future PRs can add more detailed types. There should be no functionality changes here.

## PoW (screenshots / screen recordings)

App runs as expected: 

Screen Shot 2021-12-21 at 5 24 32 PM

## Dev checklist for QA: what to test

 - Linting/compiling should complete successfully.

## Final checklist
[x] Assigned individual reviewers?
[x] Added labels?

### CODE REVIEW

**Review by brunobar79 — CHANGES_REQUESTED** [review]
Code looks good, however there are changes on the lockfile that are causing this PR to fail on CI and should be reverted.

**Review by jinchung — APPROVED** [review]
Approval pending addressing Bruno's comment and rebasing

**Comment by marco** [comment]
@brunobar79 Okay, I reverted the lockfile change, but a couple things I'm noticing:

1. Bitrise keeps failing, and in particular seems to get stuck at the dependency installation phase. I can't figure out why this is, so please let me know if you have any ideas!
2. I remember on our call earlier you mentioned that a JSON file might need to be changed now that the files have been renamed. I made the change to that file on my end to fix an error, but wasn't sure how to push it (since it's not tracked in this repo). Please let me know how to approach that for this PR. 

Thank you!

**Review by brunobar79 — APPROVED** [review]
🚀

**Pull request merged**
