### PR TITLE
Initial work to replace full-screen menus on Android with Popup menu

### PR DESCRIPTION
**Pull request by osdnk**
Fixes RNBW-4008

Figma link (if any):

## What changed (plus any additional context for devs)

image

I implemented the integration with the library. I needed to fix this a bit because when we quickly pressed the navigation action after opening many, the menu is not yet shown so this opens over the new screen (e..g, modal). SO I had to make a patch and call the function on each navigation (`src/navigation/onNavigationStateChange.js`).

See design: https://rainbowhaus.slack.com/archives/CGUNEHL9K/p1658742754709779?thread_ts=1658396734.255119&cid=CGUNEHL9K

## Screen recordings / screenshots
https://streamable.com/ofbllh

## What to test
Check if this menu is working, buttons are ok. 
Check if the menu is dismissing even when we very quickly pressed some navigation action (before the menu actually appeared)

### CODE REVIEW

**Comment by estebanmino** [comment]
i'm getting this error when creating new wallet 
image

i got the error twice, first i did `yarn:setup` and got the error, then i did `rm -rf node_modules && yarn:setup` and got the error again

**Comment by osdnk** [comment]
oh, thanks, I will fix it!

**Review by brunobar79 — APPROVED** [review]
Reviewed native code of new dep and LGTM

**Review by estebanmino — APPROVED** [review]
niice

**Pull request merged**
