### PR TITLE
Vertical Jittering on swap screen 

### PR DESCRIPTION
**Pull request by perunt**
Fixes TEAM1-106
Figma link (if any):

## What changed (plus any additional context for devs)
There are several problems on the Swap screen related to focusing; this pr fixes only one of them - jittering when switching currencies

before: https://user-images.githubusercontent.com/48593211/185408415-7d2276d1-6925-4c9e-a3b7-85fa85a3b8bf.mp4
after: https://user-images.githubusercontent.com/48593211/185409128-a549d122-6bf3-4631-8712-24a50843156b.mp4

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels? (`team1/team2`, `critical path`, `release`, `dev QA`)
- [x] Did you test both iOS and Android?
- [x] If your changes are visual, did you check both the light and dark themes?
- [ ] Added e2e tests? If not, please specify why
- [ ] If you added new critical path files, did you update the CODEOWNERS file?
- [ ] If no `dev QA` label, did you add the PR to the QA Queue?

### CODE REVIEW

**Review by ibrahimtaveras00 — CHANGES_REQUESTED** [review]
still seeing the bounce issue on Google Pixel 5a OS 12

seen here:

https://user-images.githubusercontent.com/41752922/185505159-09db5961-a4b2-4dc7-9616-a8cc441f43bf.mov

**Comment by ibrahimtaveras00** [comment]
@BrodyHughes, you want to check on Pixel 6?

**Comment by perunt** [comment]
My PR was based on using the cached value of Numpad height, but it was a bit wrong as measuring keyboard height is tricky for android. On IOS, we have the same size for all keyboards, but on Android, we don't. There is no way to know the keyboard height before it's open. So I close this PR in favor of #4049. In #4049, the numpad keyboard has dimensions of the tallest keyboard, thanks to that, we have no jittering but have a kind of space between keyboard and content as in real life, a numpad keyboard is a bit lesser than a default keyboard.

**Pull request closed without merging**
