### PR TITLE
App error boundary to avoid white screen crashes (do not merge)

### PR DESCRIPTION
**Pull request by nicoglennon**
Fallback error component when an uncaught error hits the top of the DOM tree -- avoid white screen of death. Error Boundary component is a Class component due to the error-catching APIs still not being available in hooks 😅

Screen Shot 2021-07-21 at 2 50 02 PM

FYI if testing in development mode, you can’t actually click the reset button because the React Native LogBox alerts modal background doesn’t go away after dismissing the alert.

Fixes RNBW-1370.

### CODE REVIEW

**Comment by nicoglennon** [comment]
Error boundary PoW: https://www.loom.com/share/413a33de3d2b48a98905db5d02833a5a

**Comment by nicoglennon** [comment]
This PR is waiting for a solution to the `NSInternalInconsistencyException: UIViewControllerBuiltinTransitionViewAnimator can only operate on a container view of type UITransitionView` errors that seem to be related to the Discover Sheet. For some reason rendering the Error Boundary Fallback throws the `NSInternalInconsistencyException` every single time, crashing the app before the error screen can be seen. This does not happen when the `DiscoverSheet` component is commented out. Although it doesn't change the user experience (the app crashes anyways), it could muddle the error logs in Sentry by adding a `NSInternalInconsistencyException` with every uncaught JS error that is thrown, so will wait to merge for now.

**Comment by nicoglennon** [comment]
After testing with Michal's latest changes this PR is now ready to go! @skylarbarrera

**Review by skylarbarrera — APPROVED** [review]
👌

**Comment by skylarbarrera** [comment]
@brunobar79 not merging in case you want to take a look otherwise lgtm and and i can push a release out

**Pull request merged**
