### PR TITLE
Fix navigating to the wrong screen while importing on Android

### PR DESCRIPTION
**Pull request by osdnk**
Fixes RNBW-3938

## PoW (screenshots / screen recordings)

https://streamable.com/0nfv09

## Dev checklist for QA: what to test

Try importing, adding a new wallet, importing with ENS, seeds etc.  Use iOS as a reference 

Also, see if the swap flow is not broken

### CODE REVIEW

**Review by tchayen — APPROVED** [review]
Works good for me.

**Comment by nickbytes** [comment]
@osdnk this seems like a significant change since it may affect all of our navigation. I see that `react-native-pager-view` is a continuation/migration of `react-native-community/viewpager`, but it seems like bumping this many minor versions (+ potential differences?) may be a good reason for us to go through full QA flow. 

What do you think? Could you explain more reasoning as to why this _shouldn't_ go through the full QA flow?

**Comment by osdnk** [comment]
Hey, 
I don't think this is enough reason for a full QA. This was migrated from `@react-native-community/viewpager` to `react-native-pager-view` because of purely "political| reasons. This is the same repo maintained by the same guys. 

Also, it might seem this is a big change. This is not really a big thing - the reason why this is major is because of the reasons explained in #3506. The rest of the changes are some minor bug fixes.

So i don't see a reason for any QA intervention except regular checks while releasing.

**Comment by nickbytes** [comment]
@osdnk I think it's difficult to tell what changes are worthy of the `dev QA` label, we should continue to talk about this. I appreciate you testing out our new processes and discussing where they may or may not work. 

Here's a few reasons why I think a change like this deserves the full QA process:

1. **Not all version bumps are created equal.** This specific bump includes 50+ commits, some which may have unrelated changes or regressions. It's hard to tell what might have changed looking at the history. Other scenarios may have version bumps with relatively few changes, and we may be able to review those changes and say w/ confidence that "nothing has changed that would affect our users" – I don't believe this is the scenario in this instance, but please tell me if I'm wrong here and you were able to review all changes in between.
2. **This PR doesn't contain an exhaustive list of what to test.** I think PRs with an exhaustive testing list that covers nearly all possible scenarios will be better candidates for the `dev QA` label. I would guess it may even be hard to create an exhaustive list since this dependency affects app-wide navigation. Again, please let me know if my understanding is wrong here.
3. **Bugs resulting from this change could deem the app unusable.** We want to have high confidence that we're not breaking something core to every users' experience. Bugs in navigation will likely not go unnoticed, whereas other changes that are less critical to the users' experience may be acceptable, for example styling fixes or changes to less frequently visited screen/components.

What do you think?

**Comment by osdnk** [comment]
@nickbytes ok, let's add this to the QA

**Review by terrysahaidak — APPROVED** [review]

**Review by skylarbarrera — APPROVED** [review]
things looking good to me but def want QA 🥇

**Comment by BrodyHughes** [comment]
dm'd Michal a couple concerns!

**Review by perunt — APPROVED** [review]
Works good for me

**Review by BrodyHughes — APPROVED** [review]
Looks good! Working as intended.

**Review by nickbytes — APPROVED** [review]

**Pull request merged**
