### PR TITLE
Consolidate env prod vs dev keys usage

### PR DESCRIPTION
**Pull request by jinchung**
Related to APP-2008

## What changed (plus any additional context for devs)
* Cleans up more unused configs
* Consolidates some keys that are prod vs staging (will create a separate followup PR for creating separate staging vs prod configs.)
* Associated with: https://github.com/rainbow-me/rainbow-env/pull/73

## Screen recordings / screenshots

Screenshot 2024-11-07 at 11 36 52 AM
Screenshot 2024-11-07 at 11 37 12 AM
Screenshot 2024-11-07 at 11 37 24 AM
Screenshot 2024-11-07 at 11 37 36 AM

## What to test
* wallet data still behaves as expected
* NFT related data (mints, offers, nft metadata) looks the same

### CODE REVIEW

**Review by walmat — APPROVED** [review]
LGTM. One question: Why do we alias some env vars inside env.ts and not some others? One example in this PR is `RESERVOIR_API_KEY`

**Review by benisgold — APPROVED** [review]

**Comment by brunobar79** [comment]
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@jin/prod-dev-env/74e7f592171d8ceadaf551b084b02fbd25d85c34.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/@jin/prod-dev-env/74e7f592171d8ceadaf551b084b02fbd25d85c34.ipa) for 74e7f592171d8ceadaf551b084b02fbd25d85c34

**Comment by jinchung** [comment]
> LGTM. One question: Why do we alias some env vars inside env.ts and not some others? One example in this PR is `RESERVOIR_API_KEY`

I think it started off with the IS_PROD vs not and some were added there in order to distinguish between PROD vs STAGING envs and expose them. Now that we don't need to do that for the RESERVOIR key, I'll follow up in another cleanup PR and remove the instances that use the env.ts for it.

**Comment by brunobar79** [comment]
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@jin/prod-dev-env/3da66cc42968572553f70f8332a58092b00e2a80.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/@jin/prod-dev-env/3da66cc42968572553f70f8332a58092b00e2a80.ipa) for 3da66cc42968572553f70f8332a58092b00e2a80

**Pull request closed without merging**
