### PR TITLE
Update WC dapp display treatment

### PR DESCRIPTION
**Pull request by brunobar79**
Fixes RNBW-####

## What changed (plus any additional context for devs)
Follow up PR based on earlier convos.

## PoW (screenshots / screen recordings)
TBD

## Dev checklist for QA: what to test
WC connection prompt will display all dapps the same way

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels?
- [ ] Added e2e tests? if not please specify why
- [ ] If you added new files, did you update the CODEOWNERS file?

### CODE REVIEW

**Review by osdnk — APPROVED** [review]

**Review by jinchung — APPROVED** [review]
🌮

**Review by skylarbarrera — APPROVED** [review]

**Review by ibrahimtaveras00 — CHANGES_REQUESTED** [review]
👎🏽

**Review by ibrahimtaveras00 — APPROVED** [review]
Looks good on both OS's, QA Passed 👍🏽

**Pull request merged**
