### PR TITLE
Fix e2e flakiness / errors

### PR DESCRIPTION
**Pull request by BrodyHughes**
CI IS BORKED
- Fixed experimental flag that was causing NFTs to not display properly
- Rearranges CI script so we can see test logs more clearly for debugging
- Added @walmat 's unit test fix here as well (This fixes the lint failure as seen in this action run: https://github.com/rainbow-me/rainbow/actions/runs/10708629212/job/29694446365)

### CODE REVIEW

**Review by brunobar79 — CHANGES_REQUESTED** [review]
Revert the changes to the project.pbxproj file

**Comment by brunobar79** [comment]
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/brody/fix-ci-e2e/1c410e990dd8439d2400c01501ba2f43caf06098.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/brody/fix-ci-e2e/1c410e990dd8439d2400c01501ba2f43caf06098.ipa) for 1c410e990dd8439d2400c01501ba2f43caf06098

**Comment by brunobar79** [comment]
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/brody/fix-ci-e2e/4570081061508cb2c1e11088e9ce958e8224c601.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/brody/fix-ci-e2e/4570081061508cb2c1e11088e9ce958e8224c601.ipa) for 4570081061508cb2c1e11088e9ce958e8224c601

**Review by brunobar79 — APPROVED** [review]
👏 👏 👏

**Review by walmat — APPROVED** [review]

**Review by ibrahimtaveras00 — APPROVED** [review]
🌮

**Pull request merged**
