### PR TITLE
[RNBW-4059] swaps: fix arbitrum flipping

### PR DESCRIPTION
**Pull request by estebanmino**
Fixes RNBW-4059
Figma link (if any):

## Final checklist

- [ ] Assigned individual reviewers?
- [ ] Added labels? (`team1/team2`, `critical path`, `release`, `dev QA`)
- [ ] Did you test both iOS and Android?
- [ ] If your changes are visual, did you check both the light and dark themes?
- [ ] Added e2e tests? If not, please specify why
- [ ] If you added new critical path files, did you update the CODEOWNERS file?
- [ ] If no `dev QA` label, did you add the PR to the QA Queue?

### CODE REVIEW

**Review by derHowie — APPROVED** [review]
dev QA passed

**Review by skylarbarrera — APPROVED** [review]
looking good on my end

**Comment by estebanmino** [comment]
PoW https://www.loom.com/share/015680c1a3824b448238f0243b7e26b8

**Review by derHowie — APPROVED** [review]
dev qa pow post rebase: https://recordit.co/ommra0ruZ1
Screen Shot 2022-07-26 at 2 15 54 PM

**Pull request merged**
