### PR TITLE
Fix not visible checkbox in list edit mode

### PR DESCRIPTION
**Pull request by osdnk**
1. Before: 
I noticed that when previously when no coin was visible, the checkbox was not visible.

https://streamable.com/sygwt1

2. After those changes it works as expected:

https://streamable.com/pp5a3f

### CODE REVIEW

**Review by skylarbarrera — APPROVED** [review]
Want another opinion on disabled imgix in dev but solves the issue 👌

**Comment by brunobar79** [comment]
Since the imgix fix was added in #1589, the imgix part of this pr can be reverted, right?

**Comment by osdnk** [comment]
It's just linting

**Comment by brunobar79** [comment]
> It's just linting

My bad. I saw @skylarbarrera's comment and the file that was changed and assumed that was what happening. All good!

**Comment by skylarbarrera** [comment]
yeah re-read that code after and realized, my bad 😚

**Pull request merged**
