### PR TITLE
Update route swap icons

### PR DESCRIPTION
**Pull request by l2succes**
Fixes TEAM2-146

## What changed (plus any additional context for devs)
- Renamed asset in Xcode to match route name

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels?
- [x] Added e2e tests? if not please specify why
- [x] If you added new files, did you update the CODEOWNERS file?

### CODE REVIEW

**Review by skylarbarrera — CHANGES_REQUESTED** [review]
DM'd on slack with link to updated assets

**Review by estebanmino — COMMENTED** [review]
don't we want to maintain the `Both.png` name? having an asset named `rainbow for round frames.png` feels odd to me

**Comment by l2succes** [comment]
Fair enough, I'll update the name

**Review by estebanmino — APPROVED** [review]
🚀

**Pull request merged**
