### PR TITLE
@tchayen/fix swap gesture on expanded asset

### PR DESCRIPTION
**Pull request by tchayen**
Fixes RNBW-3207

## What changed (plus any additional context for devs)

Turns out that there's some interaction that takes a long time to finish and on iOS we are waiting for it do so. I tried to not wait for it and seems that this issue is gone.

But... I am not an expert in interactions/gestures in RN and don't know specifics of how this particular screen evolved so it's possible that I might be breaking something. If yes pls let me know and introduce me to details :pray:.

No e2e tests because I am fixing a bug in existing behavior plus it's about UI interactions so it's nearly impossible to test in e2e.

## PoW (screenshots / screen recordings)

**Before:** here I am constantly trying to dismiss the modal but unable to do so for a couple seconds:

https://user-images.githubusercontent.com/5769281/163201241-aef865ad-76f0-4cde-88f9-ea8f9f904a09.MP4

**After:** here I am able to immediately dismiss the modal:

https://user-images.githubusercontent.com/5769281/163201258-03d6476b-62b2-44b6-9499-ffef4872796d.MP4

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels?
- [x] Added e2e tests? if not please specify why
- [x] If you added new files, did you update the CODEOWNERS file?

### CODE REVIEW

**Review by skylarbarrera — APPROVED** [review]
working 4 me 🙆‍♂️

**Review by osdnk — APPROVED** [review]

**Comment by tchayen** [comment]
@skylarbarrera so we are skipping QA this time and we are good to go, right?

**Comment by skylarbarrera** [comment]
> @skylarbarrera so we are skipping QA this time and we are good to go, right?

yes! for small things like this we want devs to do the testing so Ibrahim can focus on bigger items, this is why fedora was so important

ibrahim will still check every PR before a release is cut

**Pull request merged**
