### PR TITLE
Make extremes points less pointy + bump reanimated

### PR DESCRIPTION
**Pull request by osdnk**
Now it's technically possible that extremes might generate very pointy charts because they make points denser.

e.g.

```
...---x-----x-----x--E--x-----x-----x-----x---...
``` 

I decided to remove surrounding points so now it looks like:

```
...---x-----x--------E--------x-----x-----x---...
``` 

what makes interpolation is these parts even smoother in those areas

### CODE REVIEW

**Comment by christianbaroni** [comment]
path looks great now

but seeing a weird bug with the labels, some of them are shaking back and forth: https://www.dropbox.com/s/mv3cnx8fwwdkfn6/Screen%20Recording%202020-09-06%20at%206.19.06%20PM.mov?dl=0

**Comment by osdnk** [comment]
;----;

**Comment by osdnk** [comment]
@christianbaroni can you take a look?

**Comment by christianbaroni** [comment]
@osdnk shaking still happening

only happens when a label is all the way on the right edge

**Comment by christianbaroni** [comment]
@osdnk fixed the shaking, seeing two other issues:

- [ ] when you start scrubbing, the path's strokeWidth and opacity no longer animate
- [ ] when building to my phone in release mode: occasionally when I tap a coin row to open the expanded state, the app freezes completely. I then can't get past the splash screen, even after force quitting, until I rebuild

**Comment by christianbaroni** [comment]
@osdnk saw the freeze again, this time while switching time periods

**Comment by osdnk** [comment]
gone

**Review by christianbaroni — APPROVED** [review]
💯

**Pull request merged**
