### PR TITLE
android save image

### PR DESCRIPTION
**Pull request by skylarbarrera**
Fixes RNBW-3371

## What changed (plus any additional context for devs)
my initial image handling changes did not properly handle downloading images, this fixes it along with https://github.com/rainbow-me/rainbow/commit/50ce64c47aefdb5560ec2137b6c4ed9110954876

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels?
- [x] Added e2e tests? if not please specify why
- [x] If you added new files, did you update the CODEOWNERS file?

### CODE REVIEW

**Review by jinchung — APPROVED** [review]
🌮

**Review by osdnk — COMMENTED** [review]
Please, add a bit of description. After a year, we will use `git blame` and find this and start wondering what's going on here

**Review by terrysahaidak — APPROVED** [review]
Chnages look good to me, but yeah would be cool to have a little description too

**Pull request merged**
