### PR TITLE
Tophat

### PR DESCRIPTION
**Pull request by brunobar79**
## What changed (plus any additional context for devs)

Splits CI jobs in two parallel.

- build: which generates a ready to install sim and iPhone build for the current comment in release mode.
- tests: which runs linting + unit tests in one action, and e2e in another one (also in parallel)

## Screen recordings / screenshots

Sim: 

https://github.com/user-attachments/assets/170b203a-699f-4e1d-8274-e4aea983ceb5

Device:

https://github.com/user-attachments/assets/e431624e-83b2-40b7-9432-82dcfba44889

## What to test

- Install the latest version of tophat.
- Make sure you have the  iPhone 15 pro simulator with iOS 17.4 installed.
- Make sure you have your phone as a device registered inside xcode (with wifi builds enabled)
- Select your iPhone on tophat and click on the comment of this PR where it says "device". The app should be installed immediately
- Select your Sim on tophat and click on the comment of this PR where it says "simulator". The app should be installed immediately

### CODE REVIEW

**Comment by brunobar79** [comment]
Here's the app file: http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@bruno/publish-artifacts/7c2489791a1ba0481f4d0596bb5bdf30bd892254.app

**Comment by brunobar79** [comment]
Launch the iOS app [here](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@bruno/publish-artifacts/c1d3ccb551e2b05cd34a700979d45e80302eaaa0.zip)

**Comment by brunobar79** [comment]
Launch the iOS app [here](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@bruno/publish-artifacts/039a24f3b9d9340949e1586f191e46eeed9d0a12.app.zip)

**Comment by brunobar79** [comment]
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@bruno/publish-artifacts/45d67a466b883d94d7a01b04c0ce5018982cd555.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/@bruno/publish-artifacts/45d67a466b883d94d7a01b04c0ce5018982cd555.ipa) for 45d67a466b883d94d7a01b04c0ce5018982cd555

**Comment by brunobar79** [comment]
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@bruno/publish-artifacts/c7d6e8d1f9b6e405ba19b47654b590e3ee7b50c3.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/@bruno/publish-artifacts/c7d6e8d1f9b6e405ba19b47654b590e3ee7b50c3.ipa) for c7d6e8d1f9b6e405ba19b47654b590e3ee7b50c3

**Comment by brunobar79** [comment]
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@bruno/publish-artifacts/28297f1950d73be40217206a2e9d30327d64370e.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/@bruno/publish-artifacts/28297f1950d73be40217206a2e9d30327d64370e.ipa) for 28297f1950d73be40217206a2e9d30327d64370e

**Comment by brunobar79** [comment]
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@bruno/publish-artifacts/2a5fb51a219cf0d9cc4197acdee296ca4fcaeb0d.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/@bruno/publish-artifacts/2a5fb51a219cf0d9cc4197acdee296ca4fcaeb0d.ipa) for 2a5fb51a219cf0d9cc4197acdee296ca4fcaeb0d

**Review by jinchung — APPROVED** [review]
🌮

**Review by christianbaroni — APPROVED** [review]

**Pull request merged**
