### PR TITLE
Do not unmount DiscoverSheet's home

### PR DESCRIPTION
**Pull request by osdnk**
I noticed it's rather pointless to unmount Discover's home. With this, the performance seems to be slightly better and the animation looks smoother

### CODE REVIEW

**Comment by osdnk** [comment]
https://streamable.com/jsfeo5

**Comment by skylarbarrera** [comment]
I dont think we want this(see top movers on bottom): http://cloud.skylarbarrera.com/Screen-Shot-2021-01-11-12-38-29.90.png

**Comment by christianbaroni** [comment]
I think we should just do a crossfade between the two views, so simultaneously:

search view goes from opacity 0 → 1
discover home goes from opacity 1 → 0

that should avoid the issue @skylarbarrera is seeing. don't think y position of discover home needs to change

**Comment by christianbaroni** [comment]
+ disable touch events on discover home when search is enabled

**Comment by osdnk** [comment]
closing then

**Pull request closed without merging**
