### PR TITLE
WC send reject full error

### PR DESCRIPTION
**Pull request by estebanmino**
Adding full errors to the response

### CODE REVIEW

**Review by brunobar79 — COMMENTED** [review]
This is good but only adds support for RPC callls of NON signing methods which AFAIK WalletConnect doesn't fwd to the wallet anymore (they are sent to the provider that the dapp provides when initializing)  so it doesn't make a difference.

The real improvement would be to return the real errors every by calling walletConnectSendStatus on `handleSignMessage` and `handleConfirmTransaction`

**Comment by estebanmino** [comment]
@brunobar79 nice suggestion! just made the changes accordingly PoW https://recordit.co/l5kVYkfKBp

**Review by brunobar79 — APPROVED** [review]
This is great 🔥

**Review by skylarbarrera — APPROVED** [review]
🧉

**Review by skylarbarrera — APPROVED** [review]
lgtm

**Pull request merged**
