### PR TITLE
fix: android review send nft

### PR DESCRIPTION
**Pull request by estebanmino**
Fixes RNBW-3878

## PoW (screenshots / screen recordings)

https://user-images.githubusercontent.com/12115171/174892832-ecfc9828-0660-400f-97ad-1f94665e8c8f.mov

## Final checklist

- [ ] Assigned individual reviewers?
- [ ] Added labels?
- [ ] Added e2e tests? if not please specify why
- [ ] If you added new files, did you update the CODEOWNERS file?

### CODE REVIEW

**Review by BrodyHughes — APPROVED** [review]
Fixed the problem!

**Review by skylarbarrera — APPROVED** [review]
😅

**Review by jxom — APPROVED** [review]

**Review by osdnk — APPROVED** [review]

**Pull request merged**
