### PR TITLE
Fix sticky headers

### PR DESCRIPTION
**Pull request by osdnk**
Fixes RNBW-2055
Fixes RNBW-20562

## What changed (plus any additional context for devs)

While expanding the list, the header might get unmounted and I was ignoring this case.
Additionally, I implemented parallel behavior for edit row

## PoW (screenshots / screen recordings)
image

image

## Dev checklist for QA: what to test

Scroll through the list  

## Final checklist
[ ] Assigned individual reviewers?
[ ] Added labels?

### CODE REVIEW

**Comment by markdalgleish** [comment]
I just ran this locally and I'm seeing issues with the edit row. It's rendering _under_ the other rows, and it's not moving off the screen when the "Collectibles" header reaches it.

**Comment by osdnk** [comment]
crap, that's valid. Actually, we should not show other sections while editing 😢

**Comment by osdnk** [comment]
image

**Comment by jinchung** [comment]
Ran locally and confirmed that it is working:
- regular scrolling with small balances closed works as expected
- opening small balances and scrolling works as expected
- opening edit row and then scrolling leaves the edit row sticky and removes other sections

**Review by terrysahaidak — APPROVED** [review]

**Review by jinchung — APPROVED** [review]
🌮

**Pull request merged**
