### PR TITLE
add default edit button

### PR DESCRIPTION
**Pull request by skylarbarrera**
Fixes RNBW-2050

## What changed (plus any additional context for devs)
added an edit button for < 5 asset wallets, removed any xtra handling for coin dividers that isn't needed now

## PoW (screenshots / screen recordings)
https://cloud.skylarbarrera.com/Screen-Recording-2022-01-18-10-51-32.mp4

## Dev checklist for QA: what to test
edit + hiding/pinning tokens should work as expected

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels?

### CODE REVIEW

**Review by jxom — APPROVED** [review]
lgtm!

**Comment by osdnk** [comment]
Do we have a design review for this?

**Review by osdnk — CHANGES_REQUESTED** [review]
I'm not a fan of this tbh,
We should fix the flow in a better way. I think that the location of that button is a bit... ugly? 

Maybe we can allow for a long press on the sum button to open the context with a way to enter the edit mode? 

However, this needs input from @christianbaroni or Jeremy?

**Comment by skylarbarrera** [comment]
@osdnk can you review now

**Review by osdnk — APPROVED** [review]
Looks good

**Pull request merged**
