### PR TITLE
speed up WC requests

### PR DESCRIPTION
**Pull request by estebanmino**
Before / after 

https://user-images.githubusercontent.com/12115171/128407695-1a18c936-5241-4c23-9dc3-f92dc8289e36.mov

Fixes RNBW-1381

### CODE REVIEW

**Review by brunobar79 — APPROVED** [review]
💯

**Comment by skylarbarrera** [comment]
other than the initial connection request i am not getting any transaction/signing requests on multiple dapps

**Review by skylarbarrera — APPROVED** [review]
we need to figure out CI but everything else is 🏎️

**Comment by skylarbarrera** [comment]
@estebanmino  can you remove everything that is not part of the walletconnect.js changes while i look into the further today?

**Comment by estebanmino** [comment]
@skylarbarrera  done! sorry about that

**Pull request merged**
