### PR TITLE
Bump iOS target to iOS 13 and remove version checks

### PR DESCRIPTION
**Pull request by jkadamczyk**
Fixes APP-76
## What changed (plus any additional context for devs)

* Bumped iOS Deployment target from 11 to 13 on all Xcode Targets
* Removed `isNativeStackAvailable` variable and removed its usages or replaced it with `IS_IOS`
* Removed `@available(iOS 13.0)` checks in native iOS code (we always have minimum iOS 13 now so it's not needed) 

## Final checklist

- [x] Assigned individual reviewers?
- [x] Did you test both iOS and Android?
- [x] If your changes are visual, did you check both the light and dark themes?
- [x] Added e2e tests? If not, please specify why
- [x] If you added new critical path files, did you update the CODEOWNERS file?

### CODE REVIEW

**Review by estrattonbailey — APPROVED** [review]

**Review by skylarbarrera — APPROVED** [review]
🖖

**Review by skylarbarrera — APPROVED** [review]
changes look good and straightforward, ran a mild QA on the impacted sections and things are looking good 👌

**Pull request merged**
