### PR TITLE
Upgrade RN to v0.74.3, bump outdated packages

### PR DESCRIPTION
**Pull request by christianbaroni**
Fixes APP-1666

## What changed (plus any additional context for devs)
- Bumps RN to `v0.74.3`
- Upgrades outdated packages
- Bumps minimum iOS version to iOS 15.0
- Removes Crashlytics as its crash tracking is redundant on top of Sentry
- Removes unused Plaid integration

Todo:
- [x] Local iOS builds working
- [x] Local Android builds working
- [x] Fix CI

### CODE REVIEW

**Comment by christianbaroni** [comment]
> **🚨 Potential security issues detected.** Learn more about [Socket for GitHub ↗︎](https://socket.dev?utm_medium=gh)
> 
> To accept the risk, merge this PR and you will not be notified again.
> 
> Alert	Package	Note	Source	CI
> [ Install scripts ](https://socket.dev/npm/package/@lavamoat/preinstall-always-fail/alerts/2.0.0?alert_name=installScripts)	[ npm/@lavamoat/preinstall-always-fail@2.0.0 ](https://socket.dev/npm/package/@lavamoat/preinstall-always-fail/overview/2.0.0)	
> * **Install script:** [preinstall](https://socket.dev/npm/package/@lavamoat/preinstall-always-fail/overview/2.0.0)
> * **Source:** `echo "Don't run npm lifecycle scripts by default! Create a .yarnrc or .npmrc and set enableScripts: false. Then, whitelist them with @lavamoat/allow-scripts" && exit 1`
> 
> * [`package.json`](https://github.com/rainbow-me/rainbow/pull/5739/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519)
> 
> 🚫
> [**View full report↗︎**](https://socket.dev/dashboard/org/rainbow-me/diff/8e5e6050-3a84-4415-b32c-3d6689400546/1944ca5c-6582-4758-a639-badc0bd783e1)
> 
> ### Next steps
>  ** What is an install script? **
>  ** Take a deeper look at the dependency **
>  ** Remove the package **
>  **Mark a package as acceptable risk**

@SocketSecurity ignore npm/@lavamoat/preinstall-always-fail@2.0.0

**Review by walmat — COMMENTED** [review]
Code looks great. Kudos on the Kotlin rewrite 💯

Tested on iOS and haven't noticed any regressions. Will get to Android tomorrow.

**Review by ibrahimtaveras00 — CHANGES_REQUESTED** [review]
This currently works on prod with latest playstore version
https://linear.app/rainbow/issue/APP-1690/upgrade-rn-to-v0742-qa-bug-cant-unpin-pinned-tokens

**Comment by christianbaroni** [comment]
> This currently works on prod with latest playstore version https://linear.app/rainbow/issue/APP-1690/upgrade-rn-to-v0742-qa-bug-cant-unpin-pinned-tokens
> 
> Happening on iOS as well per @BrodyHughes

Just pushed a fix

**Review by ibrahimtaveras00 — APPROVED** [review]
Fixes look good ✅

**Review by jinchung — APPROVED** [review]
🌮

**Pull request merged**
