### PR TITLE
handle no nfts error for v2 OS API

### PR DESCRIPTION
**Pull request by skylarbarrera**
Fixes RNBW-3059 RNBW-3336

## What changed (plus any additional context for devs)
OS gives us an error on the v2 api when the address has no assets on that network, we dont save to redux if there's an error so we need to return an empty array for this case so poaps still get saved

## PoW (screenshots / screen recordings)
https://cloud.skylarbarrera.com/Screen-Shot-2022-05-02-11-09-33.69.png

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels?
- [x] Added e2e tests? if not please specify why
- [x] If you added new files, did you update the CODEOWNERS file?

### CODE REVIEW

**Comment by skylarbarrera** [comment]
> this is just for analytics, correct?

nah this fixes the bug explained in the linear ticket

**Comment by jinchung** [comment]
This seems brittle but we will have as a temp solution for now:
Ideally we should be splitting up POAP and unique token data and then reading from both. Made a ticket here: https://linear.app/rainbow/issue/RNBW-3501/separate-poap-and-unique-token-data-from-each-other

We're also going to be moving to another data provider which should not have this issue.

**Review by jinchung — APPROVED** [review]
🌮

**Pull request merged**
