### PR TITLE
[TEAM2-488] Disable wyre with remote config

### PR DESCRIPTION
**Pull request by derHowie**
## What changed (plus any additional context for devs)
We are displaying an explainer modal to inform users that Wyre is disabled temporarily due to the merge.

## Screen recordings / screenshots
https://recordit.co/47fiaGFqJo
https://recordit.co/J7tRgf0VLl
https://recordit.co/8CpDIq6ace

## What to test
Ensure Wyre works when `config.wyre_enabled` is true, but that the explainer modal appears when `config.wyre_enabled` is false. This should be checked on the add funds interstitials and within the profile masthead.

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels? (`team1/team2`, `critical path`, `release`, `dev QA`)
- [x] Did you test both iOS and Android?
- [x] If your changes are visual, did you check both the light and dark themes?
- [x] Added e2e tests? If not, please specify why
- [x] If you added new critical path files, did you update the CODEOWNERS file?
- [x] If no `dev QA` label, did you add the PR to the QA Queue?

### CODE REVIEW

**Review by estebanmino — APPROVED** [review]
code lgtm and is working on both android and ios

**Review by skylarbarrera — APPROVED** [review]
👌

**Comment by derHowie** [comment]
Screen Shot 2022-09-06 at 5 15 22 PM
Screen Shot 2022-09-06 at 5 15 02 PM
Screen Shot 2022-09-06 at 5 14 43 PM
t.com/14877580/188739970-6869a236-d239-45d5-8055-1ea71397b78c.png">

design tweaks POW

**Pull request merged**
