### PR TITLE
Make discover up to date with develop

### PR DESCRIPTION
**Pull request by brunobar79**
PoW: http://recordit.co/6CiUxkhAON

And fixed a bunch of bugs related to asset data & lists.

Fixes RNBW-507
Fixes RNBW-994
Fixes RNBW-971
Fixes RNBW-989
FIxes RNBW-970

### CODE REVIEW

**Review by skylarbarrera — APPROVED** [review]
👌 , will look into e2e

**Review by osdnk — APPROVED** [review]
I'm unable to review this (+7,944 −6,707). Is there a chance to extract changes from catching up with develop?

**Comment by brunobar79** [comment]
Unfortunately no because my changes build on top of latest develop, but
It’s not that much and can be reviewed correctly once it’s merged in the
discover branch

**Comment by brunobar79** [comment]
@osdnk actually you can take a look at individual commits under my name starting after "fix lists data"

**Comment by osdnk** [comment]
So let's go with it. Discover search branch has also broken E2E and it's not worth waiting with merging to feature branch if it will speed up our workflow

**Pull request merged**
