### PR TITLE
Polish up exchange, withdraw, deposit and contact screen

### PR DESCRIPTION
**Pull request by osdnk**
https://streamable.com/ws4hpn

Fixed:
- [x] touchables
- [x] status bar
- [x] keyboard
- [x] Animations
- [x] Minor glitches  
- [x] Gas
- [x] Fix padding-top in ChartExpandedState (not related)

### CODE REVIEW

**Comment by skylarbarrera** [comment]
this is great, android swap is functional! iOS has a pretty breaking issue when opening swap: https://cloud.skylarbarrera.com/Screen-Recording-2020-10-19-18-53-23.mp4

**Comment by osdnk** [comment]
@skylarbarrera take a look! :)

**Comment by skylarbarrera** [comment]
@osdnk Clicking Choose a Token for input/output on android crashes, probably has to do with search input changes!

**Comment by osdnk** [comment]
On Android?

**Comment by skylarbarrera** [comment]
Yes sorry for not clarifying, building iOS right now

**Comment by osdnk** [comment]
Okies, maybe just worked on my phone

**Review by skylarbarrera — APPROVED** [review]
fav android PR yet, no regressions on iOS! 1 minor thing, # + Gwei font on Android Gas selector is off, otherwise 🔥

**Comment by osdnk** [comment]
@skylarbarrera the font is not off. It's just not bolded and it's expected. w/o this it's breaking on Android

**Pull request merged**
