### PR TITLE
disable redundant expanded state haptics

### PR DESCRIPTION
**Pull request by skylarbarrera**
fixes RNBW-2837

## What changed (plus any additional context for devs)
removed haptics for elements that dont have actions

## Dev checklist for QA: what to test
haptics should be disabled for elements shown in linear ticket, will need to build to device

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels?

### CODE REVIEW

**Review by tchayen — APPROVED** [review]
Works 👌

**Review by osdnk — APPROVED** [review]

**Review by osdnk — CHANGES_REQUESTED** [review]
Actually, I think we need to understand what is happening here: 
1. The prop you're changing is applied here: `src/components/token-info/TokenInfoItem.js:90`. 
2. However, `onPress` should be `undefined` and this should be sufficient to disable `haptic` feedback because the condition is:
```
enableHapticFeedback={onPress && enableHapticFeedback}
```
3. My guess is that `onPress` is `undefined` so `onPress && enableHapticFeedback` is evaluated to `undefined` as well and this causes the intended logic here doesn't work. The desired state is that every `TokenInfoIten` w/o `onPress` should not have haptic feedback (of course, it doesn't make sense to have this feedback with no action specified). Disabling this feedback specifically is pointless.
4.  Probably this will be enough to change
``` enableHapticFeedback={onPress && enableHapticFeedback}```
to: 
``` enableHapticFeedback={!!onPress && enableHapticFeedback}```
in `src/components/token-info/TokenInfoItem.js:90`.

**Comment by skylarbarrera** [comment]
good 2 go

**Review by osdnk — APPROVED** [review]

**Comment by osdnk** [comment]
Actually, i don't know why i added 'needs qa'. I think it's good

**Pull request merged**
