### PR TITLE
Polish chart interactions

### PR DESCRIPTION
**Pull request by christianbaroni**
- add haptic feedback
- simplify gesture handling
- improve scrubbing transitions
- improve scrubber

### CODE REVIEW

**Comment by osdnk** [comment]
hm, the reason I used PanGH instead of only LPGH is that I want to make it not active for a while to allow dismissing modal

**Comment by christianbaroni** [comment]
> hm, the reason I used PanGH instead of only LPGH is that I want to make it not active for a while to allow dismissing modal

if you test on a real device it works pretty well with the long press, and avoids the haptic feedback when dismissing. was able to get decent control with maxDist/minDurationMs

there were a couple bugs with the TapGH/PanGH combo, where you could activate the pan gesture without activating the tap gesture, or the tap gesture without the pan gesture

would be better if we had control over horizontal/vertical gestures separately, need something like a LongPressPanGH--if you think it can be better with PanGH feel free to change

**Comment by osdnk** [comment]
Let's merge for no cause it's WIP anyway

**Comment by osdnk** [comment]
and it's worth to have the one source of truth

**Pull request merged**
