### PR TITLE
Profiles: Fix SVG NFT avatars & filter out non-image NFTs

### PR DESCRIPTION
**Pull request by jxom**
Fixes RNBW-3735, RNBW-3774

## What changed (plus any additional context for devs)

This PR addresses the following issues in the "Select NFT" sheet:
- selecting SVG NFTs would result in a blank avatar ([context](https://rainbowhaus.slack.com/?redir=%2Farchives%2FC02TSCZT94Z%2Fp1653902602647059))
- we now filter out audio/video NFTs, as well as POAPs & ENS NFTs

## PoW (screenshots / screen recordings)

https://user-images.githubusercontent.com/7336481/171555719-07702dc1-e984-42e5-9ced-7cab7902c493.MP4

### CODE REVIEW

**Review by pugson — APPROVED** [review]
🐐👑

thing that irks me is the `grouped2` variable name but that's only a nit

**Review by estebanmino — COMMENTED** [review]
looking goooood

what do you think of hiding the showcase section as well? I put ENS NFTs in my showcase and I can use them as avatar

**Comment by benisgold** [comment]
My cover photo NFT is pixelated on this branch but not on the checkpoint branch

Simulator Screen Shot - iPhone 13 Pro - 2022-06-02 at 14 29 26
5272675/171741701-76769324-67cf-44d4-98bd-fe596d5e12fc.png)

**Comment by jxom** [comment]
Fixed!

**Pull request merged**
