### PR TITLE
Update text input props

### PR DESCRIPTION
**Pull request by brunobar79**
Fixes RNBW-####

## What changed (plus any additional context for devs)
Added some missing props to the text input.

## PoW (screenshots / screen recordings)
e2e should be green

## Dev checklist for QA: what to test
importing a wallet via seed, pkey and ens name.

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels?
- [x] Added e2e tests? if not please specify why
- [ ] If you added new files, did you update the CODEOWNERS file?

### CODE REVIEW

**Review by estebanmino — APPROVED** [review]
imported pkey, seedphrase and ens name, looking good 🚀

**Review by jinchung — APPROVED** [review]
🌮

**Comment by tchayen** [comment]
Linter failing on order of keys 🙈

**Pull request merged**
