### PR TITLE
turn on hermes

### PR DESCRIPTION
**Pull request by osdnk**

### CODE REVIEW

**Review by skylarbarrera — APPROVED** [review]
would love to see CI pass 1 more time but LGTM 🚀 🚀

**Review by brunobar79 — APPROVED** [review]
🚀🚀🚀

**Comment by natioskar** [comment]
Hey guys, I'm following your repo a bit and also using the app 👯 
I'm just wondering why the diction to remove codepush from the app?

**Comment by osdnk** [comment]
Due to legal reasons (+ tbh, we don't use it too often)

**Pull request merged**
