### PR TITLE
Disable short form and main pager's swiping if search is enabled

### PR DESCRIPTION
**Pull request by osdnk**
Partially https://linear.app/rainbow/issue/RNBW-972/improve-search-mode-interactions

### CODE REVIEW

**Comment by skylarbarrera** [comment]
This works great 👌, I think we should add the swipe down on header action to close search pre merge

**Comment by osdnk** [comment]
oh yes, excellent catch!

**Comment by skylarbarrera** [comment]
Still not able to swipe to close sheet on search, I think this is expected but if not lmk and ill approve

**Comment by osdnk** [comment]
yeah it's not something we wanna have

**Comment by osdnk** [comment]
as I discussed with Christian. If it's the case, I can just change it later cause I made an effort to make it exactly like it is now xD

**Review by skylarbarrera — APPROVED** [review]
🍳

**Pull request merged**
