### PR TITLE
Profiles: Fix "Selling" NFTs alignment

### PR DESCRIPTION
**Pull request by jxom**
Fixes TEAM2-431

Figma: https://www.figma.com/file/O2iH8h2H00ycicwUHIfBah/profiles-spec?node-id=351%3A7681

## What changed (plus any additional context for devs)

- Fixing alignment of NFTs under the "Selling" row.
- Added the proper emoji for "Selling" as per the designs.

## Screen recordings / screenshots

Screen Shot 2022-08-17 at 11 27 59 am

### CODE REVIEW

**Review by pugson — APPROVED** [review]
🌈👏

**Review by skylarbarrera — APPROVED** [review]
🤝

**Review by estebanmino — APPROVED** [review]
🚀  https://www.loom.com/share/8601a4f771a242e198f3a2f135fb66d5

**Pull request merged**
