### PR TITLE
[RNBW-2086] Fix wallet name not updating

### PR DESCRIPTION
**Pull request by jxom**
Fixes RNBW-2086

## What changed (plus any additional context for devs)

It seems that the in-place mutating of the selected wallet addresses was playing up with the memoization (`useMemo` deps) in `useAccountProfile.js`.

I have converted the in-place update selected wallet addresses mutation to one which is immutable, causing the comparison in the `useAccountProfile` hook to work correctly.

## PoW (screenshots / screen recordings)

https://www.loom.com/share/5eea3e5eed3f4f6a9cafc78e6118bfa3

## Dev checklist for QA: what to test

1. Edit wallet name in the wallet list
2. Check if the updated wallet name has propagated to the profile page header & asset list header.

## Final checklist
[x] Assigned individual reviewers?
[x] Added labels?

### CODE REVIEW

**Review by skylarbarrera — APPROVED** [review]
nice catch 👌

**Review by jinchung — APPROVED** [review]
🌮

**Comment by jinchung** [comment]
When I kill the app and come back, the profile and wallet screen are updated, but the wallet list still has the old name for some reason!
Example: https://recordit.co/DJmCKmCHnV

**Review by jinchung — CHANGES_REQUESTED** [review]
When I kill the app and come back, the profile and wallet screen are updated, but the wallet list still has the old name! The recording below is after I had already tested this flow without recording, so the names are already out of sync to begin with, and still are out of sync after my actions in the recording.
Example: https://recordit.co/DJmCKmCHnV

**Comment by jxom** [comment]
@jinchung – try again now... 
Seems like due to the async behaviour of `asyncSome`, it was causing weird race conditions in the `walletsUpdate` action. Not sure if we even need `asyncSome`, so I ended up refactoring the behaviour to be more sync, and hopefully also read a bit better.

**Review by jinchung — CHANGES_REQUESTED** [review]
Just did another test:
1. Confirming the change persists after killing the app and returning
2. Did a separate test where I edit the name of the wallet, see it update in the right places, then (without killing it), I update it again to another name - the ProfileScreen / WalletScreen do not update automatically at that point. When I move to the WalletScreen and back to the ProfileScreen, the ProfileScreen will then update. The WalletScreen never updates with the new name.

**Comment by jinchung** [comment]
> @jinchung – try again now... Seems like due to the async behaviour of `asyncSome`, it was causing weird race conditions in the `walletsUpdate` action. Not sure if we even need `asyncSome`, so I ended up refactoring the behaviour to be sync, and hopefully also read a bit better.

this is a very nice code improvement! thank you!

**Comment by jinchung** [comment]
> @jinchung – try again now... Seems like due to the async behaviour of `asyncSome`, it was causing weird race conditions in the `walletsUpdate` action. Not sure if we even need `asyncSome`, so I ended up refactoring the behaviour to be sync, and hopefully also read a bit better.

this is a very nice code improvement! thank you!

**Review by jinchung — APPROVED** [review]
🍔 🍟

**Comment by jinchung** [comment]
I confirmed a series of actions - all looking good!
Changed names multiple times on selected wallet as well as other non-selected wallets.
Confirmed that choosing the non-selected wallet afterwards behaves correctly.
Tested it on read only wallets and imported wallets.
Tested killing the app after multiple changes on multiple wallets - all working correctly.
Tested it on .eth named wallets.

**Pull request merged**
