### PR TITLE
fix: GasSpeedLabelPager update deps to get correct accent color

### PR DESCRIPTION
**Pull request by estebanmino**
Fixes RNBW-####

## What changed (plus any additional context for devs)

gas section accent color wasn't changing according to output amount

## PoW (screenshots / screen recordings)

before

https://user-images.githubusercontent.com/12115171/176961581-aef5ed78-d53c-451a-ae7c-6ca054bbdbf8.mp4

after

https://user-images.githubusercontent.com/12115171/176961503-e7311801-4237-4719-9676-100cdb37904c.mp4

## Final checklist

- [x] Assigned individual reviewers?
- [ ] Added labels?
- [ ] Added e2e tests? if not please specify why
- [ ] If you added new files, did you update the CODEOWNERS file?

### CODE REVIEW

**Comment by estebanmino** [comment]
i think this update to magicMemo could have caused this https://github.com/rainbow-me/rainbow/pull/3463

**Review by skylarbarrera — APPROVED** [review]
🙏

**Review by osdnk — APPROVED** [review]

**Comment by estebanmino** [comment]
adding `dev QA`, very small and specific fix

**Comment by estebanmino** [comment]
POW android & ios https://www.loom.com/share/a96672e8cfd3463a91d841c10618bbb8

**Pull request merged**
