### PR TITLE
Fix slow image loading

### PR DESCRIPTION
**Pull request by terrysahaidak**
Fixes RNBW-4275
Figma link (if any):

## What changed (plus any additional context for devs)

I was investigating slow image loading on Android with caching enabled #3699. To get a better picture of what's happening, when we download images and what kind - I set up a proxy on Android. 

This showed me that on app load, we actually fetch lots of images. These images - are NFTs. We run preload logic in the selector that builds our wallet screen's list. 

Disabling these preloads actually fixed the bug.
But also, since I was able to reproduce this bug in production as well I realized that caching only makes it more consistent.
When we load some huge wallet, we download hundreds of images of 200x200 size (second parameter of `.preload`).
But when I tried to log images that are 200x200 - there were none. We don't use this number at all for displaying our images. So when we need to display any image - we wait for all the preloads and start again with the new size.

So since this preloading of NFTs didn't actually do anything but wasted lots of traffic, I decided to remove it where we don't really use it, it was left from the old times.

Another reason why this is not needed - we cache all the images with the fast image. So when we render these - we load them and cache, next time the user sees them - they will be loaded from the cache, no need to `.preload` them just in case.

## What to test

- All the images should load as it was
- There should be no worse delay with loading than it is in production application

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels? (`team1/team2`, `critical path`, `release`, `dev QA`)
- [x] Did you test both iOS and Android?
- [ ] If your changes are visual, did you check both the light and dark themes?
- [ ] Added e2e tests? If not, please specify why
- [ ] If you added new critical path files, did you update the CODEOWNERS file?
- [x] If no `dev QA` label, did you add the PR to the QA Queue?

### CODE REVIEW

**Review by skylarbarrera — APPROVED** [review]
💆

**Review by perunt — APPROVED** [review]
I tested it on android, and images load faster

**Review by tchayen — APPROVED** [review]
Wow, this is amazing. I am seeing a huge speed up. Great job!

**Review by brunobar79 — APPROVED** [review]
🚀 🚀 🚀

**Comment by skylarbarrera** [comment]
:shipit:

**Review by ibrahimtaveras00 — APPROVED** [review]
Way faster than the initial reported issue, especially with larger wallets (i.e. dom.eth), QA Passed 👍🏽

**Pull request merged**
