### PR TITLE
rc-v1.6.14

### PR DESCRIPTION
**Pull request by jinchung**
* Version bump
* Audit deps (and moment package version upgrade)
* Opensea WC fix
* Fix swap details row crash

For testing the swap details row crash:
It happens when you go to swap pick two ERC-20 tokens and go to view details

For testing the Opensea WC fix:
https://linear.app/rainbow/issue/RNBW-3963/walletconnect-personal-sign-and-eth-sign-false-expiry-on-custom-id

### CODE REVIEW

**Review by osdnk — APPROVED** [review]
Looks good although I share the opinion that we should merge only what's crucial for fixing the regression and ignore the rest (eg audit bump)

**Comment by jinchung** [comment]
> Looks good although I share the opinion that we should merge only what's crucial for fixing the regression and ignore the rest (eg audit bump)

We also need to do a release for the opensea fix by today.

**Review by BrodyHughes — APPROVED** [review]
Critical path + specific 2 bug fixes look good on iOS (although we can't test the OpenSea issue on their develop, only their prod). @ibrahimtaveras00 is looking at Android now.

**Review by ibrahimtaveras00 — APPROVED** [review]
👍🏽

**Pull request merged**
