### PR TITLE
Browser upgrades follow-up

### PR DESCRIPTION
**Pull request by christianbaroni**
## What changed (plus any additional context for devs)
- Now enabling/disabling WebView JS handlers when navigating to or away from the browser tab
- Patches Reanimated to cache all worklets
  - This avoids repeated serialization of worklets, which based on thoroughly testing the app, can be safely cached — it noticeably smooths out gesture-driven interactions and should speed up anything that involves frequently/repeatedly called worklets (this change is being considered in Reanimated)
- [Android] Removes a duplicate context menu that would show when tapping the edge of the tab button

### CODE REVIEW

**Review by brunobar79 — COMMENTED** [review]
Code LGTM! Will test in a bit a report back

**Comment by brunobar79** [comment]
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@christian/browser-upgrades-follow-ups/45533b2b029080394a8831a931f811fff24c354f.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/@christian/browser-upgrades-follow-ups/45533b2b029080394a8831a931f811fff24c354f.ipa) for 45533b2b029080394a8831a931f811fff24c354f

**Review by brunobar79 — APPROVED** [review]
Tested on iOS and it works correctly

**Comment by brunobar79** [comment]
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@christian/browser-upgrades-follow-ups/c604402bb780b71a3c6f5d51194e49ba141c070e.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/@christian/browser-upgrades-follow-ups/c604402bb780b71a3c6f5d51194e49ba141c070e.ipa) for c604402bb780b71a3c6f5d51194e49ba141c070e

**Review by derHowie — APPROVED** [review]

**Pull request merged**
