### PR TITLE
MainnetAssetDiscovery though the address websocket instead of a Covalent call

### PR DESCRIPTION
**Pull request by osdnk**
Fixes RNBW-3320

We have a new endpoint introduced by RNBW-3368. This is wrapping what we were currently doing with covalent and offers us overriding names/symbols for free. 
I tried to make those changes very not severe. Please review with `no whitespace` (https://github.com/rainbow-me/rainbow/pull/3416/files?w=1)

## What changed (plus any additional context for devs)
I added a new logic for the new namespace within the `address` socket. Previously, this was async logic waiting for a response from a server. Now, I made a FIFO queue with callbacks and pick them up while receiving a response. 

for other chains, we fallback to the old logic 

## PoW (screenshots / screen recordings)
N/A
no visual changes 

## Dev checklist for QA: what to test

Try to send a new coin and observe how fast it gets picked up.
I think this is important also to have it reviewed by engineers with `console.log`s on previous `covalentMainnetAssets` and new `covalentMainnetAssets`.

old: https://gist.github.com/osdnk/65901ae2fa5b806df5ba53157a55c92f
new: https://gist.github.com/osdnk/b20e5ecb09abf92db18eec075f94a926

It's OK for our cases, cause we care only about discovering assets and we fetch prices on chain

### CODE REVIEW

**Comment by skylarbarrera** [comment]
adding a note to double check coin names, I saw USDC was coming in as USD Coin

**Review by brunobar79 — APPROVED** [review]

**Review by welps — APPROVED** [review]

**Comment by jinchung** [comment]
@osdnk can u rebase codeowners

**Review by BrodyHughes — APPROVED** [review]
Looks good!

**Pull request merged**
