### PR TITLE
fix the missing verified tokens in swap search

### PR DESCRIPTION
**Pull request by mikedemarais**

### CODE REVIEW

**Review by brunobar79 — APPROVED** [review]
LGTM but probably @jinchung  is the best person to review it

**Comment by skylarbarrera** [comment]
Seems to work but when comparing to the latest testflight we're missing some pretty big "verified coins" in the initial list(pre search) imo.

Coins I think that should be on that list that were previously: Aave, CRV, DPI, Index, Yearn 

Another thing that we may want to fix moving forward is showing the main token on top of derivatives 
Example Yearn:

Before this PR: http://cloud.skylarbarrera.com/IMG_0005.jpeg
After this PR: http://cloud.skylarbarrera.com/Screen-Shot-2021-01-05-23-44-21.91.png

**Review by skylarbarrera — APPROVED** [review]
👍

**Comment by christianbaroni** [comment]
@jinchung is going to look into the sorting issues, let's hold off merging this for now

I'm thinking we need to either de-emphasize some of these verified tokens (maybe ones without curated flag), or cut down on the number of tokens we're marking verified

**Comment by jinchung** [comment]
Going to close this for now as we will be doing different changes in: https://github.com/rainbow-me/rainbow/pull/1562

**Pull request closed without merging**
