### PR TITLE
fix: reference redux within `NotificationsHandler`

### PR DESCRIPTION
**Pull request by estrattonbailey**
## What changed (plus any additional context for devs)
Bit of a nit-picky thing here, but we don't really need to wrap the whole app in this component. Two main reasons:
- once we refactor state, this _could_ have an impact on render performance i.e. more nesting, more state subscriptions, more renders
- I'd like to eventually remove our usage of `connect()` in `App.js`, and this would mean making this PR at that point

Super small, so figured I'd just push it up and see what you think :) 

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels? (`team1/team2`, `critical path`, `release`, `dev QA`)
- [x] Did you test both iOS and Android?
- [x] If your changes are visual, did you check both the light and dark themes?
- [x] Added e2e tests? If not, please specify why
- [x] If you added new critical path files, did you update the CODEOWNERS file?
- [x] If no `dev QA` label, did you add the PR to the QA Queue?

### CODE REVIEW

**Review by osdnk — COMMENTED** [review]
Hard for me to empathise. I don't even understand why this is a component and not just a helper called while initialization

**Comment by estrattonbailey** [comment]
@osdnk it's accessing hooks. Maybe eventually we can refactor, but for now this is the right path forward.

**Review by osdnk — COMMENTED** [review]
Yea, that's why I feel it might be just a hook. For me it is moving from one weird pattern to another that is slightly less weird,

**Review by osdnk — APPROVED** [review]
but i don't oppose

**Comment by estrattonbailey** [comment]
@osdnk oh I see, I misunderstood you. I think we can work towards that, sure!

**Review by skylarbarrera — APPROVED** [review]
🖖

**Review by jkadamczyk — APPROVED** [review]

**Comment by jkadamczyk** [comment]
Closing it after consulting with @estrattonbailey

**Pull request closed without merging**
