### PR TITLE
Restore stack navigator instead of native stack

### PR DESCRIPTION
**Pull request by osdnk**

### CODE REVIEW

**Comment by skylarbarrera** [comment]
@osdnk I merged develop & fixed e2e, added to this branch since develop is working fine! 

Looks like there's an issue now, lmk when it's fixed and ill take another look 🚀 : https://cloud.skylarbarrera.com/Screen-Shot-2020-11-18-at-2.56.21-PM.png

**Comment by brunobar79** [comment]
@osdnk  Can we make the charts sheet to have approx. this height ?

Screen Shot 2020-11-18 at 5 10 27 PM (2)

**Comment by brunobar79** [comment]
> @osdnk I merged develop & fixed e2e, added to this branch since develop is working fine!
> 
> Looks like there's an issue now, lmk when it's fixed and ill take another look 🚀 : https://cloud.skylarbarrera.com/Screen-Shot-2020-11-18-at-2.56.21-PM.png

@skylarbarrera  You should remove the line `Routes.android.js:228` to fix that issue

**Comment by skylarbarrera** [comment]
@osdnk fixed sorry 😘  , settings needs some love: https://cloud.skylarbarrera.com/Screenshot_20201118-162209_Rainbow.jpg

also you may want to address this in this PR but your call: https://linear.app/rainbow/issue/RAI-946/savings-and-pools-sheets-max-height

**Review by brunobar79 — APPROVED** [review]
Code LGTM. Can be merged after taking care of the comments

**Comment by brunobar79** [comment]
@osdnk  This is great!

This is what I found:

1) Walletconnect transaction modals are missing the background overlay (should be black)
Screen Shot 2020-11-20 at 1 39 12 AM

Screen Shot 2020-11-20 at 1 38 34 AM

Screen Shot 2020-11-20 at 1 37 47 AM



2) Settings modal has some rounded borders and diff. background color.
Would be much better if it's just plain white

Screen Shot 2020-11-20 at 1 30 24 AM

3) The background overlay of charts expanded state is too light

Screen Shot 2020-11-20 at 1 30 45 AM

4) Unique Tokens Expanded state height should not be 100%. Just have some space at the top to show the overlay like we do on iOS (and you already did with ChartsExpandedState!)

**Comment by skylarbarrera** [comment]
Blocking: 
 - Send Sheet tab is iOS not android, and the overlay is not independent
           - https://cloud.skylarbarrera.com/Screen_Recording_20201120-124506.mp4

Non-Blocking:
- should be full screen, needs a safe area on top(tab is above the camera on Galaxy)
        - https://cloud.skylarbarrera.com/Screenshot_20201120-125236_Rainbow.jpg
- settings modal needs less height IMO
       - https://cloud.skylarbarrera.com/Screenshot_20201120-124702_Rainbow.jpg

**Pull request merged**
