### PR TITLE
Disable animated number on android

### PR DESCRIPTION
**Pull request by brunobar79**
Since the performance of animated number is pretty bad we decided to disable the animation for now.

PoW:  https://recordit.co/EEjcYcrVZK

Fixes RAI-921
Fixes RAI-936

### CODE REVIEW

**Review by skylarbarrera — APPROVED** [review]
💯

**Review by osdnk — APPROVED** [review]
Hope it won't break savings!

**Comment by brunobar79** [comment]
> Hope it won't break savings!

What do you mean?

**Comment by osdnk** [comment]
Will it impact saving's animation on WalletScreen?

**Comment by brunobar79** [comment]
> Will it impact saving's animation on WalletScreen? 

No. You can see on the PoW video that it's working fine

**Comment by osdnk** [comment]
Let's mercz

**Comment by osdnk** [comment]
Mi amigo

**Review by osdnk — APPROVED** [review]

**Comment by osdnk** [comment]
:es:

**Pull request merged**
