### PR TITLE
bump socket.io-parser resolution

### PR DESCRIPTION
**Pull request by estebanmino**
Fixes RNBW-####

Audit was screaming

## Final checklist

- [ ] Assigned individual reviewers?
- [ ] Added labels?

### CODE REVIEW

**Review by brunobar79 — APPROVED** [review]
Thank uuuu

**Review by osdnk — APPROVED** [review]
This is still breaking?

**Comment by estebanmino** [comment]
@osdnk yeah, looking at https://github.com/rainbow-me/rainbow/pull/2899 @skylarbarrera halp

**Review by osdnk — CHANGES_REQUESTED** [review]
The problem is with this version 
image

**Comment by estebanmino** [comment]
this should do it then https://github.com/rainbow-me/rainbow/pull/2987

**Pull request closed without merging**
