### PR TITLE
pass hidden & pinned from balance row

### PR DESCRIPTION
**Pull request by skylarbarrera**
Fixes RNBW-2198

## What changed (plus any additional context for devs)
RLV changes added isHIdden to every coin row, while we only care if its hidden for the BalanceCoinRow

added removing hidden tokens form swap & send (updated POW)

## PoW (screenshots / screen recordings)
https://cloud.skylarbarrera.com/Screen-Recording-2022-01-11-22-49-32.mp4

## Dev checklist for QA: what to test
hidden tokens in search or lists should be normal, should not be in send or swap

## Final checklist
[x] Assigned individual reviewers?
[x] Added labels?

### CODE REVIEW

**Review by jinchung — APPROVED** [review]
🌮

**Comment by jinchung** [comment]
> Hey, I think I moved this down for the performance reason. Can you indeed use a prop`ignorePinning`?

Are you referring to the passing along of `isHidden` and `isPinned` to the `CoinRow` from `BalanceCoinRow`? Could you describe the path for how this would be less performant? `BalanceCoinRow` already does a memo across the array to be able to get `isHidden` and `isPinned` for the `BalanceCoinRowCoinCheckButton`. I would say we're saving ourselves an unnecessary `isHidden / isPinned` calculation at the `CoinRow` level.

**Review by osdnk — APPROVED** [review]

**Review by jinchung — APPROVED** [review]
Tested:
1. On rainbowwallet.eth
2. Hid Unisocks and confirmed hidden in wallet screen
3. Opened Swap, selected Input currency, confirmed hidden when scrolling down the list
3b. Tried searching for it in Input currency, did not find it
4. Opened Swap, selected Output currency, confirmed that it is in the list and results when searched
5. Opened Send and confirmed I could not find it in the list

**Comment by jinchung** [comment]
Good to merge once https://github.com/rainbow-me/rainbow/pull/2817 is merged and this is rebased with tests passing

**Pull request merged**
