### PR TITLE
Fix jumping profile header

### PR DESCRIPTION
**Pull request by osdnk**
Fixes RNBW-2385

## What changed (plus any additional context for devs)

I made hacks to make it work! Please, read the comment inside the codebase, this should be descriptive. I had to modify the library to keep track of one timeout's id. 

## PoW (screenshots / screen recordings)

https://streamable.com/c1we7k

## Dev checklist for QA: what to test

Observe the video in linear and try to jump back and forth between different wallets (I don't think that the watch if this is i watch-only mode matters)

### CODE REVIEW

**Comment by skylarbarrera** [comment]
jw were you able to get a consistent repro on this?

**Comment by tchayen** [comment]
I have trouble reproducing it. I understand that I should scroll a wallet and then switch to displaying another one and headers should be in wrong places?

**Comment by osdnk** [comment]
You need to slightly scroll down and change wallet to another

**Review by terrysahaidak — APPROVED** [review]

**Review by tchayen — APPROVED** [review]
Reproduced bug and verified the fix.

**Review by skylarbarrera — APPROVED** [review]
lgtm post CI

**Pull request merged**
