### PR TITLE
Profiles: reorder records and add coins to profile

### PR DESCRIPTION
**Pull request by estebanmino**
Fixes RNBW-3414

## Final checklist

- [ ] Assigned individual reviewers?
- [ ] Added labels?
- [ ] Added e2e tests? if not please specify why
- [ ] If you added new files, did you update the CODEOWNERS file?

### CODE REVIEW

**Comment by jxom** [comment]
Shouldn't we be displaying all coin addresses?

**Comment by estebanmino** [comment]
you mean including ETH? we don't have more coins and ETH is same than ens in my opinion

**Comment by jxom** [comment]
I mean shouldn't we be displaying all coin addresses on a profile? There can be infinitely many of them.
If someone had: BTC, AVAX and XRP addresses on their profile or something.

**Comment by benisgold** [comment]
maybe we could just show all rainbow verified/curated coins?

**Comment by estebanmino** [comment]
ah let's go with the ones we support when creating a profile I'd say, if we want to show any coin it would be the same than showing all random records, which we don't do either. We can revisit later when / if we add custom stuff in profile

**Review by jxom — APPROVED** [review]
all good with me!

**Pull request merged**
