### PR TITLE
Disable coin icons storage on Android

### PR DESCRIPTION
**Pull request by osdnk**
## What changed (plus any additional context for devs)

Grouped imports to `react-coin-storage`, then moved them to one file that is not accessible on android.

I copied the code of the library to the app. This is worth clean-up soon. I needed this because on android I want some of the functionalities of the lib, w/o importing the storage.

I check this in FS, and the bundle size is >10% smaller.

## Dev checklist for QA: what to test

Run android app

### CODE REVIEW

**Comment by skylarbarrera** [comment]
quick glance, ENS & SHIB should have icons from the fallback logic

**Comment by osdnk** [comment]
@skylarbarrera this screenshot is invalid sorry, I can make it better tomorrow.

**Comment by osdnk** [comment]
@skylarbarrera

**Comment by osdnk** [comment]
image
@skylarbarrera

**Review by brunobar79 — CHANGES_REQUESTED** [review]
Because I saw that you named the the file `src/utils/CoinIcons/CoinIcons.ios.js` instead of `src/utils/CoinIcons/CoinIcons.android.js` I ran: 
- `npx react-native-bundle-visualizer --platform ios --dev false`
- `npx react-native-bundle-visualizer --platform android --dev false`

Both on this branch and develop and these are the results:

```
iOS develop => Bundle is 16.63 MB in size
android develop => Bundle is 16.62 MB in size
android this branch => Bundle is 16.63 MB in size (+++ has increased with 713 bytes since last run)
ios this branch => Bundle is 14.29 MB in size (--- has decreased with 2452673 bytes since last run)
```

which means that while this work,  the empty export file should be the android one, not the iOS one

**Review by skylarbarrera — APPROVED** [review]
post export changes this lgtm although I wish we would just delete the whole thing 😩

**Comment by osdnk** [comment]
@brunobar79 sorrrry 😅 😅 😅 😅

**Comment by osdnk** [comment]
whoever will approve: pls merge if no changes needed

**Pull request merged**
