### PR TITLE
Delay closing sheet until we're done with keychain on android 

### PR DESCRIPTION
**Pull request by osdnk**
Fixes RNBW-3875

looks like the prompt doesn't like the animation at the same time.

why? idk
can this be done better? yes
why did profiles break it?  ¯\_(ツ)_/¯ 

## PoW (screenshots / screen recordings)
https://streamable.com/dp52xm

(screen recording doesn't work)

## Dev checklist for QA: what to test

- touchid on
- create a new wallet
- create another wallet 
- authenticate with a finger

### CODE REVIEW

**Comment by benisgold** [comment]
idk why this got introduced now but seems like this is an existing issue with `InteractionManager.runAfterInteractions`

an alternative (but similar) work around:
https://github.com/facebook/react-native/issues/8624#issuecomment-231040370

**Review by benisgold — APPROVED** [review]

**Comment by BrodyHughes** [comment]
This still isn't working for me. Exact same behavior as develop for me. Here is another screen recording to clarify exactly what is happening for me. 

Uploading screen-20220624-110401.mp4…

**Comment by BrodyHughes** [comment]
https://user-images.githubusercontent.com/41711440/175575056-f369a51c-17cf-4cfd-8126-51291403a88c.mp4

**Review by BrodyHughes — APPROVED** [review]
Great fix!

**Pull request merged**
