### PR TITLE
RIP native transaction list

### PR DESCRIPTION
**Pull request by nicoglennon**
Go full JS on the profile page / transactions page. Fixes RNBW-1396.

### CODE REVIEW

**Comment by nicoglennon** [comment]
Seems ok performance-wise to me on the simulator. I do see this sometimes in the first token row right under the titles: 

Screen Shot 2021-07-21 at 9 15 00 PM

**Comment by skylarbarrera** [comment]
> Seems ok performance-wise to me on the simulator. I do see the token circle getting clipped sometimes in the first token row right under the titles:
> 
> Screen Shot 2021-07-21 at 9 15 00 PM

It seems the bottom padding on the headers is larger than it is on the native list should fix the issue

**Comment by skylarbarrera** [comment]
The only things that sticks out to me that we should address before switching:

Loading another group of transactions is sometimes slow, white spaces at the end of the new section.

Scrolling fast up or down also causes the same issue.



Sticky Headers are a little bit blow to

**Comment by nicoglennon** [comment]
This is currently blocked by performance audit that Alexey is doing -- list moves smoothly after first minute of app being open (right after the JS thread stops maxing out).

**Pull request closed without merging**
