### PR TITLE
Profiles: Profile avatar options

### PR DESCRIPTION
**Pull request by benisgold**
Fixes TEAM2-362
Figma link (if any):

## What changed (plus any additional context for devs)
- all wallets that do not have an ens avatar should be able to have a custom image/emoji avatar

## Screen recordings / screenshots

https://user-images.githubusercontent.com/15272675/182515200-07105d82-986b-48b4-ba2a-ffb51e351029.mp4

## What to test
- make sure various types of wallets (ie. ones with ens, ones without, watched wallets, ones with ens avatars, etc) have appropriate profile avatar functionality 

## Final checklist

- [ ] Assigned individual reviewers?
- [ ] Added labels? (`team1/team2`, `critical path`, `release`, `dev QA`)
- [ ] Did you test both iOS and Android?
- [ ] If your changes are visual, did you check both the light and dark themes?
- [ ] Added e2e tests? If not, please specify why
- [ ] If you added new critical path files, did you update the CODEOWNERS file?
- [ ] If no `dev QA` label, did you add the PR to the QA Queue?

### CODE REVIEW

**Review by estebanmino — CHANGES_REQUESTED** [review]
bug fix is looking good https://www.loom.com/share/01af6b004bfa4a72b155dbff19b2ee28?from_recorder=1&focus_title=1

- i noticed pressing "View Profile" is also opening the ens intro screen

https://user-images.githubusercontent.com/12115171/182691124-ecb6f1dc-223b-4dec-aa89-3f64c3b77bdd.mp4


 
- could you add this e2e? pressing avatar on wallet screen should show you an option to edit and view profile, and also pick picture and emoji

**Comment by jxom** [comment]
Screen Shot 2022-08-04 at 6 37 35 am

I think the destructive button should be the last item?

**Comment by benisgold** [comment]
@jxom hmmm idk if i agree, maybe this is a design question? i feel like it makes sense that it replaces the "Pick an Emoji" option with all other options remaining in the same order

**Comment by pugson** [comment]
@benisgold this is a design pattern set by apple so @jxom is right (2 points)

dropping the HIG alpha for @rainbow-me/design 

> If you need to include potentially destructive items in your context menu — such as Delete or Remove — list them at the end of the menu and identify them as destructive

https://developer.apple.com/design/human-interface-guidelines/components/menus-and-actions/context-menus/

**Comment by benisgold** [comment]
noooooo

**Comment by benisgold** [comment]
+ 1 point per e2e test = +5 points

**Comment by jxom** [comment]
-1 point per failing e2e test

**Review by estebanmino — APPROVED** [review]
i like the tests https://www.loom.com/share/1bc46fae9a474f749640b86c7e4f3353

**Pull request merged**
