### PR TITLE
Hide search on hardware back button/gesture event

### PR DESCRIPTION
**Pull request by terrysahaidak**
Fixes RNBW-2267

## What changed (plus any additional context for devs)

If you're on search the only way to hide it is to press "done" button. But this is now how android users used to do it. There is hardware button/gesture to go back. Currently it navigates the user back to home page but the search is still active which results into not working pager gestures - you can't swipe to the discovery sheet or scanner.

We pass cancelSearch to the search screen component. I used hook "useHardwareBack" which calls a callback on hardware back events. We hide the search screen which results in an expected behavior for the user.

## PoW (screenshots / screen recordings)

https://drive.google.com/file/d/1ITMIsGLJz62YUHRX0AsgDUlb8FY0RL7H/view?usp=drivesdk

## Dev checklist for QA: what to test
- Press on search input or FAB
- Use back button/gesture to go back
- Expect it to hide the search instead of navigating to home
- Main screen pager (swipe navigator) should swipe

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels?

### CODE REVIEW

**Review by osdnk — DISMISSED** [review]
That's cool, I was thinking if we can make this more reusable for other places, but I cannot think of many other usages

**Review by skylarbarrera — APPROVED** [review]
🍳

**Comment by terrysahaidak** [comment]
Just found a very unexpected bug. If you press on any of the assets in the search, it opens the asset sheet, back button/gesture actually hides the search but asset sheet is still visible. This is very weird since the asset sheet is basically a react navigation screen so every time we add another sheet - it adds its handler to the queue of handlers. So that sheet's handler should handle the event and if it returns false - it should run our handler.
Gonna figure out what's wrong.

**Comment by terrysahaidak** [comment]
Apparently, react navigation doesn't have back button handling for each screen but only for the navigation. So when we open that bottom sheet route it won't add any additional handlers to the queue so yeah search handler is firing.
I used useFocusEffect to workaround it - now we handle back button if the Search is in focus (active screen).

**Review by osdnk — APPROVED** [review]
🔥

**Review by skylarbarrera — APPROVED** [review]

**Review by tchayen — APPROVED** [review]

**Pull request merged**
