### PR TITLE
Set custom depth of the scroll view in Exchange modal in RNCM

### PR DESCRIPTION
**Pull request by osdnk**
Fixes TEAM2-216
Figma link (if any):

## What changed (plus any additional context for devs)

In the exchange, modals there are two scrollviews - outer for the horizontal animation (not interactive with a gesture) and inner for the vertical scroll. Obviously, we want ot attach the logic to the inner. 

I added a small trick to let developers specify which scroll view ot use in the order of DFS traversing. In this case, this is the second, not the first one.  

In the preview it looks like this: 

outer: 
Pasted Graphic 1

inner: 

Pasted Graphic 2

So i added an option `relevantScrollViewDepth`. 

## Screen recordings / screenshots
The behavior is expected: https://streamable.com/634wyp

To test changes, please open the Exchange modal and observe interactions. If they are ok, it's ok. You may check also other modals, e.g., switch wallet sheet or setting screen (or small phones), but I don't expect this is serious. I checked it all and it's fine

### CODE REVIEW

**Review by jkadamczyk — APPROVED** [review]
Looks good to me, amazing job!

**Review by tchayen — APPROVED** [review]
Niiiiiice

**Review by brunobar79 — APPROVED** [review]
💯

**Review by estebanmino — CHANGES_REQUESTED** [review]
i'm running into some issues, please don't merge yet

**Comment by skylarbarrera** [comment]
leaving a note to make sure that requested reviewers are from the targeted project so they have the context to review properly

**Comment by osdnk** [comment]
Let's talk to Christian what's expected here

**Review by skylarbarrera — APPROVED** [review]
🔥

**Comment by skylarbarrera** [comment]
merged latest and rerunning e2e

**Review by estebanmino — APPROVED** [review]
thanks @osdnk !! 🚀

**Pull request merged**
