### PR TITLE
round last sale price

### PR DESCRIPTION
**Pull request by benisgold**
Fixes RNBW-2773

## What changed (plus any additional context for devs)
- rounded nft last sale price immediately after getting this data from opensea api. i chose to show a maximum of 5 decimal places, not sure if that is the best choice

## PoW (screenshots / screen recordings)
https://user-images.githubusercontent.com/15272675/159536624-eb3d48a3-12b6-4f49-a9f1-e4810d4aba92.mp4

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels?

### CODE REVIEW

**Comment by benisgold** [comment]
if the last sale price is less than 0.000001, I believe it might round to 0. Should I round all last sale prices below this amount up to 0.000001?

**Review by osdnk — CHANGES_REQUESTED** [review]
Hey, @benisgold!

This is still not correct. 

1. JS has a problem with `0.5` rounding with `toFixed`.
E.g., `(0.135).toFixed(2)` is `"0.13"` See: https://www.quora.com/Why-do-we-round-off-0-5-to-1-and-not-to-0

2. with `toFixed(2)` we _always_  get 2 digits after comma. E.g., `(2).toFixed(2)` is `"2.00"` and obviously we don't need those tailing zeros. 

The solution is `Math.round((value + Number.EPSILON) * 100) / 100`

See: https://stackoverflow.com/questions/11832914/how-to-round-to-at-most-2-decimal-places-if-necessary

**Comment by osdnk** [comment]
And, also, if the value is less than something (I think 5 decimals is redundant. Maybe 3 is fine. Even `0.01 eth` is about 30 dollars and it's rare to have nft of this price (listing is more expensive), but we should do something like `< 0.01 eth`. However, IMO this logic should stay in the component

**Comment by benisgold** [comment]
ok thanks @osdnk i took your advice! lmk how it looks now

**Review by osdnk — APPROVED** [review]

**Review by tchayen — DISMISSED** [review]
I don't mind the `lastSalePrice` formatting, it would make it much more complex so probably not worth it.

But having the calculations with epsilon controlled in one place is IMO important.

**Comment by osdnk** [comment]
I think here we're ok w/ skipping the design review?

**Review by osdnk — APPROVED** [review]

**Review by tchayen — APPROVED** [review]
LGTM

**Pull request merged**
