### PR TITLE
Wallet connect loader in session requests

### PR DESCRIPTION
**Pull request by estebanmino**
Adds a loader on wallet connect session requests

https://recordit.co/wJDLeiCviQ

### CODE REVIEW

**Review by brunobar79 — APPROVED** [review]
💯

**Review by jinchung — APPROVED** [review]
🌮

**Comment by skylarbarrera** [comment]
getting a crash when i try to make a WC connection:
https://cloud.skylarbarrera.com/Screen-Recording-2021-07-30-22-21-11.mp4

**Comment by skylarbarrera** [comment]
crash is fixed, we should add some kind of timeout, currently the bridge is down so the app never gets any metadata and spins indefinitely

**Comment by estebanmino** [comment]
thanks @christianbaroni not sure what i did there 😅

**Comment by estebanmino** [comment]
added analytics in order to track how many seconds users are waiting for the connection to load.

event name: `Received wc connection`

params: 
```
{
  dappName,
  dappUrl,
  waitingTime
}
```

with `waitingTime` in secsonds

**Pull request merged**
