### PR TITLE
Fix content being cut in WC approval sheet

### PR DESCRIPTION
**Pull request by tchayen**
Fixes RNBW-2390
Fixes RNBW-2448

## What changed (plus any additional context for devs)

There was no margin and I assume it didn't look bothering on iOS as it had bottom inset from safe area view.

### Before

photo_2022-02-02 16 03 48
photo_2022-02-02 16 03 45

### After

photo_2022-02-02 16 16 24
photo_2022-02-02 16 16 30

## Dev checklist for QA

Check if the content in the WC approve modal is properly displayed (not cut).

### CODE REVIEW

**Comment by osdnk** [comment]
What happens if there's e.g. 3 lines long text? Or 4?

**Comment by tchayen** [comment]
@osdnk
I realized that this sheet's height is fixed (`const sheetHeight = type === WalletConnectApprovalSheetType.connect ? 408 : 438;`) so for multiple lines the content would be pushed out of the screen.

I checked that removing both height and margin seems to help with this:
photo_2022-02-02 16 34 33
photo_2022-02-02 16 34 35

Do you maybe know if the reason for which fixed height was introduced still applies?

**Comment by osdnk** [comment]
Hm, I was more thinking about the like "Rainbow Dapp Button" e.g.  "Rainbow Dapp Button Rainbow Dapp Button Rainbow Dapp Button" instead. 
But ok, I think this is the same thing. 

The reason? I think this is a "left-over" from a time when we used a react-navigation modal sheet for that?

**Review by osdnk — APPROVED** [review]
Well, I approve of those changes if you double-checked this on both platforms. I cannot imagine this breaking anything more and def we should make similar changes wherever possible

**Comment by tchayen** [comment]
My previous comment was a bit misleading. The last two screenshots were with a change that I haven't posted yet at that time (pushed now).

I just noticed another problem with height – it was used in the loading phase to show empty sheet with a spinner.

So it looks like we either should:

1) keep the height setting and update the value so it won't be cutting content (as otherwise autosizing of elements works, as shown in the screenshots above).

2) remove the height from the final sheet but keep it intact for loading phase – this results in a 'jump',  specifically here the sheet moves ~20 pixels to the top after the spinner. Not terrible but also not perfect UX.

https://user-images.githubusercontent.com/5769281/152182363-30c8b15c-04bc-4813-8b8b-e7b743aff0d6.mp4

3) remove the height from final sheet and change it for loading to, let's say, 100 pixels, so it will clearly be a different height so it won't feel like a small glitch (case of variant 2).

**Comment by christianbaroni** [comment]
does removing the height prevent the sheet from being flicked upwards? that might be why it's there

if so, can we measure how many lines of text there are and change the height accordingly?

**Comment by tchayen** [comment]
@christianbaroni

> does removing the height prevent the sheet from being flicked upwards? that might be why it's there
Pretty much (but opposite). The height was there to have known height for both spinner phase and target phase.

Without height the content is not hidden but there is a flick upwards after spinner whenever there are more lines than there were expected. If the length of the text is not too long there is no flicking.

> can we measure how many lines of text there are and change the height accordingly?

When we display the spinner we don't have any info loaded yet, so we can't predict how many lines there will be.

One possible solution to flicking might be to make the sheet visibly shorter (for example just 100 pixels high instead of ~400) and then animate to the full height once data loads.

**Review by skylarbarrera — APPROVED** [review]
this seems chill, this whole sheet + `transactionConfirmationScreen` needs a refactor

**Review by ibrahimtaveras00 — CHANGES_REQUESTED** [review]
Couple issues I spotted while testing: 

**Issue 1:**

when the wallet name has a long name, we should do an ellipses

Screen Shot 2022-02-09 at 11 20 23 AM

Screen Shot 2022-02-09 at 11 30 41 AM

**Issue 2:**

This seems to only happen on androids with bigger screens (tested on an Google Pixel 5a)

When attempting an approve from uniswap I do not see the gas price nor the gas button & custom gas button in comparison to a smaller device (pixel 2) 

image

Flow seen here = https://recordit.co/faq3IYFpkF

**Issue 3:**

When connecting to polygon network, the MATIC pushes the view down and gets cut off

flow seen here = https://recordit.co/lkhp6nzyzD

Screen Shot 2022-02-09 at 11 37 00 AM

Screen Shot 2022-02-09 at 11 43 37 AM

**Comment by tchayen** [comment]
@ibrahimtaveras00 All of those issues are not directly connected to this problem so I'd rather solve them separately and merge this now.

I have created issue for ellips text: https://linear.app/rainbow/issue/RNBW-2514/wallet-names-need-ellipsis

Is #2 consistent only on this branch? It's a bit hard to believe it's connected as this is entirely different screen, different code that is 100% unaffected by this change. Same for number three and additional issue from comment.

**Comment by ibrahimtaveras00** [comment]
Hmmm I can't check against current develop, seems like the android builds are broken?

**Comment by ibrahimtaveras00** [comment]
ok I was able to build develop, interestingly enough, issue 2 does work on develop

Screen Shot 2022-02-10 at 2 02 08 PM

but is reproducible on this branch = https://recordit.co/bfrKBTShlR

**Comment by tchayen** [comment]
@ibrahimtaveras00 can you pull newest changes and check again? Maybe there was some other change on develop that 'fixed' this problem with disappearing gas and this branch was behind.

**Review by ibrahimtaveras00 — APPROVED** [review]
It all looks good now 👍🏽 

Screen Shot 2022-02-14 at 2 13 47 PM

**Pull request merged**
