### PR TITLE
Enabling flipper for Android & iOS

### PR DESCRIPTION
**Pull request by mwieja0**
Reintroducing Flipper support on Android & iOS

Please play extra attention during the review on how the Debug/Release is handled, here are the details:

Android:
1. Currently flipper is initialized through java reflection, so the library is not required when building a release version. Unfortunately, this solution ships with a few lines of code that do the BuildConfig.DEBUG check.

iOS:
2. Flipper needs to be statically linked, at the same time Firebase has to be a dynamic library. I disabled global dynamic linking and forced it only for Firebase and dependencies. I'd like someone to take a look if this has any implications for production build.
3. Flipper on iOS internally checks if ENV['PRODUCTION'] == 1 and if so disables itself, so I don't think it needs any special treatment on iOS, flipper pods won't be even installed.

### CODE REVIEW

**Comment by mwieja0** [comment]
Did you build a release? I want to double-confirm flipper isn't bundled in a release build and doesn't break release build in any way.

**Comment by dereknelson** [comment]
> Did you build a release? I want to double-confirm flipper isn't bundled in a release build and doesn't break release build in any way.

I added it to my in progress work so when I build I will confirm that.

In the meantime @ibrahimtaveras00 if you have time today would be sick to QA flipper in releases so we can merge it

**Comment by ibrahimtaveras00** [comment]
I attempted a build via Testflight and see that it failed = https://app.bitrise.io/build/ad5e9d68-d666-4fbd-aa0f-ceaad0ee4dd8#15239e82-d0fb-445b-ba6c-d785e5cca666-error 

Screenshot 2023-09-15 at 5 44 52 PM

**Comment by dereknelson** [comment]
> I attempted a build via Testflight and see that it failed = https://app.bitrise.io/build/ad5e9d68-d666-4fbd-aa0f-ceaad0ee4dd8#15239e82-d0fb-445b-ba6c-d785e5cca666-error 
> 
> 
> 
> Screenshot 2023-09-15 at 5 44 52 PM
> 
> 

this happens intermittently, not related to this change

**Comment by mwieja0** [comment]
This one should not be related to Flipper. @ibrahimtaveras00 can you give it another try since it might be a stochastic behavior?

**Review by ibrahimtaveras00 — APPROVED** [review]
Was able to run yarn android:apk fine and bitrise ended up working = https://app.bitrise.io/build/e0e79b9e-71b8-428f-8612-82801af0db7f

**Review by jinchung — APPROVED** [review]
🌮

**Pull request merged**
