### PR TITLE
Improve ‘more details’ tap target area for swaps

### PR DESCRIPTION
**Pull request by pugson**
Fixes TEAM2-414

## What changed (plus any additional context for devs)
- Added invisible padding around the `More details` button in swap review sheet to make it easier to tap with your finger.

## What to test
Going into swap review sheet and tapping on `More details` on Android and iOS.

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels? (`team1/team2`, `critical path`, `release`, `dev QA`)
- [x] Did you test both iOS and Android?
- [x] If your changes are visual, did you check both the light and dark themes?
- [ ] Added e2e tests? If not, please specify why
- [ ] If you added new critical path files, did you update the CODEOWNERS file?
- [ ] If no `dev QA` label, did you add the PR to the QA Queue?

### CODE REVIEW

**Review by estebanmino — COMMENTED** [review]
working nicely! could we add the same for the other rows that the user can press?

**Comment by pugson** [comment]
> working nicely! could we add the same for the other rows that the user can press?

i added it for 'swapping via'. tried doing it for all rows but things get so messed up and uncontrollable that i gave up after a few hours. too many text rendering issues on both platforms 😢

**Review by skylarbarrera — APPROVED** [review]
cool w this for now, we should revisit post design system conversion

**Review by derHowie — APPROVED** [review]
👍 🖌️

**Review by derHowie — APPROVED** [review]
👍

**Pull request merged**
