### PR TITLE
Explain sheet

### PR DESCRIPTION
**Pull request by osdnk**
For now, it's just available on the long-press for back button in Profile Screen in debug mode. 

image

new version: 
image

### CODE REVIEW

**Comment by osdnk** [comment]
image

**Review by skylarbarrera — APPROVED** [review]
lgtm 🙆‍♂️

**Review by jinchung — APPROVED** [review]
🌮 great! would just confirm final text given Christian and Jackson's versions of the explainer!

**Comment by osdnk** [comment]
This version is confirmed by Jackson. May I ask for merging after confirming it's ok?

**Pull request merged**
