### PR TITLE
New expanded LP pools + New expanded asset state

### PR DESCRIPTION
**Pull request by osdnk**
image

### CODE REVIEW

**Comment by skylarbarrera** [comment]
Looks good, only blocker is the expanded state doesnt open on android

**Comment by skylarbarrera** [comment]
ios looks good to go! Some android things:

Cant swipe down on sheet content to close sheet(should be possible if sheet is at the top)


There's this state where the liquidity info and description don't load and then we get the following sheet - see Aragon Expanded State: http://cloud.skylarbarrera.com/Screen-Recording-2021-04-06-15-41-36.mp4

**Comment by osdnk** [comment]
@skylarbarrera 
The first bug will be not fixed. To fix this we need to migrate sheets to Mo's implementation. I can do this later, but for now, I think it's good. 

The second bug is fixed

**Comment by osdnk** [comment]
I feel this PR is ready

**Review by christianbaroni — APPROVED** [review]

**Pull request merged**
