### PR TITLE
Fix scrubbering on the last point of the chart

### PR DESCRIPTION
**Pull request by osdnk**

### CODE REVIEW

**Comment by christianbaroni** [comment]
still seeing the issue with certain charts @osdnk, near the last point it moves off the line

**Comment by osdnk** [comment]
I think it's worth taking a look now, @christianbaroni!

**Comment by osdnk** [comment]
I know it might not be perfect in extremes but at least it will help with edges

**Comment by christianbaroni** [comment]
@osdnk seems now less accurate over most of the chart

in latest develop it stays on the line basically everywhere except the very last point. I think the issue might happen when we override the last point in the chart with the current price, and the current price is different from the last data point

is there a way to fix the last point without affecting scrubbing over the rest of the line?

video: https://www.dropbox.com/s/nngjnvg2uqbif6e/Screen%20Recording%202020-09-10%20at%207.57.02%20PM.mov?dl=0

**Review by christianbaroni — APPROVED** [review]

**Pull request merged**
