### PR TITLE
Remove a thread blocking behavior in `react-native-keychain`

### PR DESCRIPTION
**Pull request by perunt**
Fixes RNBW-4267
Figma link (if any):

## What changed (plus any additional context for devs)
 AFAIK it happens when animation is not finished, and we call the `getInternetCredentials` method from the keychain(we use it for speed up transactions/canceling). It looks like a `react-native-keychain` makes a deadlock when opening auth modal. It happens because `react-native-keychain` doesn't support a kind of `concurrent mode` but just makes a deadlock when we try to call `getInternetCredentials` at the same time as animation is performing.

We decided to create a fork with these new changes, which will be fair for SDK >= 24. In the `index` file into `react-native-keychain` we just decide which keychain version we wanna use - the forked one or the real keychain. So we don't need to change the js code at all
In the future, we'll be able just to drop the forked version, or we can update the fork with required changes from its "main."

forked lib: https://github.com/rainbow-me/react-native-keychain-new
PR, which I use for this fork: https://github.com/oblador/react-native-keychain/pull/547
Here are changes in the fork: https://github.com/oblador/react-native-keychain/compare/master...rainbow-me:react-native-keychain-new:master?expand=1
## What to test
   Test everything related to the keychain, creating a new wallet, creating a backup, restoring a backup, accessing the seed phrase.
   It is important to note that you need to test on two versions of Android, up to version 7 (5-6) and from version 7 (7 - up to date)
   The fix should work fully for versions 7 and above
   For versions 5-6, the fix will work partially, and the error can be reproduced, but much less often

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels? (`team1/team2`, `critical path`, `release`, `dev QA`)
- [x] Did you test both iOS and Android?
- [x] If your changes are visual, did you check both the light and dark themes?
- [ ] Added e2e tests? If not, please specify why
- [ ] If you added new critical path files, did you update the CODEOWNERS file?
- [x] If no `dev QA` label, did you add the PR to the QA Queue?

### CODE REVIEW

**Review by tchayen — APPROVED** [review]

**Review by terrysahaidak — APPROVED** [review]

**Review by estebanmino — APPROVED** [review]

**Review by BrodyHughes — CHANGES_REQUESTED** [review]
^^^

**Review by BrodyHughes — APPROVED** [review]
No crashes happening.

Sped up 10 queued txns on one wallet then 6 queued txns on another on iPhone & Android.

**Review by brunobar79 — CHANGES_REQUESTED** [review]
Changing to request changes since the keychain patch was introduced later after my initial review and had some comments about it

**Review by BrodyHughes — APPROVED** [review]
Tested: queuing up and speeding up a bunch of txns, creating wallets, viewing secret phrases.

**Review by brunobar79 — APPROVED** [review]
👍 👍 👍

**Pull request merged**
