### PR TITLE
Create `codegen-translations` script and update related files.

### PR DESCRIPTION
**Pull request by marco**
## What changed (plus any additional context for devs)

A little while ago, @osdnk mentioned that it might be nice to have TypeScript types for i18n keys. This adds a script to generate a declarations file for those types, enabling autocomplete. If the script isn't run, there is no effect on the existing behavior.

## PoW (screenshots / screen recordings)

Autocomplete now will appear like this after running `yarn codegen-translations`:

Screen Shot 2022-01-24 at 1 23 25 PM

## Dev checklist for QA: what to test

- Running `yarn codegen-translations` should generate the `src/languages/types-generated.d.ts` types file.
- The project should compile with or without the `.d.ts` file.

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels?

### CODE REVIEW

**Comment by markdalgleish** [comment]
I tried this out locally and found that the module augmentation introduced via `declare module 'i18n-js'` overloads the original `t` function rather than replacing its type signature, meaning that you don't get any type errors when using invalid keys since it falls back to the original looser typing.

The generated types look good, but maybe we need to hook them up to our own `t` function that wraps `i18n-js` internally? That way our custom `t` function could use your generated types for its API without any augmentation.

**Comment by marco** [comment]
@markdalgleish Ah yes, that's a good point. I think the hard part is to ideally avoid type errors if the script isn't run. I think that would require some sort of "default" in the wrapper function, but that would then get merged with the new types in the same way as the `i18n-js` declaration types do.

In other words, I'm wondering if there's a way to have our wrapper function:

```ts
export function t(scope: ScopeType) {
  ...
}
```

while updating `ScopeType` separately through the generated/gitignored file. I'm not sure if there's a way to do this without either (a) requiring the script to be run before compiling or (b) having a default that gets merged instead of overwritten. I definitely could be missing something here tough.

Please let me know what you think, thanks!

**Comment by markdalgleish** [comment]
Maybe it'd be worth checking in the generated types? We could also run the script when starting the app to ensure it's always up to date in case anything slipped through, but the script doesn't have to be blocking.

**Comment by marco** [comment]
@markdalgleish Ah, that makes sense. I think in that case I'll probably hold off on this until after the current i18n PR goes through, and then I can try using the wrapper and the committed types. Thanks!

**Review by jinchung — APPROVED** [review]
🌮

**Review by skylarbarrera — APPROVED** [review]
file merging this and changing separately

**Pull request merged**
