### PR TITLE
profiles: profile avatar / names updates after ens transactions

### PR DESCRIPTION
**Pull request by estebanmino**
Fixes TEAM2-354
Fixes RNBW-4131
Fixes RNBW-4174

Figma link (if any):

fixing behavior mentioned on tickets

- if the ENS changes we change name and avatar

## Screen recordings / screenshots

https://user-images.githubusercontent.com/12115171/183002096-870f70dd-ea43-48c5-b055-0ee83c6a6bb0.mp4

added this to e2e ^ to check if the names / account label are changing correctly

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels? (`team1/team2`, `critical path`, `release`, `dev QA`)
- [x] Did you test both iOS and Android?
- [ ] If your changes are visual, did you check both the light and dark themes?
- [x] Added e2e tests? If not, please specify why
- [ ] If you added new critical path files, did you update the CODEOWNERS file?
- [ ] If no `dev QA` label, did you add the PR to the QA Queue?

### CODE REVIEW

**Comment by jxom** [comment]
Probably unrelated to this PR, but when I update my ENS avatar on my primary ENS (`jaketest7.eth`), it also sets the primary name again.

Updating my avatar performed these 2 txns (setting name to `jaketest7.eth` is redundant because it is already my primary name):

https://etherscan.io/tx/0xd686248f3fd472c9356443a5b6452151bc43df54f12c82c1204e86b36739c925
https://etherscan.io/tx/0xdeaaef84bd89f6e4ae29cfc3bf9f9a67532510e13e1dbc99f6a3d35f7f3e23be

**Comment by jxom** [comment]
After sending off my ENS (`jaketest7.eth`) with a set avatar, it removes the name but still has the avatar set:

Screen Shot 2022-08-05 at 4 22 00 pm

**Comment by estebanmino** [comment]
@jxom makes sense! just updated it to only maintain the avatar if it was a local image, if it's not will remove the image

**Comment by BrodyHughes** [comment]
exact same behavior as @jxom above! 

Additionally, if I have a wallet that already has a primary ENS name set (for example, 0xbrdy.eth), I can go in and edit the wallet to change the display name in our UI (changed from "0xbrdy.eth" > "tester"). If I do that, then change the ENS's pfp image, it will also subsequently update the wallets name to the ENS (reverts it from "tester" > "0xbrdy"). If that is all expected behavior then were good.

**Review by ibrahimtaveras00 — APPROVED** [review]

**Comment by estebanmino** [comment]
@BrodyHughes nice, yeah i can see that happening on the code i changed it for https://linear.app/rainbow/issue/RNBW-4174/wallet-with-custom-name-should-update-to-ens-name-when-set-as-primary, let me think about it

**Review by BrodyHughes — APPROVED** [review]
wow code so good

**Review by benisgold — APPROVED** [review]

**Pull request merged**
