### PR TITLE
[RNBW-2458][RNBW-2140][RNBW-2873] UI is mixing up my wallet balances

### PR DESCRIPTION
**Pull request by derHowie**
## What changed (plus any additional context for devs)
We now make sure to use the account address received in the response when persisting asset data.

## Dev checklist for QA: what to test
You will need to watch a wallet with a lot of tokens in it (dame.eth worked well for me). Then quickly switch back and forth on the wallet screen between the heavy wallet and a nearly empty one. In prod you will eventually see assets from the heavy wallet make their way onto the other wallet's screen.
## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels?

### CODE REVIEW

**Review by brunobar79 — APPROVED** [review]
🐐

**Review by skylarbarrera — APPROVED** [review]
pls merge 🐐

**Comment by jinchung** [comment]
soz leaving a note here - do not merge yet

**Comment by jinchung** [comment]
hey sorry nit: can we do a `if (!matchingAddress) return;` type of early return and not have to put the rest of the logic inside the `if`

**Review by jinchung — APPROVED** [review]
🌮

**Pull request merged**
