### PR TITLE
Remove dead files for discover

### PR DESCRIPTION
**Pull request by osdnk**
We are not caring about the experimental flag this time anyway

### CODE REVIEW

**Comment by skylarbarrera** [comment]
petition to keep cameraHeader button, I've got something i wanna do with it

**Comment by skylarbarrera** [comment]
I also think we should keep WC explainer and refactor as new users seem to click/use it frequently

**Comment by osdnk** [comment]
@skylarbarrera 
That's an amazing idea. I've heard someday about [git](https://git-scm.com/). 

Git is a free and open-source distributed version control system designed to handle everything from small to very large projects with speed and efficiency.

Git is easy to learn and has a tiny footprint with lightning-fast performance. It outclasses SCM tools like Subversion, CVS, Perforce, and ClearCase with features like cheap local branching, convenient staging areas, and multiple workflows.

**Comment by osdnk** [comment]
Jokes aside, we added experimental flags to faster integrate with things that are not ready and reduce the time needed to rebase some code is ready to merge, but the whole feature is not done.
However, it is not done for the purpose of keeping code that is just dead. If we want to do this, we have Git, but leaving this kind of code in most cases leads to forgetting about this and this is just additional work for the bundler to track those files and increases entropy for us while navigating in the codebase.

**Review by skylarbarrera — APPROVED** [review]
I'm more of a ClearCase guy but this will do 😝

**Pull request merged**
