### PR TITLE
Revert "Disable focusing on input on navigating to Currency Selection…

### PR DESCRIPTION
**Pull request by skylarbarrera**
… View from Swap flow (#2721)"

This reverts commit b868562180112797960d6bb610608c904309e2c6.

## What changed (plus any additional context for devs)
having the keyboard flash is still better than not having the input not focus at all

## PoW (screenshots / screen recordings)
current behavior: https://cloud.skylarbarrera.com/Screen-Recording-2021-12-19-12-36-45.mp4
reverted: https://cloud.skylarbarrera.com/Screen-Recording-2021-12-19-12-37-36.mp4

## Final checklist
[x] Assigned individual reviewers?
[x] Added labels?

### CODE REVIEW

**Comment by osdnk** [comment]
I think this is really annoying. Also, I managed once to get to the state where the keyboard was getting immediately dismissed on each focus (even after the transition). This did never happen after the commit

**Comment by terrysahaidak** [comment]
it's kinda default on Android even for native apps lol

**Review by terrysahaidak — APPROVED** [review]

**Comment by jinchung** [comment]
@christianbaroni we need your attention here

**Comment by skylarbarrera** [comment]
was having troubling getting a repro for the issue this was supposed to fix, will try again at some point

**Review by christianbaroni — APPROVED** [review]

**Pull request merged**
