### PR TITLE
Android frame rate metrics reporting

### PR DESCRIPTION
**Pull request by jkadamczyk**
Fixes RNBW-4211 RNBW-RNBW-4212
Figma link (if any):

## What changed (plus any additional context for devs)
* Implemented frame rate metrics for android
* Counts total frames drawn, total dropped, expected frames based on refresh rate

## What to test

* Check the stats if they look as we wanted

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels? (`team1/team2`, `critical path`, `release`, `dev QA`)
- [x] Did you test both iOS and Android?
- [x] If your changes are visual, did you check both the light and dark themes?
- [x] Added e2e tests? If not, please specify why
- [x] If you added new critical path files, did you update the CODEOWNERS file?
- [x] If no `dev QA` label, did you add the PR to the QA Queue?

### CODE REVIEW

**Comment by tchayen** [comment]
There's some seemingly unrelated linting error?

**Review by tchayen — APPROVED** [review]
Tested on Android and confirmed with Kuba that reports arrive properly.

**Comment by jkadamczyk** [comment]
The linting error is due to the fact that I updated react native typings which were outdated

**Review by brunobar79 — APPROVED** [review]
🚀

**Review by osdnk — APPROVED** [review]

**Comment by jkadamczyk** [comment]
Closing this PR, because we don't want to ship it anymore. This branch with the changes will still be available to leave a trace of how this thing looks like in case we ever think about doing sth like this again

**Pull request closed without merging**
