### PR TITLE
Swap review sheet UI updates

### PR DESCRIPTION
**Pull request by pugson**
Fixes TEAM2-120 TEAM2-122

## What changed (plus any additional context for devs)
- Updated coin and $ display to match design spec
- Fixed token truncation to always show the symbol
- Fixed padding around swap button
- Fixed weird coin tile padding on Android
- Fixed chevron shadow between coin tiles
- Fixed icon clipping for contract rows on Android
- Updated text color for swap review
- Updated copy for the Rainbow Fee explainer sheet
- Refactored components to use more of the design system
- Added shadow to swap route picker
- Matched swap settings order with one in Figma
- Removed price difference row

> **Note**: Being unable to trigger touch events on some rows on Android from time to time is caused by the bottom sheet swipe threshold being too sensitive. Light taps are picked up as swipes that are trying to close the bottom sheet 🤷‍♀️  This is a known bug also in ENS Profiles flow that we discussed with @jxom recently.

> **Note**: Screenshots below are outdated.

## PoW (screenshots / screen recordings)

| iOS Light  | iOS Light |
| ---------- |---------- |
| CleanShot 2022-06-22 at 01 35 11 AM@2x | CleanShot 2022-06-22 at 01 35 18 AM@2x |

| iOS Dark  | iOS Dark |
| --------- | -------- |
| CleanShot 2022-06-22 at 01 32 53 AM@2x | CleanShot 2022-06-22 at 01 32 59 AM@2x |

| Android  | Android |
| -------- | ------- |
| Screenshot_20220622-013804 | Screenshot_20220622-013808 |

## Dev checklist for QA: what to test
Swapping, looking at review sheet for swaps.

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels?
- [x] Added e2e tests? if not please specify why
- [x] If you added new files, did you update the CODEOWNERS file?

### CODE REVIEW

**Review by estebanmino — COMMENTED** [review]
comparing ios | figma | android
image

- we need to remove the `Difference in value` row
- DAI / SOCKS contract in more details has a different font color than the rest

**Review by estebanmino — COMMENTED** [review]
on android i'm having issues pressing the rows

in the video i'm trying to press rows, sometimes the press is handled, sometimes the row doesn't even animate even tho i'm pressing

https://user-images.githubusercontent.com/12115171/175071517-50f40e36-6c96-4b7b-b20f-70884d26dadb.mov

s

**Review by derHowie — APPROVED** [review]
looks beautiful on pixel 6 🌈

**Review by estebanmino — APPROVED** [review]
🔥

**Pull request merged**
