### PR TITLE
Add yarn nuke script

### PR DESCRIPTION
**Pull request by brunobar79**
Fixes RNBW-####
Figma link (if any):

## What changed (plus any additional context for devs)
I've been collecting feedback from different build issues so I compiled a list and wrote a script to handle all of them
(pod issues, ios cache, rn cache, node_modules, etc)

## Screen recordings / screenshots

Screen Shot 2022-08-18 at 5 46 53 PM

## What to test

You can pull this branch. Run `yarn nuke` and then `yarn fast` and you should be able to build on both platforms without issues.

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels? (`team1/team2`, `critical path`, `release`, `dev QA`)
- [x] Did you test both iOS and Android?
- [x] If your changes are visual, did you check both the light and dark themes?
- [x] Added e2e tests? If not, please specify why
- [x] If you added new critical path files, did you update the CODEOWNERS file?
- [x] If no `dev QA` label, did you add the PR to the QA Queue?

### CODE REVIEW

**Review by estebanmino — APPROVED** [review]
all new commands working on my end 🚀

**Comment by brunobar79** [comment]
PR fails on the message to slack because it originally had quotes on the name smh

**Comment by brunobar79** [comment]
Fixes 4376

**Review by skylarbarrera — APPROVED** [review]
nuke my shit

**Pull request merged**
