### PR TITLE
Add images to iOS notifications

### PR DESCRIPTION
**Pull request by jxom**
Fixes TEAM2-71

## What changed (plus any additional context for devs)

This PR adds images to iOS notifications.

## Screen recordings / screenshots

</img>

## What to test

Can test on TestFlight 1.6.17 (9)

- Ensure notifications still work properly in general
- Ensure images are attached to notifications that include images

### How to test notifications w/ images

1. Make sure you are subscribing to a topic via Settings -> Notifications Debug in the Rainbow App
2. Head to the [Firebase Notifications Composer](https://console.firebase.google.com/u/0/project/_/notification)
3. Create a new notification
4. Add a mock title, description and image
5. **IMPORTANT**: make sure you target a **Topic**
6. Insert `owner_1_{your address here}_received` into the input field
7. Send the notification off!

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels? (`team1/team2`, `critical path`, `release`, `dev QA`)
- [x] Did you test both iOS and Android?
- [x] If no `dev QA` label, did you add the PR to the QA Queue?

### CODE REVIEW

**Comment by pugson** [comment]
tried to test this with crypto coven and OKPC on TF but was only getting generic ERC-721 notifications 😔
image

**Comment by welps** [comment]
> tried to test this with crypto coven and OKPC on TF but was only getting generic ERC-721 notifications 😔
> image
> 

yeah it's bugging out right now,  @salman-rb is working on a fix i believe

**Comment by pugson** [comment]
alright ping me when i can send this shit back to my main wallet to test again lol

**Comment by salman-rb** [comment]
> alright ping me when i can send this shit back to my main wallet to test again lol

@pugson change was deployed few hours ago, should be good to test again

**Review by brunobar79 — APPROVED** [review]
Amazing!

**Pull request merged**
