### PR TITLE
chore: hide testnet settings

### PR DESCRIPTION
**Pull request by skylarbarrera**
Fixes APP-890

## What changed (plus any additional context for devs)
removing testnet settings from user facing since its been rugged for like 6 months

keeping it all there in case we reprioritize it

### CODE REVIEW

**Comment by walmat** [comment]
What happens if a user is on testnet mode? Do we need to write a migration?

**Review by walmat — APPROVED** [review]
LGTM, just had a small question

**Comment by skylarbarrera** [comment]
> What happens if a user is on testnet mode? Do we need to write a migration?

its actually been rugged since last summer, its impossible to get on a TF atm

**Comment by walmat** [comment]
> > What happens if a user is on testnet mode? Do we need to write a migration?
> 
> its actually been rugged since last summer, its impossible to get on a TF atm

got it, then yeah good to go from my perspective

**Pull request merged**
