### PR TITLE
TS bump to 4.9

### PR DESCRIPTION
**Pull request by jkadamczyk**
## What changed (plus any additional context for devs)

* Bumped TS to the latest version and fixed some errors that came along the way
* Fixed redash patch that was ignoring typescript issues there – we use an old version, the new one will likely be working fine  without it.
* Bumped patch-package since there was a new version with some bug fixes
* Removed `parseQueryParams` file since it had no usages and was erroring out with TS

### CODE REVIEW

**Review by estrattonbailey — APPROVED** [review]
💪

**Comment by jkadamczyk** [comment]
@SocketSecurity ignore

**Comment by jkadamczyk** [comment]
@SocketSecurity ignore react-native-cloud-fs@2.5.0

**Review by skylarbarrera — APPROVED** [review]
👑

**Pull request merged**
