### PR TITLE
Fix profile screen shimmer background

### PR DESCRIPTION
**Pull request by christianbaroni**
Think this fixes/removes this light background that sometimes shows behind the profile screen loading state

IMG_7071

### CODE REVIEW

**Review by skylarbarrera — APPROVED** [review]
confirmed 👌

**Review by nicoglennon — APPROVED** [review]
💎

**Review by BirinIhor — COMMENTED** [review]
ios/TransactionListLoadingViewCell.xib

**Review by BirinIhor — CHANGES_REQUESTED** [review]
@christian/fix-native-shimmer

**Review by BirinIhor — CHANGES_REQUESTED** [review]
> @@ -230,7 +230,7 @@ export const buildUniqueTokenList = (uniqueTokens, selectedShowcaseTokens) => {
     });
   }
 
-  rows = sortBy(rows, ['familyName']);
+  rows = sortBy(rows, row => row.familyName.replace('The ', '').toLowerCase());
Could use a more general regex to catch all the "the"s:

const theRegex = /^(the|The|THE)\s/g;
rows = sortBy(rows, row => row.familyName.replace(theRegex, '').toLowerCase());
—

**Pull request merged**
