### PR TITLE
send sheet keyboard handling and ui clean up 

### PR DESCRIPTION
**Pull request by skylarbarrera**
Fixes RNBW-1997 

## What changed (plus any additional context for devs)

removed unneeded keyboard handling effect, was improperly dismissing the keyboard and doesn't seem we need for sheet keyboard handling anymore

UI tweaks: 
- removed some old extra android padding that is unneeded post send sheet V2 design
- adjusted gasSpeedButton padding to more closely match iOS
 
## PoW (screenshots / screen recordings)
pixel: https://cloud.skylarbarrera.com/Screen-Recording-2021-12-10-11-43-48.mp4

samsung w/ soft menu(debug so its slow AF): https://cloud.skylarbarrera.com/Screen-Recording-2021-12-10-12-13-14.mp4

## Dev checklist for QA: what to test
input handling(auto focus, etc) should work same on iOS 

## Final checklist
[x] Assigned individual reviewers?
[x] Added labels?

### CODE REVIEW

**Comment by osdnk** [comment]
any ideas why did we have this code on the first place?

**Comment by terrysahaidak** [comment]
Yeah, kinda weird code. I would check git blame for these changes.

**Comment by skylarbarrera** [comment]
@osdnk @terrysahaidak this is from our initial android clean up PR from a year ago, was moved by bruno when he was working but didn't change the code at all. so without doing some deep investigating not sure, @osdnk id guess it was you to handle some input focusing/sheet dismissing behavior but without it behavior now matches up to iOS

**Comment by osdnk** [comment]
If it's not changing anything on iOS, idc

**Review by osdnk — APPROVED** [review]

**Review by terrysahaidak — APPROVED** [review]

**Pull request merged**
