### PR TITLE
Add react-native-turbo-haptics

### PR DESCRIPTION
**Pull request by christianbaroni**
## What changed (plus any additional context for devs)
- Adds [react-native-turbo-haptics](https://github.com/christianbaroni/react-native-turbo-haptics)
- Replaces instances of `runOnJS(triggerHapticFeedback)` with the new `triggerHaptics`
- Tested on both iOS and Android

## What to test
- Should feel haptic feedback on iOS and Android when for example:
  - Submitting a swap
  - Dragging the swap slider to 0 or 100%

### CODE REVIEW

**Comment by brunobar79** [comment]
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@christian/turbo-haptics/7640f8eb4d2ac03a9a6b8b3c46a468ef63b94d1b.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/@christian/turbo-haptics/7640f8eb4d2ac03a9a6b8b3c46a468ef63b94d1b.ipa) for 7640f8eb4d2ac03a9a6b8b3c46a468ef63b94d1b

**Comment by brunobar79** [comment]
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@christian/turbo-haptics/932118396b035a11fe551a9004e0f001524f571c.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/@christian/turbo-haptics/932118396b035a11fe551a9004e0f001524f571c.ipa) for 932118396b035a11fe551a9004e0f001524f571c

**Comment by brunobar79** [comment]
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@christian/turbo-haptics/a885c8a7b6193435fd96ed6b8150194483fbb0b4.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/@christian/turbo-haptics/a885c8a7b6193435fd96ed6b8150194483fbb0b4.ipa) for a885c8a7b6193435fd96ed6b8150194483fbb0b4

**Comment by brunobar79** [comment]
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@christian/turbo-haptics/f7833009722712ad5008d01b512ef3deda753a48.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/@christian/turbo-haptics/f7833009722712ad5008d01b512ef3deda753a48.ipa) for f7833009722712ad5008d01b512ef3deda753a48

**Review by maxbbb — APPROVED** [review]

**Review by greg-schrammel — APPROVED** [review]
🔥

**Pull request merged**
