### PR TITLE
CHANGE: upgrade camera package to react-native-vision-camera FIX: [APP-171], [APP-776]

### PR DESCRIPTION
**Pull request by BrodyHughes**
Fixes APP-171

Goals: 
- upgrade camera package to `react-native-vision-camera`
- get green camera usage light to turn off when expected (https://linear.app/rainbow/issue/APP-171/camera-light-is-staying-on-after-making-a-wc-link-in-rainbow)
- Make android scan low contrast QR codes better (https://linear.app/rainbow/issue/APP-776/android-has-difficulty-scanning-walletconnect-qr-codes-in-dark-mode)

I believe this PR accomplishes all three of these. Things I also had to do to make the new package work:
- bump Kotlin version
- update some patches to point to the new Kotlin version

Remaining concerns for eng:
- How should I handle inline styles?

POW:

In the video I test closing by swiping and by the 'x' button. The green status light and the torch both properly turn off.

<video src="https://github.com/rainbow-me/rainbow/assets/41711440/7b38a19f-23ee-4a1d-9655-bb68ee9ac96d" />

### CODE REVIEW

**Review by dereknelson — APPROVED** [review]
not much to say other than it works, code is clean and straightforward, just a great showing all around 👍🏻

**Review by skylarbarrera — APPROVED** [review]
good 2 go, needs android testing

**Comment by walmat** [comment]
Kinda Sus intermediate screen on android. Not sure if this is expected but doesn't seem like it.

**Review by ibrahimtaveras00 — APPROVED** [review]
🌮

**Pull request merged**
