### PR TITLE
Bumping React Native because of Android build issues

### PR DESCRIPTION
**Pull request by jkadamczyk**
## What changed (plus any additional context for devs)

Facebook communicated that there is a hotfix release addressing issues caused by some maven central binary upload that messed up builds for everyone.

more info here https://github.com/facebook/react-native/issues/35210#issuecomment-1304536693

### CODE REVIEW

**Review by skylarbarrera — APPROVED** [review]
:shipit:

**Comment by brunobar79** [comment]
Did u make sure we don't need all these fixes that Terry did for the statusbar on android?

Screen Shot 2022-11-07 at 10 39 49 AM

**Review by estrattonbailey — APPROVED** [review]
Pending Bruno's comment

**Comment by jkadamczyk** [comment]
I'm merging that right now and will revert the android statusbar fixes Terry made once I build the react native .aar files

**Pull request merged**
