### PR TITLE
Bugfix/search ethereum list

### PR DESCRIPTION
**Pull request by estebanmino**
On `Search all of Ethereum` I couldn't see the add button nor scroll down the list on android.

Now is fixed https://recordit.co/NDrRAKMmCo

Fixes RNBW-1282

### CODE REVIEW

**Review by brunobar79 — APPROVED** [review]
🐐 !

**Review by skylarbarrera — APPROVED** [review]
🐐

**Comment by skylarbarrera** [comment]
lgtm, lemme double check CI real quick

**Comment by skylarbarrera** [comment]
good to go!

**Pull request merged**
