### PR TITLE
Fix ETH balance

### PR DESCRIPTION
**Pull request by brunobar79**
PoW http://recordit.co/mAKYnU54JP

### CODE REVIEW

**Review by welps — APPROVED** [review]
:+1:

**Comment by jinchung** [comment]
I'm missing some context here but just wanted to confirm: `COVALENT_ETH_ADDRESS` is only that for mainnet? (nothing we need to handle for arb/poly?)

**Review by jinchung — APPROVED** [review]
🥑

**Comment by welps** [comment]
> I'm missing some context here but just wanted to confirm: `COVALENT_ETH_ADDRESS` is only that for mainnet? (nothing we need to handle for arb/poly?)

@jinchung We use the same address (which I've called MAINNET_ETH_PLACEHOLDER_ADDRESS internally) for Polygon because the polygon -> mainnet token mapper maps polygon `WETH` to `ETH` instead of mainnet `WETH`: https://github.com/rainbow-me/rainbow/blob/develop/src/redux/polygonExplorer.js#L96

If you want to nitpick, Bruno probably apply this const to that area of code too

**Review by ibrahimtaveras00 — APPROVED** [review]
👍🏽

**Pull request merged**
