### PR TITLE
Add a shadow to Get a new wallet in Onboarding flow

### PR DESCRIPTION
**Pull request by osdnk**
Fixes RNBW-4021
Figma link (if any):

## What changed (plus any additional context for devs)
I added the elevation (cause we don't have shadows on Android) and looks ok. I removed the displacement on Android (not needed). I made the whole component visible on both platforms

## Screen recordings / screenshots
image

no impact on IOS

## What to test
Just observe if there is a shadow changing color

### CODE REVIEW

**Review by tchayen — APPROVED** [review]
Tested on Samsung Galaxy S10e. Works.

**Comment by tchayen** [comment]
CI go stuck. Maybe rebase will help?

**Review by terrysahaidak — APPROVED** [review]

**Pull request merged**
