### PR TITLE
Remove toChecksumAddress for assets urls

### PR DESCRIPTION
**Pull request by brunobar79**
Fixes RNBW-####

## What changed (plus any additional context for devs)
Created a new (default) branch on the assets repo where all the addresses are lowercased so we don't have to call the expensive function  `toChecksumAddress`

## PoW (screenshots / screen recordings)
Before (checksummed): 
https://raw.githubusercontent.com/rainbow-me/assets/master/blockchains/ethereum/assets/0x6B175474E89094C44Da98b954EedeAC495271d0F/logo.png

After (lowercase):
https://raw.githubusercontent.com/rainbow-me/assets/lowercase/blockchains/ethereum/assets/0x6b175474e89094c44da98b954eedeac495271d0f/logo.png

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels?
- [ ] Added e2e tests? if not please specify why - Doesn't apply
- [ ] If you added new files, did you update the CODEOWNERS file? - No new files

### CODE REVIEW

**Review by skylarbarrera — APPROVED** [review]
🤝

**Comment by osdnk** [comment]
I wonder if this is good. This is a fork and we want to sometimes merge from the original repo. Will you rerun this script every time? Shouldn't we rather make an automated mirror for this?

**Comment by brunobar79** [comment]
@skylarbarrera  how many times have you pulled upstream so far?

**Comment by skylarbarrera** [comment]
> @skylarbarrera how many times have you pulled upstream so far?

like once every couple of months, def would be nice to have some automation set up for this but for now I think this is totally fine

**Comment by brunobar79** [comment]
> > @skylarbarrera how many times have you pulled upstream so far?
> 
> like once every couple of months, def would be nice to have some automation set up for this but for now I think this is totally fine

Agreed.  Here's the script if someone wants to automate it in the future: https://gist.github.com/brunobar79/7f66f9c71a66c61103252ce0dbaed7fb

**Comment by osdnk** [comment]
hm, I'm not sure. This is actually a problem that we make those updates not too often and this is making this a bit more difficult

**Comment by osdnk** [comment]
Also, I am not sure if the name `develop` for this branch is good. This is a bit misleading tbh

**Comment by terrysahaidak** [comment]
agree on the branch name, perhaps `lowercased`?

**Comment by osdnk** [comment]
Can we hold this for a while? @skylarbarrera is researching some more ultimate solution so we might want to stop relying of fetching images from GitHub at all

**Comment by brunobar79** [comment]
if u merge this as it is you can get the perf. boost and iterate later on a better approach but ok

**Comment by terrysahaidak** [comment]
I plan to improve BalanceCoinRow component in the near future, we might get back to this PR after it.

**Comment by osdnk** [comment]
let's merge it lol

**Review by osdnk — APPROVED** [review]

**Comment by brunobar79** [comment]
FYI renamed the branch to "lowercase" instead of "develop". Will merge after CI passes

**Pull request merged**
