### PR TITLE
Fix refresh persistence bug

### PR DESCRIPTION
**Pull request by jinchung**
Fixes APP-840

### CODE REVIEW

**Comment by walmat** [comment]
LGTM! Nice work. Pull to refresh working. Not necessarily related to the changes made through this PR, but [should the `refetchInterval` be lowered](https://github.com/rainbow-me/rainbow/blob/bca9b45fe5d1f84843c15588be9a6cab0ffc1dd5/src/resources/assets/UserAssetsQuery.ts#L282)? 5 minutes seems like a long time to keep price data unless manually refreshed.

**Comment by jinchung** [comment]
> LGTM! Nice work. Pull to refresh working. Not necessarily related to the changes made through this PR, but [should the `refetchInterval` be lowered](https://github.com/rainbow-me/rainbow/blob/bca9b45fe5d1f84843c15588be9a6cab0ffc1dd5/src/resources/assets/UserAssetsQuery.ts#L282)? 5 minutes seems like a long time to keep price data unless manually refreshed.

Thanks! I'll take a revisit to this separately - will depend on caching timeouts on the backend and also would like to be thoughtful bc this is the "assets balances" endpoint and we still have the separate websockets endpoint for generic asset prices, which I would need to check if we're subscribing to anyway for the wallet's assets as well

**Comment by skylarbarrera** [comment]
agree 5 min seems way too long

**Review by walmat — APPROVED** [review]

**Review by ibrahimtaveras00 — APPROVED** [review]
Looks good on both OS's 👍🏽

**Pull request merged**
