### PR TITLE
Fixes for savings label

### PR DESCRIPTION
**Pull request by osdnk**

### CODE REVIEW

**Comment by christianbaroni** [comment]
hey @osdnk so I made these recordings at the same time

both the starting amounts and the animation speeds are different in this PR and the app store version, I'm not sure which is correct

cc @jinchung @brunobar79 

app store version: https://www.dropbox.com/s/nn293etdiukpb2e/RPReplay_Final1593462586.MP4?dl=0

this PR (debug mode): https://www.dropbox.com/s/gjc832qjpyoe9b1/Screen%20Recording%202020-06-29%20at%204.29.25%20PM.mov?dl=0

**Comment by osdnk** [comment]
@mikedemarais can you help be reviewing this logic?

**Comment by christianbaroni** [comment]
just took a quick look, seems like this logic is missing? to calculate future value

https://github.com/rainbow-me/rainbow/blob/c3822cec6db43daedc4faf2e83b1e734a0b55b86/src/components/savings/SavingsListRow.js#L111-L131 https://github.com/rainbow-me/rainbow/blob/c3822cec6db43daedc4faf2e83b1e734a0b55b86/src/helpers/savings.js#L23-L27

also this would always be 0, right?

https://github.com/rainbow-me/rainbow/blob/c3822cec6db43daedc4faf2e83b1e734a0b55b86/ios/RainbowText.m#L49 https://github.com/rainbow-me/rainbow/blob/c3822cec6db43daedc4faf2e83b1e734a0b55b86/ios/RainbowText.m#L69-L70

**Comment by osdnk** [comment]
`_time` is evaluated on the beginning of the animation and it's persisted for the time of animation's duration (edited) so `diff` is basically "number of seconds from the beginning of the animation" (edited) 
From my intuition: we have calculated `futureValue` (1 day from now), then I divide it by number of seconds per day and the multiply with `diff`

**Comment by christianbaroni** [comment]
think this is why the starting point is different:

https://github.com/rainbow-me/rainbow/blob/c3822cec6db43daedc4faf2e83b1e734a0b55b86/src/components/savings/SavingsListRowAnimatedNumber.js#L63

should be `initialValue: Number(initialValue)`

still not sure where the issue with the speed is

**Comment by osdnk** [comment]
@christianbaroni @mikedemarais 
speed can be increased with `interval` prop. I changed it to `0' - it means 30 ms. I firstly slow it down because of performance, but now I see that after implementing there's no need to.

**Comment by christianbaroni** [comment]
@osdnk it's not the update interval but the speed at which the numbers increase. the animation speed should be determined by future value

for example if current value is $10 and future value (in 24 hours) is $12.40, every hour it should move +$0.10

if you compare the two videos above, the numbers are increasing at different speeds. I'm not sure if it's the JS version or the native version that's moving at the wrong speed

**Comment by osdnk** [comment]
@christianbaroni @mikedemarais 
I think the reason is because I removed one character (there were 10 digits after comma, now there are 9). I asked @mikedemarais for restoring it and then it should be same as previously

**Pull request merged**
