### PR TITLE
Fix initialRoute on Android

### PR DESCRIPTION
**Pull request by osdnk**

### CODE REVIEW

**Comment by osdnk** [comment]
Fixes https://linear.app/rainbow/issue/RNBW-1222/fix-swipelayout-initialroute-on-android

**Review by brunobar79 — APPROVED** [review]
🐐

**Comment by brunobar79** [comment]
@osdnk  Looks like the build failed because it failed to apply the patch

**Comment by osdnk** [comment]
@brunobar79 I had an issue with the patching package.json so I just made changes and added it as a file

**Review by skylarbarrera — APPROVED** [review]
lgtm

to note, this fixes the issue when opening the app but the issue still remains for initial wallet load from the welcome screen. This seems fine for now 💯

**Pull request merged**
