### PR TITLE
Handle refuel sheet when not enough source token

### PR DESCRIPTION
**Pull request by sammdec**
Fixes TEAM2-474
Figma link (if any):

## What changed (plus any additional context for devs)
This PR adds logic to handle the non-happy paths for refuel in crosschain swaps. 
The various cases are:
- A user is max swapping from the native token to another chain but doesn't have native token on the destination chain e.g Polygon matic. In this case we offer to deduct $3 worth of native token and convert it across to the native token on the destination
- A user is swapping but if we took $3 worth of native token to convert there wouldn't be enough native token to make the tx succesfully

## Screen recordings / screenshots
Screenshot 2022-10-11 at 15 45 38

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels? (`team1/team2`, `critical path`, `release`, `dev QA`)
- [x] Did you test both iOS and Android?
- [x] If your changes are visual, did you check both the light and dark themes?
- [ ] Added e2e tests? If not, please specify why
- [ ] If you added new critical path files, did you update the CODEOWNERS file?
- [ ] If no `dev QA` label, did you add the PR to the QA Queue?

### CODE REVIEW

**Comment by sammdec** [comment]
\rebase

**Review by estebanmino — APPROVED** [review]
confirmed last 2 fixes are working 🥇

**Review by skylarbarrera — APPROVED** [review]
lovely ser

**Pull request merged**
