### PR TITLE
Add context menu for android transactions

### PR DESCRIPTION
**Pull request by tchayen**
Fixes RNBW-4062
Figma link (if any):

## What changed (plus any additional context for devs)

This PR migrates the popup that appears on Android when pressing transaction row from current system to the context menu introduced by @osdnk in #3831.

The code for achieving context menu for both iOS and Android requires quite a bit of structure:
1. We have to calculate menu items.
2. We have to create iOS callback (it is applied to animated button and programmatically invokes context menu which receives callback for item presses).
3. We have to create Android callback (it is applied to ContextMenuButton and it is direct callback for item presses).

So basically we need items, we need item press callback, we need a wrapper for iOS that invokes proper API and we need to supply them in two different places. This probably asks for an abstraction layer.

I wasn't sure exactly what path to follow here and how to properly balance speed and readability. Let's discuss!

## Screen recordings / screenshots

|Before|After|Dark mode (after)|
|--|--|--|
|Screenshot_20220801-174247_Rainbow|Screenshot_20220801-174044_Rainbow|Screenshot_20220801-174611_Rainbow|

## What to test

Press on as many different kinds of transactions as you can find to find all possible buttons in the context menu. You are looking for: view contact, add to contacts, speed up, cancel, view on Etherscan.

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels? (`team1/team2`, `critical path`, `release`, `dev QA`)
- [x] Did you test both iOS and Android?
- [x] If your changes are visual, did you check both the light and dark themes?
- [x] Added e2e tests? If not, please specify why
- [x] If you added new critical path files, did you update the CODEOWNERS file?
- [ ] If no `dev QA` label, did you add the PR to the QA Queue?

### CODE REVIEW

**Review by osdnk — APPROVED** [review]
i think its ok

**Review by osdnk — COMMENTED** [review]
Actually, can you also show if we can show a title (with ellipsis)? How will it look like?

**Comment by tchayen** [comment]
Good catch! This would otherwise be a small regression.

Screenshot_20220801-195047_Rainbow

**Comment by osdnk** [comment]
Can you send it to design approval? I would skip the date

**Comment by osdnk** [comment]
This looks a bit long-ish

**Comment by estrattonbailey** [comment]
I also noticed the need for multiple forms of config when working on the Hide NFTs project. If this is a common need, I agree with @tchayen that we should consider creating an abstraction over this.

I might be wrong, but the [new library](https://github.com/react-native-menu/menu) we're using looks to support iOS and Android in the same way. Do we need a new abstraction or can we migrate to using this new library?

**Comment by osdnk** [comment]
I think we needed some alteration to those libs anyway. Let's make a migration plan afterward. Now we should just iterate on it with minimal effort and then unify this when we'll have a bit more time

**Review by perunt — APPROVED** [review]

**Pull request merged**
