### PR TITLE
Use nonce manager with WC session address

### PR DESCRIPTION
**Pull request by estebanmino**
Fixes RNBW-2125

## What changed (plus any additional context for devs)

We're using the account settings address instead of the wallet connect session address in `TransactionConfirmationScreen`, so the nonce manager is getting another nonce if those addresses are different. Changed it to use `accountInfo.address` instead.

## Final checklist
[ ] Assigned individual reviewers?
[ ] Added labels?

### CODE REVIEW

**Review by jinchung — APPROVED** [review]
🎂

**Comment by jinchung** [comment]
Where is accountAddress used in that file anymore, and should it even be

**Review by brunobar79 — APPROVED** [review]
🙏 🙏 🙏

**Review by derHowie — APPROVED** [review]
👍

**Pull request merged**
