### PR TITLE
Get shadows to display

### PR DESCRIPTION
**Pull request by tchayen**
Fixes RNBW-3946

There was a visual regression introduced with merge of balanced coin row refactor: some coin shadows were gone.

## What changed (plus any additional context for devs)

ETH icon shadow should be back together with some others (shiba inu for example).

## PoW (screenshots / screen recordings)

> **NOTE:** as of now, those screenshots should be accurate as there were no code changes. However, they might turn out to be inaccurate because of human error (I messed up something while pasting) or some glitch (bundler not updating when switching branches). Use at your own risk.

||Before|Develop|Fix|
|--|--|--|--|
|Android light|an_before_light|an_develop_light|an_now_light|
|Android dark|an_before_dark|an_develop_dark|an_now_dark|
|iPhone light|ip_before_light|ip_develop_light|ip_now_light|
|iPhone dark|ip_before_dark|ip_develop_dark|ip_now_dark|

## Dev checklist for QA: what to test

Shadows under coin icons. Presumably develop state is wrong, target state is the one from before (but I can be wrong).

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels?
- [x] Added e2e tests? if not please specify why
- [x] If you added new files, did you update the CODEOWNERS file?

### CODE REVIEW

**Review by osdnk — APPROVED** [review]

**Review by perunt — APPROVED** [review]

**Review by BrodyHughes — APPROVED** [review]
QA checked & compared to prod:
- discover 👍 
- balance screen 👍 
- expanded state 👍 
- design 👍

**Review by BrodyHughes — CHANGES_REQUESTED** [review]
Still need to QA. Approved wrong PR.

**Comment by BrodyHughes** [comment]
Light mode looks good! I need some clarification on what Dark mode shadows should look like. Are they supposed to have color or not? This should effect token shadows everywhere right?

**Review by BrodyHughes — APPROVED** [review]
Looks good! Shadows have color on light mode and no color on dark mode. Checked balances page, expanded state and discover page. The pools shadows are still wrong.

**Review by terrysahaidak — APPROVED** [review]

**Pull request merged**
