### PR TITLE
perf: RecyclerAssetList

### PR DESCRIPTION
**Pull request by cawfree**
- Attempted memoize dynamically allocated props wherever possible.
  - Replaced calls to `setTimeout` with `requestAnimationFrame`.

### CODE REVIEW

**Comment by osdnk** [comment]
@cawfree do you notice any perf boost? 

What do you think about making this functional component?

**Comment by cawfree** [comment]
About being functional; I'm completely open to doing that! I tried to keep the changes small to reduce risk, but I'd be happy to do the larger refactor if you think it's worth doing.

**Comment by osdnk** [comment]
Hi, @cawfree 
Please, can you answer if you find it boosting the performance in some way? If yes, it is okay.

The only reason I am concern (against optimistic approving I always do 😄) is that this component is a bit "fragile". It is a result of our researches about the performance and observation and this might reflect in a code that is not the highest quality.  

If you are modifying this component, we will need to make a lot of validation about corner cases, because we are simply not understanding some code here and our knowledge regarding some decisions is distributed. 

Therefore, if you are already making an attempt to understand this code and additionally, we need to put some effort into verifying these crucial changes, why not take this opportunity to make some more general refactor? It is one of the very last components that are still not FC and maybe you can be the one who will rewrite this and make this code understandable for others.

**Comment by osdnk** [comment]
Additionally, I am sorry, I see some merge conflicts

**Comment by cawfree** [comment]
I can confirm that this does increase performance, but I completely agree, since this component is fragile it makes sense to perform the proper work in migrating it over to an FC so we can begin to understand it and see where the patterns for reuse are.

As it stands, this is just a quick fix (and adding more complexity, who wants that? 🤣)

Can we keep this draft open?

I'd like to continue to work on the refactor here. I want to try abstracting all the various logic and apply tests to the existing setup. From  there I should be able to gradually replace them.

**Comment by osdnk** [comment]
Yes, of course. I do not mind having open drafts :)

**Pull request closed without merging**
