### PR TITLE
Fix improper gas fee calculation

### PR DESCRIPTION
**Pull request by walmat**
Fixes APP-1887

## What Changed
During the refactor a mul got removed by me which is needed for proper estimations. I also noticed some inconsistencies for when a user has a preferred network set that we aren't defaulting to that on swaps open, so I fixed those as well in this PR.

## What To Test
Should test switching between chains to make sure the EIP1559 cases are handled properly now.

### CODE REVIEW

**Comment by brunobar79** [comment]
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@matthew/fix-wrong-gas-fee-calculation/8868f53495022cb2eeea3f9407a1b0ff9e5b580f.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/@matthew/fix-wrong-gas-fee-calculation/8868f53495022cb2eeea3f9407a1b0ff9e5b580f.ipa) for 8868f53495022cb2eeea3f9407a1b0ff9e5b580f

**Comment by brunobar79** [comment]
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@matthew/fix-wrong-gas-fee-calculation/900d758d193a8bfc667db9e09df2677a7413bfa3.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/@matthew/fix-wrong-gas-fee-calculation/900d758d193a8bfc667db9e09df2677a7413bfa3.ipa) for 900d758d193a8bfc667db9e09df2677a7413bfa3

**Comment by brunobar79** [comment]
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/@matthew/fix-wrong-gas-fee-calculation/17e2b856305610d66654c4c47253340a4065830e.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/@matthew/fix-wrong-gas-fee-calculation/17e2b856305610d66654c4c47253340a4065830e.ipa) for 17e2b856305610d66654c4c47253340a4065830e

**Review by ibrahimtaveras00 — APPROVED** [review]
All fixes look good now, QA passed 👍🏽

**Review by benisgold — APPROVED** [review]

**Pull request merged**
