### PR TITLE
Track token lists

### PR DESCRIPTION
**Pull request by greg-schrammel**
Fixes APP-2067

## What changed (plus any additional context for devs)

tracks token lists, amount of tokens in the list and how many have icons and price

```ts
screen: 'wallet' | 'swap' | 'send';
total_tokens: number;
no_icon: number;
no_price?: number;
query?: string; // query is only sent when searching token to buy/sell in the swap screen
```

### CODE REVIEW

**Comment by brunobar79** [comment]
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/gregs-analytics-2/af4c29f85a20588800c44ece0afe6af6d0ff6652.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/gregs-analytics-2/af4c29f85a20588800c44ece0afe6af6d0ff6652.ipa) for af4c29f85a20588800c44ece0afe6af6d0ff6652

**Review by walmat — APPROVED** [review]

**Comment by brunobar79** [comment]
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/gregs-analytics-2/df43c82b020550a17c4efbd93a6c579be5d3d8a1.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/gregs-analytics-2/df43c82b020550a17c4efbd93a6c579be5d3d8a1.ipa) for df43c82b020550a17c4efbd93a6c579be5d3d8a1

**Comment by derHowie** [comment]
> > Hey @greg-schrammel, this doesn't appear to be functioning correctly and may not be covering the ticket's requirements. I saw three issues:
> > 
> > * the function meant to track assets on the wallet screen doesn't fire
> > * the send screen is sending information for the wallet screen
> > * I don't believe any tracking was added for the discover screen
> 
> ah the discover screen I was thinking trending tokens but there is a search there, should I add this tracking for that?

yes, please

**Comment by greg-schrammel** [comment]
> Hey @greg-schrammel, this doesn't appear to be functioning correctly and may not be covering the ticket's requirements. I saw three issues:
> 
> * the function meant to track assets on the wallet screen doesn't fire
> * the send screen is sending information for the wallet screen
> * I don't believe any tracking was added for the discover screen

- confirmed the track on wallet screen is working
- fixed the `screen` param in send screen
- added tracking to discovery screen

**Comment by brunobar79** [comment]
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/gregs-analytics-2/646231c1668d602419792d2a93fa64979787b127.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/gregs-analytics-2/646231c1668d602419792d2a93fa64979787b127.ipa) for 646231c1668d602419792d2a93fa64979787b127

**Comment by brunobar79** [comment]
Launch in [simulator](http://localhost:29070/install/ios?virtual=https://app-team.p.rainbow.me/gregs-analytics-2/2d7a5358f99de8cbe3745a4c99bf6138ca5d9e4d.app.zip) or [device](http://localhost:29070/install/ios?physical=https://app-team.p.rainbow.me/gregs-analytics-2/2d7a5358f99de8cbe3745a4c99bf6138ca5d9e4d.ipa) for 2d7a5358f99de8cbe3745a4c99bf6138ca5d9e4d

**Review by derHowie — APPROVED** [review]
✅

**Pull request merged**
