### PR TITLE
Fix speed up and cancel sheet

### PR DESCRIPTION
**Pull request by brunobar79**
QA:  Test Speed up and Cancel for all the following scenarios on Android & iOS

(use a very low custom base fee, like 1/2 of the current value to have time to test)

- Send flow => speed up / cancel
- Send flow + restarting the app => 
- WalletConnect (Uniswap) => speed up / cancel
- WalletConnect + restarting the app => speed up / cancel

Fixes RNBW-1956

### CODE REVIEW

**Review by estebanmino — DISMISSED** [review]
tried and code lgtm

**Review by skylarbarrera — APPROVED** [review]
read up on convo & code lgtm, imo we should save this for final regression QA so its not blocked 

💯💯 💯

**Review by estebanmino — DISMISSED** [review]
🚀

**Review by skylarbarrera — DISMISSED** [review]

**Review by skylarbarrera — APPROVED** [review]
👌

**Review by estebanmino — APPROVED** [review]

**Review by estebanmino — APPROVED** [review]
hide the pain 🐐

**Review by skylarbarrera — APPROVED** [review]

**Review by ibrahimtaveras00 — APPROVED** [review]
Good on both OS's

**Review by jinchung — APPROVED** [review]
🌮

**Review by ibrahimtaveras00 — APPROVED** [review]

**Pull request merged**
