### PR TITLE
animate flip

### PR DESCRIPTION
**Pull request by osdnk**
https://streamable.com/w88jzp

### CODE REVIEW

**Comment by skylarbarrera** [comment]
can we close? i think @osdnk/flip-reanimated replaces right? checking out rn

**Comment by osdnk** [comment]
No, here I have added a fancy animation while pressing "flip". If we don't need/want this, feel free to close

**Comment by skylarbarrera** [comment]
> No, here I have added a fancy animation while pressing "flip". If we don't need/want this, feel free to close

oh no i like fancy, @osdnk can you rebase and review today

**Comment by brunobar79** [comment]
Needs rebase

**Comment by skylarbarrera** [comment]
@osdnk can u rebase? i like fancy animations made my michal

**Pull request closed without merging**
