### PR TITLE
Support sending concurrent rap actions

### PR DESCRIPTION
**Pull request by jinchung**
### Changes
- Hooks up the rap actions to the latest changes made to exchange modal / swap redux
- Uses the nonce of the first transaction to determine the nonces of the following rap actions
- If a swap requires an approval, then "assume" the correct method name to use is the non-FoT method and use a higher gas limit when sending the transaction (do not display this to the user)

### Note on FoT:
- We estimate gas on swaps not only to estimate the gas limit, but also to determine if the method name should support fee on transfer tokens or not (e.g, to choose between `swapExactTokensForTokens` or `swapExactTokensForTokensSupportingFeeOnTransferTokens` etc)
- If the gas estimation fails on these method names, we were previously returning the method name as null, and the swap execution would fail
- If an input token needs to be unlocked, then the gas estimations of a swap using that token will always fail
- Thus, if we are sending concurrent raps, and an approval is needed, we will not be able to know the correct gas limit nor the exact method name to use when we are constructing the concurrent rap
- Fee on Transfer tokens are tokens where a fee is taken on every transfer (such as a deflationary token) - requiring a slippage that at least covers the fee
- These FoT tokens are presumably rare / an edge case. So for now, we will assume that most of the time, the regular (non-FoT) method is the safest bet, and we will bump up the gas limit when sending the txn inside the concurrent rap

### Testing:
- Swaps (ETH to token, token to ETH, token to token, requiring approvals and not)
- Compound withdrawals
- Compound deposits (deposit, unlock and deposit, swap and deposit, unlock and swap and unlock and deposit)
- Transactions list should be updated as expected (known issue: on withdrawals, the native value of the transaction amount is not populated so it just shows $0.00 in the transaction list when pending)
- The rap actions are sent concurrently, one right after the other - we should verify that they stay in the correct order in the transaction list whether they are pending or become confirmed

### CODE REVIEW

**Review by gigilove2001 — APPROVED** [review]

**Comment by jinchung** [comment]
@skylarbarrera I was noticing some intermittent weirdness on the native transaction list when the asset icons wouldn't match up with the underlying asset. Looking into this separately, as I don't expect any of my code changes here to have changed that, and confirmed that when I "add new pending transactions", it does send over the correct data.

**Comment by jinchung** [comment]
@skylarbarrera Also sometimes I would notice where the swaps would be "squished" with the wrong transactions in the transaction list. Also looking into this separately, but let me know if you're also seeing this

**Review by brunobar79 — APPROVED** [review]
This is 🔥🔥🔥 

@skylarbarrera  make sure you test speed up / cancellation for raps and normal tx too!

**Review by skylarbarrera — APPROVED** [review]
LGTM 💯

**Pull request merged**
