### PR TITLE
Do not use alerts for simple messages

### PR DESCRIPTION
**Pull request by osdnk**
Fixes RNBW-4028
Figma link (if any):

## What changed (plus any additional context for devs)

I added a wrapper.

## Screen recordings / screenshots

https://user-images.githubusercontent.com/25709300/182613736-49836d24-2c99-42f5-9041-073a27bc0d9a.mov

## What to test
Go through the app, especially through various backup flow scenarios, where we have a lot of those

### CODE REVIEW

**Review by tchayen — APPROVED** [review]
The ones I found looked good, but I am afraid I skipped most of them (I don't know where to look).

**Comment by osdnk** [comment]
yea, me neither, i cannot find everything, but I think it's ok

**Review by terrysahaidak — APPROVED** [review]
LGTM.

The only change here i disagree is that now we have default import for Alert instead of named  one. 

Also this alert may conflict and confuse devs with the `src/components/alert`

**Review by perunt — APPROVED** [review]
Checked a few alerts and looks good

**Pull request merged**
