### PR TITLE
Support rendering markdown from OpenSea API

### PR DESCRIPTION
**Pull request by sbauch**
hey frens - this is a super tiny thing that was bothering me, and since it's open source I figured I'd work on it myself!!

There are possibly other places this could be useful, but without much familiarity with the codebase this is what I did for now.

I also think some more thought should go into thing like styling markdown headers etc.,  but didn't want to go too far without putting this in front of the team.

| before: |  after: |
|---|---|
| before | after |

### CODE REVIEW

**Comment by skylarbarrera** [comment]
@sbauch very cool, running CI now to make sure everything is 👌  and will have our designer take a look!

**Comment by sbauch** [comment]
awesome, yeah im not sure what this check is!!

design-wise, I did my best to match. I use the existing Text component to render a markdown "paragraph" - there were some differences in how the markdown interpreter treated paragraph breaks, so I added a bit of margin to try to get it close!

we may also want to add components for things like headings, and it's a bit puzzling that italics aren't italicizing. But I think it's an improvement over seeing the markdown underscores?

**Comment by sbauch** [comment]
any thoughts on this? its obviously not a huge deal but would love to work on some more things if this feels like a competent addition! im still not really sure about CI, getting a react native app running on my own machine is enough trouble as it is. and yeah, lets talk design, i think its close to what was there but could be more perfect!

**Comment by osdnk** [comment]
Yeah, it's really good for us. We will merge this!

**Comment by mikedemarais** [comment]
closing in favor of https://github.com/rainbow-me/rainbow/pull/2090

**Pull request closed without merging**
