### PR TITLE
Fix Android Status Bar issues

### PR DESCRIPTION
**Pull request by terrysahaidak**
Fixes RNBW-4271, RNBW-2786, RNBW-2666, RNBW-4263, RNBW-4043
Figma link (if any):

## What changed (plus any additional context for devs)

On android 11+, when the theme is light, the app would just use the status bar's style used on the splash screen (light), and stuck with that, the API for changing the status bar would just not work.

This PR introduces a fix for the status bar from RN 0.69. Since we patch RN now, ~we compile it from sources on android, too - the same as we do on iOS.~ we use forked version of RN where i applied this patch and built it. So nothing's change except for the package.json

Also, this PR refactors the way we handle the status bar and fixes it for some of the screens like Expanded NFT State.

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels? (`team1/team2`, `critical path`, `release`, `dev QA`)
- [x] Did you test both iOS and Android?
- [x] If your changes are visual, did you check both the light and dark themes?
- [ ] Added e2e tests? If not, please specify why
- [ ] If you added new critical path files, did you update the CODEOWNERS file?
- [ ] If no `dev QA` label, did you add the PR to the QA Queue?

### CODE REVIEW

**Review by tchayen — APPROVED** [review]
Played a bit with the app and didn't notice any issues. Great work!

**Review by perunt — APPROVED** [review]

**Review by brunobar79 — APPROVED** [review]
Approving to unblock.  `/android`  changes LGTM

**Review by estebanmino — APPROVED** [review]
didn't do a full dev QA, code lgtm

**Review by osdnk — APPROVED** [review]

**Review by BrodyHughes — CHANGES_REQUESTED** [review]
Screenshot_20220921-122514
Only issue I see as of now. Will keep looking in the meantime while waiting for the fix. @terrysahaidak said he would handle it in the morning!

**Review by BrodyHughes — APPROVED** [review]

**Pull request merged**
