### PR TITLE
Profiles: Support contenthash

### PR DESCRIPTION
**Pull request by jxom**
Fixes TEAM2-434
Fixes TEAM2-440

## What changed (plus any additional context for devs)

This PR aims to fix a bug where the "Content" field in the create/edit profile flow was crashing. The reason for this is because we didn't polyfill `TextEncoder` (I think a merge conflict may have removed the polyfill we had earlier). 
It also turns out that setting a content hash never actually worked properly anyway. So this PR fixes that too.

## Screen recordings / screenshots

Adding a content hash:

https://www.loom.com/share/d705f44204304440a27f7b73ac2e3908

Removing a content hash:

https://www.loom.com/share/1997319b2e8948f5b0b1f01da28d8243

## What to test

- Ensure that you can successfully add a "Content" field by itself (setContenthash) on the Create/Edit Profile screen
- Ensure that you can successfully add a "Content" field with other fields (multicall) on the Create/Edit Profile screen
- Ensure that sending an ENS with the "Content" field populated, and the checkbox to clear records checked, that it clears the "Content" field.

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels? (`team1/team2`, `critical path`, `release`, `dev QA`)
- [x] Did you test both iOS and Android?
- [x] If your changes are visual, did you check both the light and dark themes?
- [x] Added e2e tests? If not, please specify why

### CODE REVIEW

**Review by estebanmino — COMMENTED** [review]
devQA
delete https://www.loom.com/share/61ebd7cafcff46d9ba0b8c39662f0827
add content hash https://www.loom.com/share/0965eb4697c64f31926296a5ccb2df9f was was spiking 😓  so the result is not in the video

**Review by estebanmino — APPROVED** [review]
code lGTM and devQA videos in a previous comment 🚀

**Comment by benisgold** [comment]
Test sending ens w/ content hash with "clear records" checked: https://www.loom.com/share/4b28513d330740998583c6cdea335263

**Review by benisgold — APPROVED** [review]
approved, see QA vids above

**Review by pugson — APPROVED** [review]

**Review by skylarbarrera — APPROVED** [review]
👌

**Pull request merged**
