### PR TITLE
Make dedicated stack from SendSheet

### PR DESCRIPTION
**Pull request by osdnk**
https://streamable.com/dmmsx

### CODE REVIEW

**Comment by wojtus7** [comment]
Hi, @osdnk!
Shouldn't contact modal backdrop darken send list modal as well as wallet screen behind it? (you can see the line at the top of the screen remain white when contact modal is opened)

**Comment by osdnk** [comment]
I reduced opacity and I think it looks ok 
image

**Comment by osdnk** [comment]
Previosuly: 
image

**Comment by christianbaroni** [comment]
Looking good @osdnk !

I think the background could be slightly darker, maybe like 0.5

Only other thing, can this be centered vertically?

8DB4978D-9FC0-4C76-94C3-8DDD4128163A

**Pull request merged**
