### PR TITLE
Profiles: Fix ENS expanded state edit button

### PR DESCRIPTION
**Pull request by jxom**
Fixes TEAM2-364

## What changed (plus any additional context for devs)

This PR fixes an issue on Android where pressing the "Edit" button on the ENS expanded state, the user would be directed to the search sheet.

The fix in this PR omits the `initialScrollPosition` prop as it is now redundant as we have upgraded our pager view (this was done in swaps)

## Screen recordings / screenshots

https://www.loom.com/share/67da8caa9b6e4d868413c2758f8967ac

### CODE REVIEW

**Review by estebanmino — COMMENTED** [review]
https://www.loom.com/share/b9116da26aa344e385cce052c5df81e1 yess

**Comment by estebanmino** [comment]
@jxom is it possible to add this flow to e2e?

**Comment by pugson** [comment]
e2e failing 😭

**Review by estebanmino — APPROVED** [review]
EDIT: wrong pr

**Review by benisgold — APPROVED** [review]

**Pull request merged**
