### PR TITLE
use non watched wallet instead of primary

### PR DESCRIPTION
**Pull request by brunobar79**
Fixes RNBW-####
Figma link (if any):

## What changed (plus any additional context for devs)
Pkeys are not considered primary so we have to use the non watched wallet instead of the primary as a default.

## Screen recordings / screenshots

Slack

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels? (`team1/team2`, `critical path`, `release`, `dev QA`)
- [x] Did you test both iOS and Android?
- [x] If your changes are visual, did you check both the light and dark themes?
- [x] Added e2e tests? If not, please specify why
- [x] If you added new critical path files, did you update the CODEOWNERS file?
- [x] If no `dev QA` label, did you add the PR to the QA Queue?

### CODE REVIEW

**Review by estebanmino — APPROVED** [review]
code lgtm

**Review by ibrahimtaveras00 — APPROVED** [review]
Looks good on both OS's 👍🏽

**Pull request merged**
