### PR TITLE
Tweak InteractionManager to finish all interactions at some point

### PR DESCRIPTION
**Pull request by osdnk**
I observed that InteractionManager sometimes has some uncleaned tasks. Most likely, it's a bug made us or some library. 
However, I think it's worth to assure that every interaction won't block the manager for longer than 2 seconds. I assume that none of our interactions/animations takes longer than 2 seconds and if it does, it's a bug.

### CODE REVIEW

**Comment by osdnk** [comment]
This will tweak our stubborn bug related to the freezing of buttons. Actually, they were waiting for interaction to be finished that never happened. My intuition is that it might be some timeout/callback clearing some handle that is never called because of dismissing modal, but I cannot prove it. I added a sentry log to observe when it actually happens and hopefully it will give us some clues about how to solve it in a more elegant way.

**Review by mikedemarais — APPROVED** [review]
> This will tweak our stubborn bug related to the freezing of buttons. Actually, they were waiting for interaction to be finished that never happened. My intuition is that it might be some timeout/callback clearing some handle that is never called because of dismissing modal, but I cannot prove it. I added a sentry log to observe when it actually happens and hopefully it will give us some clues about how to solve it in a more elegant way.

i have some ideas where this could be happening. thanks for figuring this out and making this shim 💘️

**Comment by osdnk** [comment]
Where it can be? --
Pozdrawiam
Michał Osadnik

**Comment by mikedemarais** [comment]
> Where it can be?

@osdnk maybe this ternary? https://github.com/rainbow-me/rainbow/blob/develop/src/hooks/useInteraction.js#L8

**Pull request merged**
