### PR TITLE
Profiles: autopopulate ens name and avatar when adding contact

### PR DESCRIPTION
**Pull request by benisgold**
Fixes RNBW-3417

## What changed (plus any additional context for devs)
- added ens to rainbow contact info
- use ens name when contacts are added/modified to get ens avatar

## PoW (screenshots / screen recordings)
https://user-images.githubusercontent.com/15272675/166005384-92d35865-d566-412a-b06b-6f1ee03f5387.mp4

## Dev checklist for QA: what to test
- make sure that nothing is broken when profiles are disabled

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels?
- [ ] Added e2e tests? if not please specify why
- [ ] If you added new files, did you update the CODEOWNERS file?

### CODE REVIEW

**Comment by benisgold** [comment]
i noticed that discover search isn't loading ens avatars, will fix that in a sec

**Comment by benisgold** [comment]
also gonna fix how send sheet search suggests ens names

**Review by estebanmino — APPROVED** [review]
🔥 🔥 🔥 🔥

**Review by jxom — APPROVED** [review]
lgtm

**Pull request merged**
