### PR TITLE
Reset savings data when switching accounts

### PR DESCRIPTION
**Pull request by jinchung**
Example scenario with issue:
- Clearing all localstorage
- Load a wallet that has savings (e.g, poopcoin.eth)
- Load a wallet that does not have savings (e.g, 0x7044a3E6bf3baf4F0d2F8884A2Ee4E2D838f8902)
- Previously, you would see poopcoin's Savings show up in the second wallet

We were not resetting the results when switching between wallets, so there would be some delay before the next wallet's data would be fully fetched. Now, I just reset the result.

### CODE REVIEW

**Review by brunobar79 — APPROVED** [review]
LGTM!

**Comment by skylarbarrera** [comment]
I'm having the previous wallet's savings data carry over very consistently, the only way to clear and get the current wallets is to fetch more data.

Seems to happen most frequently when moving from the first wallet to a secondary, hasn't happened once moving from the 2nd wallet to the first(data always displays correctly in this case)

**Comment by skylarbarrera** [comment]
Also looks like there's some small linting errors!

**Review by skylarbarrera — APPROVED** [review]
👌

**Comment by jinchung** [comment]
Just as a note: discovered from Skylar's testing, there are still some issues that need to be investigated, but it is better to have this PR in, so I will merge this in now to not block the release.

**Pull request merged**
