### PR TITLE
improve discover search performance

### PR DESCRIPTION
**Pull request by estebanmino**
Improve performance by not using lodash `map`, from 1500ms to 500ms for searching on the assets list

Fixes RNBW-1484
Fixes RNBW-1317

### CODE REVIEW

**Comment by nicoglennon** [comment]
LGTI after passing CI 🏎

**Review by nicoglennon — APPROVED** [review]

**Comment by skylarbarrera** [comment]
search results seem more performant but the input handling and switching search queries is slow/not automatic: https://cloud.skylarbarrera.com/Screen-Recording-2021-09-01-08-56-20.mp4

The unverified/low liquidity headers are sometimes sticky to the middle of the list instead of the top

we're also showing a multiple ~4x or so of the amount of token results compared to what is currently on develop, not sure if due to the search changes but compare the search 'CAT' on your phone

**Comment by estebanmino** [comment]
@skylarbarrera  just pushed some changes that should improve this even further

- search went down from 1900 ms to 900 ms on the asset list by removing `lodash` methods and upgrading `match-sorter` probably that's why you see more assets, from what I'm seeing all result matches the search string
- https://github.com/rainbow-me/rainbow/pull/2358/files#diff-e59ab43061cd815ca989ce349667b02ebc0fef1940b0f7edc7e9f88adc45752fL89 triggering fetch from there was actually triggering multiple searches at the same time, I was able to repro infinite loops on that typing fast on the search input, so I put that logic on a callback using the same debounce logic that was already in place
- I noticed that 800 out of that 900 ms of the search time was coming from `filteredLow` list. So I changed the code to update the list with the other lists that take less time to compute (100 ms) in order to render something for the user while we wait for the big list `filteredLow` to compute the search

**Review by skylarbarrera — APPROVED** [review]
💯💯💯

**Pull request merged**
