### PR TITLE
Unify slack sheets

### PR DESCRIPTION
**Pull request by osdnk**
Fixes RAI-955

Are you sure, @brunobar79 it does not work?

I observed that sometimes it breaks, but it's not a reason of those changes. 

image
I made this and it works always

### CODE REVIEW

**Comment by brunobar79** [comment]
@osdnk  What it broke was the UI. The white part of the sheet as showing in the top middle section of the screen like this:

Screen Shot 2020-11-11 at 6 31 47 PM

while it should show aligned to the bottom like this:

Screen Shot 2020-11-09 at 1 20 48 AM

**Comment by osdnk** [comment]
ah okay

czw., 12 lis 2020 o 01:32 Bruno Barbieri <notifications@github.com>
napisał(a):

**Comment by osdnk** [comment]
can you try now, @brunobar79?

**Comment by osdnk** [comment]
@brunobar79 honey

**Comment by brunobar79** [comment]
iOS is fine Android is still broken.

Screen Shot 2020-11-18 at 11 54 47 PM
Screen Shot 2020-11-18 at 11 56 14 PM
Screen Shot 2020-11-19 at 12 01 38 AM


LMK if you want me to show you how to test it.

**Comment by osdnk** [comment]
close #1478

**Pull request closed without merging**
