### PR TITLE
Add support for .crypto domain resolution

### PR DESCRIPTION
**Pull request by sudoryan**
Adds support for .crypto address resolution
Extends resolution functionality from ENS lookups
To test functionality: brad.crypto

example

### CODE REVIEW

**Review by brunobar79 — CHANGES_REQUESTED** [review]
Thanks for your PR!

Before merging this there's a few things we would like you to change:

- Revert all UI related changes
- Fix merge conflicts / rebase
- Make sure e2e are passing
- Can you include a video of the feature working while importing a wallet and sending assets?

**Comment by osdnk** [comment]
Re: 1. Even though we want to accept .crypto, we want to make it not impacting UI at all. 
This being said, we want to keep not mentioning .crypto in prompts and stay just with ENS.

**Comment by sudoryan** [comment]
Hi @brunobar79 , how am I able to run the Bitrise tests to see if my fixes have worked?

**Comment by osdnk** [comment]
I have rerun and it passes, thanks

**Comment by osdnk** [comment]
Next time you can just push a new commit instead of amending. Then CI will just start working

**Comment by skylarbarrera** [comment]
Hey @sudoryan,

Thanks for the leg work! I've gone ahead and cleaned up/fixed some of the remaining issues and have submitted a new PR: https://github.com/rainbow-me/rainbow/pull/1714, should have it included in our next release! Will reach out to your team closer to then!

**Pull request closed without merging**
