### PR TITLE
swaps promo: add network check

### PR DESCRIPTION
**Pull request by skylarbarrera**
Fixes RNBW-4409
Figma link (if any):

## What changed (plus any additional context for devs)

added a network check so we dont show on goerli 

## Screen recordings / screenshots

logs: https://cloud.skylarbarrera.com/Screen-Shot-2022-08-29-17-35-51.61.png

PoW: https://cloud.skylarbarrera.com/Screen-Recording-2022-08-29-17-36-29.mp4

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels? (`team1/team2`, `critical path`, `release`, `dev QA`)
- [x] Did you test both iOS and Android?
- [x] If your changes are visual, did you check both the light and dark themes?
- [x] Added e2e tests? If not, please specify why
- [x] If you added new critical path files, did you update the CODEOWNERS file?
- [x] If no `dev QA` label, did you add the PR to the QA Queue?

### CODE REVIEW

**Review by estebanmino — APPROVED** [review]
can confirm i'm seeing the `wrong_network` error while starting the app on goerli for the first time 🚀

**Review by ibrahimtaveras00 — APPROVED** [review]
Was able to confirm that when on Goerli Testnet and switching to @skylar/network-check on TF I didn't see the swaps promo, but when switching to mainnet and relaunching app I did correctly see the promo!  QA Passed 👍🏽

**Pull request merged**
