### PR TITLE
feat: new Explain sheet

### PR DESCRIPTION
**Pull request by estrattonbailey**
Fixes APP-512

## What changed (plus any additional context for devs)
New Explain sheet. Usage:

```tsx
import * as ex from '@/screens/Explain';

const { open } = ex.useExplainSheet();

open(() => (
  <>
    <ex.Title>This is the title component</ex.Title>
    ...etc
  </>
), { sheetHeight: 400, ...options });
```

## What to test
I've been pasta-ing this into `ProfileActionButtonsRow` when clicking on the `BuyButton`.
```tsx
    open(() => (
      <>
        <ex.Emoji>👋</ex.Emoji>
        <ex.Title>New Sheet Who Dis</ex.Title>
        <ex.Body>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sed ex id lacus tempor hendrerit eu sit amet dolor. Curabitur arcu nisl, aliquam nec risus id, laoreet consequat magna.</ex.Body>
        <ex.Body>Etiam pharetra nulla non est finibus, ut luctus nisi viverra. Nunc id sem sit amet ipsum posuere pharetra ut id nisl. Pellentesque a suscipit nisl.</ex.Body>
        <ex.Footer>
          <ex.Button label='Click Me' />
        </ex.Footer>
      </>
    ), { sheetHeight: 450 });
```

## Screen recordings / screenshots
Simulator Screen Shot - iPhone 14 Pro - 2023-04-03 at 16 34 48
Screenshot_20230403_163858

### CODE REVIEW

**Review by jkadamczyk — APPROVED** [review]
Way better than current 1000+ line long ExplainSheet component

**Comment by jkadamczyk** [comment]
@estrattonbailey One king though. Your android screenshot shows it as full screen sheet, was that intended?

**Review by benisgold — APPROVED** [review]
one small step for man, one giant leap for mankind - looks great, this sheet was such a pain

i'm still a proponent of the dynamic height thing i messaged about tho

**Comment by estrattonbailey** [comment]
@jkadamczyk whoops, good call, fixed.

@benisgold tried for a while to get it to work, but couldn't figure out a way to prevent it from flashing full-height and then resizing. Any ideas? If you think it's easy feel free to push a commit here 😛

**Comment by benisgold** [comment]
@estrattonbailey hmmm weird i will play around with it on your branch

**Pull request merged**
