### PR TITLE
New send flow design

### PR DESCRIPTION
**Pull request by christianbaroni**
to do:
- [x] small phone handling
- [x] 'x available' text should change between $ and token balance depending on focused input
- [x] input focus is broken (broken in develop)

Input focus - current behavior will be:
- Autofocus recipient field when opening swap
- After an asset is selected, autofocus the native input field
- When changing focus to the asset input, change the coin bottom row text to the token balance (otherwise show "$.. available")
- This behavior should occur for both regular tokens as well as savings tokens
PoW: https://recordit.co/3FyU0kfCgK

For testing:
- Also check that the SendSheet input focus after QR code scanning an address behaves as expected
- Confirm behavior on Android

Simulator Screen Shot - iPhone 12 Pro - 2021-06-28 at 03 24 06

### CODE REVIEW

**Comment by christianbaroni** [comment]
Screen Shot 2021-06-28 at 11 41 51 PM

**Comment by skylarbarrera** [comment]
posting some android issues here:

balance  centering, should fix if you add line height: https://cloud.skylarbarrera.com/Screen-Shot-2021-06-29-20-50-21.99.png

inputs need a width on android: https://cloud.skylarbarrera.com/Screen-Shot-2021-06-29-20-50-40.04.png

save icon is cut off: https://cloud.skylarbarrera.com/Screen-Shot-2021-06-29-20-52-47.14.png

selected token shadow cut-off: https://cloud.skylarbarrera.com/Screen-Shot-2021-06-29-20-53-18.69.png

**Review by jinchung — APPROVED** [review]
🌮

**Comment by skylarbarrera** [comment]
This looks so good 🔥 

I'll rewrite the send sheet tests to handle the new gas flow in the AM.

Only Issue i see on android:

Max Button does not work -  nested buttons are messy on android; maybe we can unnest and position absolute.

**Review by skylarbarrera — APPROVED** [review]
I'm fine with merging with the max button issue on android since its blocking.

functionality seems 👌  otherwise

**Pull request merged**
