### PR TITLE
WC connection failed sheet fix

### PR DESCRIPTION
**Pull request by brunobar79**
If there's an exception we're not clearing the timeout

### CODE REVIEW

**Review by skylarbarrera — APPROVED** [review]
👌

**Comment by skylarbarrera** [comment]
this we should clear timeout here too right?

https://github.com/rainbow-me/rainbow/blob/dbef87746d79e8f8699e3a1cea3bf20dfb168bf3/src/redux/walletconnect.js#L209

**Review by jinchung — APPROVED** [review]
🌮

**Comment by brunobar79** [comment]
>  we should clear timeout here too right?
> 
> 
> 
> https://github.com/rainbow-me/rainbow/blob/dbef87746d79e8f8699e3a1cea3bf20dfb168bf3/src/redux/walletconnect.js#L209

It's already cleared in line 177

**Pull request merged**
