### PR TITLE
Fix exchange rate in swap review modal 

### PR DESCRIPTION
**Pull request by l2succes**
Fixes TEAM2-162
Fixes TEAM2-163

## What changed (plus any additional context for devs)
- Using `convertRawAmountToDecimalFormat` on amounts before calculating the rate
- Fix percentage by using `convertAmountToPercentageDisplayWithThreshold`

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels?
- [x] Added e2e tests? if not please specify why
- [x] If you added new files, did you update the CODEOWNERS file?

### CODE REVIEW

**Comment by l2succes** [comment]
### Updated percentage fee

**Review by estebanmino — COMMENTED** [review]
i'm not able to see the latest changes to the explainer in the code 🤔

**Comment by l2succes** [comment]
@estebanmino I just pushed the explainer changes

**Review by estebanmino — APPROVED** [review]
🔥 🚀

**Pull request merged**
