### PR TITLE
Remove unused dependencies

### PR DESCRIPTION
**Pull request by tchayen**
## What changed (plus any additional context for devs)

This PR removes unused dependencies.

## Final checklist

- [x] Assigned individual reviewers?
- [x] Added labels?

### CODE REVIEW

**Review by osdnk — APPROVED** [review]
If the build will pass, this proves that we're safe

**Comment by tchayen** [comment]
This `punycode` is coming back in some stage of `yarn fast`. But I can't reliably reproduce it. I tried all involved commands separately without luck (happened just once and I am not even sure which one caused it).

**Comment by tchayen** [comment]
@skylarbarrera Michał investigated this weird `punycode` reappearance but this issue in general has so low priority that it doesn't make sense to waste time for it now.

We can merge this as is and optionally investigate this later in future.

**Comment by osdnk** [comment]
is there something blocking us?

**Comment by tchayen** [comment]
Just the reviews. @skylarbarrera ping

**Review by terrysahaidak — APPROVED** [review]

**Pull request merged**
